(self.AMP = self.AMP || []).push({n:"amp-image-lightbox", f:(function(AMP) {var g;function l(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]};Date.now();self.log=self.log||{user:null,dev:null};var n=self.log;function p(){if(n.user)return n.user;throw Error("failed to call initLogConstructor");}function q(){if(n.dev)return n.dev;throw Error("failed to call initLogConstructor");};function aa(a,b){for(var c,d=a;d&&d!==c;d=d.parentElement)if(b(d))return d;return null}function ba(a){var b="figure";if(a.closest)return a.closest(b);b=b.toUpperCase();return aa(a,function(a){return a.tagName==b})}function r(a,b){var c=a.getElementsByTagName(b);return c[0]||null};function t(a,b){a=a.__AMP_TOP||a;var c=a.services&&a.services[b]&&a.services[b].obj;return c}function ca(a){var b=a;if(b.nodeType){var c=(b.ownerDocument||b).defaultView,d=c=c.__AMP_TOP||c,e=c.services;e||(e=c.services={});c=e;(e=c.ampdoc)||(e=c.ampdoc={obj:null,promise:null,resolve:null});e.obj||(e.obj=(void 0)(d),e.resolve&&e.resolve(e.obj));b=e.obj.getAmpDoc(b)}var f=b.isSingleDoc()?b.win:b;return f&&f.services&&f.services.history&&f.services.history.obj};function u(a){return!!(a.complete||"complete"==a.readyState||a.document&&"complete"==a.document.readyState)};function w(){this.U=[]}g=w.prototype;g.add=function(a){var b=this;this.U.push(a);return function(){b.remove(a)}};g.remove=function(a){a=this.U.indexOf(a);-1<a&&this.U.splice(a,1)};g.removeAll=function(){this.U.length=0};g.fire=function(a){for(var b=this.U,c=0;c<b.length;c++)(0,b[c])(a)};g.getHandlerCount=function(){return this.U.length};var x,da="Webkit webkit Moz moz ms O o".split(" ");function ea(a,b,c){var d,e=a.style;x||(x=Object.create(null));var f=x[b];if(!f){f=b;if(void 0===e[b]){var h=b.charAt(0).toUpperCase()+b.slice(1);a:{for(var k=0;k<da.length;k++){var m=da[k]+h;if(void 0!==e[m]){h=m;break a}}h=""}void 0!==e[h]&&(f=h)}x[b]=f}(b=f)&&(a.style[b]=d?c+d:c)}function y(a,b){for(var c in b)ea(a,c,b[c])};function z(a,b,c,d){return{left:a,top:b,width:c,height:d,bottom:b+d,right:a+c}}function A(a){return z(Number(a.left),Number(a.top),Number(a.width),Number(a.height))};function fa(a){var b=a.getAttribute("srcset");if(b){a=b.match(/\s*(?:[\S]*)(?:\s+(?:-?(?:\d+(?:\.(?:\d+)?)?|\.\d+)[a-zA-Z]))?(?:\s*,)?/g);p().assert(0<a.length,"srcset has to have at least one source: %s",void 0);for(var c=[],d=0;d<a.length;d++){var e=a[d].trim();","==e.substr(-1)&&(e=e.substr(0,e.length-1).trim());var f=e.split(/\s+/,2);if(0!=f.length&&(1!=f.length||f[0])&&(2!=f.length||f[0]||f[1]))if(e=f[0],1==f.length||2==f.length&&!f[1])c.push({url:e,width:void 0,dpr:1});else{var f=f[1].toLowerCase(),
h=f.substring(f.length-1);"w"==h?c.push({url:e,width:parseFloat(f),dpr:void 0}):"x"==h&&c.push({url:e,width:void 0,dpr:parseFloat(f)})}}return new B(c)}var k=p().assert(a.getAttribute("src"),'Either non-empty "srcset" or "src" attribute must be specified: %s',a);return new B([{url:k,width:void 0,dpr:1}])}
function B(a){p().assert(0<a.length,"Srcset must have at least one source");this.C=a;var b=!1,c=!1;for(a=0;a<this.C.length;a++){var d=this.C[a];p().assert((d.width||d.dpr)&&(!d.width||!d.dpr),"Either dpr or width must be specified");b=b||!!d.width;c=c||!!d.dpr}p().assert(!b||!c,"Srcset cannot have both width and dpr sources");b?this.C.sort(ga):this.C.sort(ha);this.kb=b;this.Wa=c}
B.prototype.select=function(a,b){var c=-1;if(this.kb)for(var c=-1,d=1E6,e=1E6,f=0;f<this.C.length;f++){var h=this.C[f],h=h.width?h.width/b:d/2,d=Math.min(d,h),h=Math.abs((h-a)/a-.2);h<e&&(e=h,c=f)}else if(this.Wa){a=-1;c=1E6;for(d=0;d<this.C.length;d++)e=Math.abs((this.C[d].dpr||1)-b),e<c&&(c=e,a=d);c=a}return-1!=c?this.C[c]:this.getLast()};B.prototype.getLast=function(){return this.C[this.C.length-1]};B.prototype.getSources=function(){return this.C};
B.prototype.stringify=function(){for(var a=[],b=0;b<this.C.length;b++){var c=this.C[b];c.width?a.push(c.url+" "+c.width+"w"):c.dpr?a.push(c.url+" "+c.dpr+"x"):a.push(""+c.url)}return a.join(", ")};function ga(a,b){p().assert(a.width!=b.width,"Duplicate width: %s",a.width);return b.width-a.width}function ha(a,b){p().assert(a.dpr!=b.dpr,"Duplicate dpr: %s",a.dpr);return b.dpr-a.dpr};function C(a,b,c){var d=this;this.Sa=t(a,"timer");this.Ya=b;this.Va=c||0;this.ba=-1;this.Ca=0;this.O=!1;this.Ta=function(){return d.ka()}}C.prototype.isPending=function(){return-1!=this.ba};C.prototype.schedule=function(a){var b=a||this.Va;this.O&&10>b&&(b=10);var c=Date.now()+b;return!this.isPending()||-10>c-this.Ca?(this.cancel(),this.Ca=c,this.ba=this.Sa.delay(this.Ta,b),!0):!1};C.prototype.ka=function(){this.ba=-1;this.Ca=0;this.O=!0;this.Ya();this.O=!1};
C.prototype.cancel=function(){this.isPending()&&(this.Sa.cancel(this.ba),this.ba=-1)};function D(a,b,c,d){var e=new ia(0,0,a,b,c,d,1,1);return e.solveYValueFromXValue.bind(e)}function ia(a,b,c,d,e,f,h,k){this.x0=a;this.y0=b;this.x1=c;this.y1=d;this.x2=e;this.y2=f;this.x3=h;this.y3=k}g=ia.prototype;g.solveYValueFromXValue=function(a){return this.getPointY(this.solvePositionFromXValue(a))};
g.solvePositionFromXValue=function(a){var b=1E-6,c=(a-this.x0)/(this.x3-this.x0);if(0>=c)return 0;if(1<=c)return 1;for(var d=0,e=1,f=0,h=0;8>h;h++){var f=this.getPointX(c),k=(this.getPointX(c+b)-f)/b;if(Math.abs(f-a)<b)return c;if(Math.abs(k)<b)break;else f<a?d=c:e=c,c-=(f-a)/k}for(h=0;Math.abs(f-a)>b&&8>h;h++)f<a?(d=c,c=(c+e)/2):(e=c,c=(c+d)/2),f=this.getPointX(c);return c};
g.getPointX=function(a){if(0==a)return this.x0;if(1==a)return this.x3;var b=this.lerp(this.x0,this.x1,a),c=this.lerp(this.x1,this.x2,a),d=this.lerp(this.x2,this.x3,a),b=this.lerp(b,c,a),c=this.lerp(c,d,a);return this.lerp(b,c,a)};g.getPointY=function(a){if(0==a)return this.y0;if(1==a)return this.y3;var b=this.lerp(this.y0,this.y1,a),c=this.lerp(this.y1,this.y2,a),d=this.lerp(this.y2,this.y3,a),b=this.lerp(b,c,a),c=this.lerp(c,d,a);return this.lerp(b,c,a)};g.lerp=function(a,b,c){return a+c*(b-a)};
var ja=D(.25,.1,.25,1),ka=D(.42,0,1,1),la=D(0,0,.58,1),ma=D(.42,0,.58,1),na={linear:function(a){return a},ease:ja,"ease-in":ka,"ease-out":la,"ease-in-out":ma};function oa(a){if(!a)return null;if("string"==typeof a){if(-1!=a.indexOf("cubic-bezier")){var b=a.match(/cubic-bezier\((.+)\)/);if(b){var c=b[1].split(",").map(parseFloat);if(4==c.length){for(var d=0;4>d;d++)if(isNaN(c[d]))return null;return D(c[0],c[1],c[2],c[3])}}return null}return na[a]}return a};function pa(){}function E(a,b){this.P=a;this.S=b||t(self,"vsync");this.Na=null;this.A=[]}function qa(a,b,c){var d=ra;return(new E(a)).setCurve(d).add(0,b,1).start(c)}E.prototype.setCurve=function(a){a&&(this.Na=oa(a));return this};E.prototype.add=function(a,b,c,d){this.A.push({delay:a,func:b,duration:c,curve:oa(d)});return this};E.prototype.start=function(a){var b=new sa(this.S,this.P,this.A,this.Na,a);b.Ia();return b};
function sa(a,b,c,d,e){var f=this;this.S=a;this.P=b;this.A=[];for(b=0;b<c.length;b++){var h=c[b];this.A.push({delay:h.delay,func:h.func,duration:h.duration,curve:h.curve||d,started:!1,completed:!1})}this.Xa=e;this.mb=this.lb=this.L=0;this.O=!1;this.Qa={};this.aa=new Promise(function(a,b){f.Ga=a;f.Fa=b});this.Ra=this.S.createAnimTask(this.P,{mutate:this.gb.bind(this)})}g=sa.prototype;g.then=function(a,b){return a||b?this.aa.then(a,b):this.aa};g.thenAlways=function(a){a=a||pa;return this.then(a,a)};
g.halt=function(a){F(this,!1,a||0)};g.Ia=function(){this.L=Date.now();this.O=!0;this.S.canAnimate(this.P)?this.Ra(this.Qa):(q().warn("Animation","cannot animate"),F(this,!1,0))};function F(a,b,c){if(a.O){a.O=!1;if(0!=c){1<a.A.length&&a.A.sort(function(a,b){return a.delay+a.duration-(b.delay+b.duration)});try{if(0<c)for(var d=0;d<a.A.length;d++)a.A[d].func(1,!0);else for(d=a.A.length-1;0<=d;d--)a.A[d].func(0,!1)}catch(e){q().error("Animation","completion failed: "+e,e),b=!1}}b?a.Ga():a.Fa()}}
g.gb=function(){if(this.O){for(var a=Date.now(),b=Math.min((a-this.L)/this.Xa,1),c=0;c<this.A.length;c++){var d=this.A[c];!d.started&&b>=d.delay&&(d.started=!0)}for(c=0;c<this.A.length;c++)if(d=this.A[c],d.started&&!d.completed)a:{var e,f;if(0<d.duration){if(f=e=Math.min((b-d.delay)/d.duration,1),d.curve&&1!=f)try{f=d.curve(e)}catch(h){q().error("Animation","step curve failed: "+h,h);F(this,!1,0);break a}}else f=e=1;1==e&&(d.completed=!0);try{d.func(f,d.completed)}catch(h){q().error("Animation","step mutate failed: "+
h,h),F(this,!1,0)}}1==b?F(this,!0,0):this.S.canAnimate(this.P)?this.Ra(this.Qa):(q().warn("Animation","cancel animation"),F(this,!1,0))}};function ta(a){var b;b=void 0===b?" ":b;return function(c,d){for(var e=[],f=0;f<a.length;f++){var h=(0,a[f])(c,d);"string"==typeof h&&e.push(h)}return e.join(b)}}function G(a,b){return function(c,d){for(var e in b)ea(a,e,b[e](c,d))}}function H(a,b){return function(c){return a+(b-a)*c}}function ua(a,b){return function(c){var d=a(c);"number"==typeof d&&(d+="px");if(!b)return"translate("+d+")";c=b(c);"number"==typeof c&&(c+="px");return"translate("+d+","+c+")"}}
function va(a){return function(b){return"scale("+a(b)+")"}};function wa(a,b,c,d){this.type=a;this.data=b;this.time=c;this.event=d}
function xa(a,b){this.K=a;this.j=[];this.ea=[];this.H=[];this.i=[];this.h=null;this.eb=b;this.pa=!1;this.ka=new C(a.ownerDocument.defaultView,this.Oa.bind(this));this.Pa=new w;this.Da=Object.create(null);this.Ma=this.cb.bind(this);this.Ka=this.ab.bind(this);this.La=this.bb.bind(this);this.Ja=this.$a.bind(this);this.K.addEventListener("touchstart",this.Ma);this.K.addEventListener("touchend",this.Ka);this.K.addEventListener("touchmove",this.La);this.K.addEventListener("touchcancel",this.Ja);this.Ea=
!1}function ya(a){var b=a.__AMP_Gestures;b||(b=new xa(a,!1),a.__AMP_Gestures=b);return b}g=xa.prototype;g.cleanup=function(){this.K.removeEventListener("touchstart",this.Ma);this.K.removeEventListener("touchend",this.Ka);this.K.removeEventListener("touchmove",this.La);this.K.removeEventListener("touchcancel",this.Ja);delete this.K.__AMP_Gestures;this.ka.cancel()};g.onGesture=function(a,b){var c=new a(this),d=c.getType(),e=this.Da[d];e||(this.j.push(c),e=new w,this.Da[d]=e);return e.add(b)};
g.onPointerDown=function(a){return this.Pa.add(a)};g.cb=function(a){var b=Date.now();this.pa=!1;this.Pa.fire(a);for(var c=0;c<this.j.length;c++)if(!this.H[c]&&(this.i[c]&&this.i[c]<b&&I(this,c),this.j[c].onTouchStart(a))){var d=c;this.ea[d]=!0;this.i[d]=0}J(this,a)};g.bb=function(a){for(var b=Date.now(),c=0;c<this.j.length;c++)this.ea[c]&&(this.i[c]&&this.i[c]<b?I(this,c):this.j[c].onTouchMove(a)||I(this,c));J(this,a)};
g.ab=function(a){for(var b=Date.now(),c=0;c<this.j.length;c++)this.ea[c]&&(this.i[c]&&this.i[c]<b?I(this,c):(this.j[c].onTouchEnd(a),(!this.i[c]||this.i[c]<b)&&I(this,c)));J(this,a)};g.$a=function(a){for(var b=0;b<this.j.length;b++){var c=b;this.H[c]=0;I(this,c)}J(this,a)};function J(a,b){var c=!!a.h||a.pa;a.pa=!1;if(!c)for(var d=Date.now(),e=0;e<a.j.length;e++)if(a.H[e]||a.i[e]&&a.i[e]>=d){c=!0;break}c&&(b.stopPropagation(),a.eb||b.preventDefault());a.Ea&&(a.Ea=!1,a.Oa())}
g.Oa=function(){for(var a=Date.now(),b=-1,c=0;c<this.j.length;c++)if(!this.H[c])this.i[c]&&this.i[c]<a&&I(this,c);else if(-1==b||this.H[c]>this.H[b])b=c;if(-1!=b){for(var d=0,c=0;c<this.j.length;c++)!this.H[c]&&this.ea[c]&&(d=Math.max(d,this.i[c]-a));if(2>d){for(var a=b,c=this.j[a],e=0;e<this.j.length;e++)if(e!=a){var f=e;this.H[f]=0;I(this,f)}this.H[a]=0;this.i[a]=0;this.h=c;c.acceptStart()}else this.ka.schedule(d)}};function I(a,b){a.ea[b]=!1;a.i[b]=0;a.H[b]||a.j[b].acceptCancel()}
function K(a,b){this.jb=a;this.ha=b}g=K.prototype;g.getType=function(){return this.jb};g.signalReady=function(a){var b=this.ha;if(b.h)this.acceptCancel();else{for(var c=Date.now(),d=0;d<b.j.length;d++)b.j[d]==this&&(b.H[d]=c+a,b.i[d]=0);b.Ea=!0}};g.signalPending=function(a){var b=this.ha;if(b.h)this.acceptCancel();else for(var c=Date.now(),d=0;d<b.j.length;d++)b.j[d]==this&&(b.i[d]=c+a)};g.signalEnd=function(){var a=this.ha;a.h==this&&(a.h=null,a.pa=!0)};
g.signalEmit=function(a,b){var c=this.ha.Da[this.getType()];c&&c.fire(new wa(this.getType(),a,Date.now(),b))};g.acceptStart=function(){};g.acceptCancel=function(){};g.onTouchStart=function(){return!1};g.onTouchMove=function(){return!1};g.onTouchEnd=function(){};function za(){}var Aa=Math.round(-16.67/Math.log(.95));function L(a,b,c){1>b&&(b=1);var d=a/b,e=.5+Math.min(b/33.34,.5);return d*e+c*(1-e)}function Ba(a,b,c,d,e,f){return(new Ca(a,b,c,d,e,f,void 0)).Ia()}function Ca(a,b,c,d,e,f,h){var k=this;this.S=h||t(self,"vsync");this.P=a;this.ra=f;this.a=b;this.b=c;this.va=d;this.wa=e;this.o=this.m=0;this.v=this.L=Date.now();this.aa=new Promise(function(a,b){k.Ga=a;k.Fa=b});this.Z=!1}g=Ca.prototype;
g.Ia=function(){this.Z=!0;if(.02>=Math.abs(this.va)&&.02>=Math.abs(this.wa))this.ra(this.a,this.b),this.sa(!0);else{this.m=this.va;this.o=this.wa;var a=this.fb.bind(this),b=this.sa.bind(this,!0);this.S.runAnimMutateSeries(this.P,a,5E3).then(b,b)}return this};g.halt=function(){this.Z&&this.sa(!1)};g.then=function(a,b){return a||b?this.aa.then(a,b):this.aa};g.thenAlways=function(a){a=a||za;return this.then(a,a)};
g.fb=function(a,b){if(!this.Z)return!1;this.v=Date.now();this.a+=b*this.m;this.b+=b*this.o;if(!this.ra(this.a,this.b))return!1;var c=Math.exp(-a/Aa);this.m=this.va*c;this.o=this.wa*c;return.02<Math.abs(this.m)||.02<Math.abs(this.o)};g.sa=function(a){this.Z&&(this.Z=!1,this.v=Date.now(),this.ra(this.a,this.b),a?this.Ga():this.Fa())};function M(a){K.call(this,"tap",a);this.b=this.a=this.f=this.g=0}l(M,K);M.prototype.onTouchStart=function(a){a=a.touches;if(!a||1!=a.length)return!1;this.g=a[0].clientX;this.f=a[0].clientY;return!0};M.prototype.onTouchMove=function(a){return(a=a.changedTouches||a.touches)&&1==a.length&&(this.a=a[0].clientX,this.b=a[0].clientY,a=8<=Math.abs(this.b-this.f),8<=Math.abs(this.a-this.g)||a)?!1:!0};M.prototype.onTouchEnd=function(){this.signalReady(0)};
M.prototype.acceptStart=function(){this.signalEmit({clientX:this.a,clientY:this.b},null);this.signalEnd()};function N(a){K.call(this,"doubletap",a);this.I=this.b=this.a=this.f=this.g=0}l(N,K);g=N.prototype;g.onTouchStart=function(a){if(1<this.I)return!1;a=a.touches;if(!a||1!=a.length)return!1;this.g=a[0].clientX;this.f=a[0].clientY;return!0};
g.onTouchMove=function(a){return(a=a.changedTouches||a.touches)&&1==a.length&&(this.a=a[0].clientX,this.b=a[0].clientY,a=8<=Math.abs(this.b-this.f),8<=Math.abs(this.a-this.g)||a)?(this.acceptCancel(),!1):!0};g.onTouchEnd=function(){this.I++;2>this.I?this.signalPending(300):this.signalReady(0)};g.acceptStart=function(){this.I=0;this.signalEmit({clientX:this.a,clientY:this.b},null);this.signalEnd()};g.acceptCancel=function(){this.I=0};
function O(a,b,c,d){K.call(this,a,b);this.fa=c;this.na=d;this.h=!1;this.o=this.m=this.N=this.v=this.L=this.W=this.V=this.b=this.a=this.f=this.g=0}l(O,K);g=O.prototype;g.onTouchStart=function(a){a=a.touches;if(!a||1!=a.length)return!1;this.L=Date.now();this.g=a[0].clientX;this.f=a[0].clientY;return!0};
g.onTouchMove=function(a){var b=a.changedTouches||a.touches;if(b&&1==b.length){var c=b[0].clientX,b=b[0].clientY;this.a=c;this.b=b;if(this.h)this.R(!1,!1,a);else if(a=Math.abs(c-this.g),c=Math.abs(b-this.f),this.fa&&this.na)(8<=a||8<=c)&&this.signalReady(-10);else if(this.fa)if(8<=a&&a>c)this.signalReady(-10);else{if(8<=c)return!1}else if(this.na)if(8<=c&&c>a)this.signalReady(-10);else{if(8<=a)return!1}else return!1}return!0};g.onTouchEnd=function(a){this.ta(a)};
g.acceptStart=function(){this.h=!0;this.V=this.g;this.W=this.f;this.N=this.L;this.g=this.a;this.f=this.b;this.R(!0,!1,null)};g.acceptCancel=function(){this.h=!1};
g.R=function(a,b,c){this.v=Date.now();var d=this.v-this.N;if(!b&&4<d||b&&16<d)this.m=L(this.a-this.V,d,this.m),this.o=L(this.b-this.W,d,this.o),this.m=1E-4<Math.abs(this.m)?this.m:0,this.o=1E-4<Math.abs(this.o)?this.o:0,this.V=this.a,this.W=this.b,this.N=this.v;this.signalEmit({first:a,last:b,time:this.v,deltaX:this.fa?this.a-this.g:0,deltaY:this.na?this.b-this.f:0,velocityX:this.fa?this.m:0,velocityY:this.na?this.o:0},c)};g.ta=function(a){this.h&&(this.h=!1,this.R(!1,!0,a),this.signalEnd())};
function P(a){O.call(this,"swipe-xy",a,!0,!0)}l(P,O);function Q(a){K.call(this,"tapzoom",a);this.h=!1;this.o=this.m=this.N=this.v=this.L=this.W=this.V=this.I=this.ib=this.hb=this.b=this.a=this.f=this.g=0}l(Q,K);g=Q.prototype;g.onTouchStart=function(a){if(this.h)return!1;a=a.touches;if(!a||1!=a.length)return!1;this.g=a[0].clientX;this.f=a[0].clientY;return!0};
g.onTouchMove=function(a){var b=a.changedTouches||a.touches;if(b&&1==b.length)if(this.a=b[0].clientX,this.b=b[0].clientY,this.h)this.R(!1,!1,a);else if(a=8<=Math.abs(this.b-this.f),8<=Math.abs(this.a-this.g)||a){if(0==this.I)return this.acceptCancel(),!1;this.signalReady(0)}return!0};g.onTouchEnd=function(a){this.h?this.ta(a):(this.I++,1==this.I?(this.signalPending(400),this.hb=this.a,this.ib=this.b):this.acceptCancel())};g.acceptStart=function(){this.I=0;this.h=!0;this.R(!0,!1,null)};
g.acceptCancel=function(){this.I=0;this.h=!1};g.R=function(a,b,c){this.v=Date.now();a?(this.L=this.v,this.m=this.o=0):2<this.v-this.N&&(this.m=L(this.a-this.V,this.v-this.N,this.m),this.o=L(this.b-this.W,this.v-this.N,this.o));this.V=this.a;this.W=this.b;this.N=this.v;this.signalEmit({first:a,last:b,centerClientX:this.g,centerClientY:this.f,deltaX:this.a-this.g,deltaY:this.b-this.f,velocityX:this.m,velocityY:this.o},c)};g.ta=function(a){this.h&&(this.h=!1,this.R(!1,!0,a),this.signalEnd())};var Da={"amp-img":!0,"amp-anim":!0},R=D(.4,0,.2,1),S=D(.4,0,.2,1),ra=D(.4,0,.2,1.4);
function Ea(a,b,c){this.ga=a;this.win=b;this.Za=c;this.oa=a.element.ownerDocument.createElement("div");this.oa.classList.add("-amp-image-lightbox-viewer");this.l=a.element.ownerDocument.createElement("img");this.l.classList.add("-amp-image-lightbox-viewer-image");this.oa.appendChild(this.l);this.la=null;this.T={alt:null,"aria-label":null,"aria-labelledby":null};this.ca=this.X=0;this.s=z(0,0,0,0);this.F=z(0,0,0,0);this.za=this.ja=this.da=this.c=1;this.ia=2;this.ya=this.xa=this.Ba=this.Aa=this.u=this.w=
this.f=this.g=0;this.M=null;Fa(this)}g=Ea.prototype;g.getElement=function(){return this.oa};g.getImage=function(){return this.l};g.getViewerBox=function(){return this.s};g.getImageBox=function(){return this.F};g.getImageBoxWithOffset=function(){var a;if(0==this.w&&0==this.u)a=this.F;else{a=this.F;var b=this.w,c=this.u;a=0==b&&0==c||0==a.width&&0==a.height?a:z(a.left+b,a.top+c,a.width,a.height)}return a};
g.reset=function(){var a=this;this.l.setAttribute("src","");Object.keys(this.T).forEach(function(b){a.l.removeAttribute(b);a.T[b]=null});this.l.removeAttribute("aria-describedby");this.la=null;this.F=z(0,0,0,0);this.ca=this.X=0;this.da=this.c=this.ja=1;this.ia=2;this.ya=this.xa=this.Ba=this.Aa=this.u=this.w=this.f=this.g=0;this.M&&this.M.halt();this.M=null};
g.init=function(a,b){var c=this;this.X=a.offsetWidth;this.ca=a.offsetHeight;this.la=fa(a);Object.keys(this.T).forEach(function(b){c.T[b]=a.getAttribute(b);c.T[b]&&c.l.setAttribute(b,c.T[b])});b&&u(b)&&b.src&&this.l.setAttribute("src",b.src)};
g.measure=function(){this.s=A(this.oa.getBoundingClientRect());var a=Math.min(this.s.width/this.X,this.s.height/this.ca),b=Math.min(this.X*a,this.s.width),c=Math.min(this.ca*a,this.s.height);16>=b-this.X&&(b=this.X,c=this.ca);this.F=z(Math.round((this.s.width-b)/2),Math.round((this.s.height-c)/2),Math.round(b),Math.round(c));y(this.l,{top:this.F.top+"px",left:this.F.left+"px",width:this.F.width+"px",height:this.F.height+"px"});this.da=this.c=1;this.f=this.u=this.g=this.w=0;T(this,this.c);U(this);
return Ga(this)};function Ga(a){if(!a.la)return Promise.resolve();a.ja=Math.max(a.ja,a.c);var b=a.la.select(a.F.width*a.ja,a.ga.getDpr()).url;return b==a.l.getAttribute("src")?Promise.resolve():t(a.win,"timer").promise(1).then(function(){a.l.setAttribute("src",b);return a.Za(a.l)})}
function Fa(a){var b=ya(a.l);b.onGesture(M,function(){a.ga.toggleViewMode()});b.onGesture(P,function(b){var c=b.data.deltaY,e=V(a,a.g+b.data.deltaX,!0),c=W(a,a.f+c,!0);X(a,a.c,e,c,!1);b.data.last&&Ha(a,b.data.velocityX,b.data.velocityY)});b.onPointerDown(function(){a.M&&a.M.halt()});b.onGesture(N,function(b){var c;c=1==a.c?a.ia:a.za;Ia(a,c,a.s.width/2-b.data.clientX,a.s.height/2-b.data.clientY,!0).then(function(){return Ja(a,0,0,0,0,0,0)})});b.onGesture(Q,function(b){Ka(a,b.data.centerClientX,b.data.centerClientY,
b.data.deltaX,b.data.deltaY);b.data.last&&Ja(a,b.data.centerClientX,b.data.centerClientY,b.data.deltaX,b.data.deltaY,b.data.velocityY,b.data.velocityY)})}function Y(a,b,c,d){return Math.max(b-d,Math.min(c+d,a))}function V(a,b,c){return Y(b,a.Aa,a.xa,c&&1<a.c?.25*a.s.width:0)}function W(a,b,c){return Y(b,a.Ba,a.ya,c?.25*a.s.height:0)}
function T(a,b){var c=0,d=0,e=a.s.height-a.F.height*b;0<=e?d=c=0:(d=e/2,c=-d);var f=0,h=0;b=a.s.width-a.F.width*b;0<=b?h=f=0:(h=b/2,f=-h);a.Aa=h;a.Ba=d;a.xa=f;a.ya=c}function U(a){var b=a.l,c;c=a.w;var d=a.u;"number"==typeof c&&(c+="px");void 0===d?c="translate("+c+")":("number"==typeof d&&(d+="px"),c="translate("+c+","+d+")");y(b,{transform:c+" "+("scale("+a.c+")")});1!=a.c&&a.ga.toggleViewMode(!0)}
function Ha(a,b,c){var d=a.u-a.f;1==a.c&&10<Math.abs(d)?a.ga.close():(a.M=Ba(a.l,a.w,a.u,b,c,function(b,c){b=V(a,b,!0);c=W(a,c,!0);if(1>Math.abs(b-a.w)&&1>Math.abs(c-a.u))return!1;X(a,a.c,b,c,!1);return!0}),a.M.thenAlways(function(){a.M=null;return La(a)}))}function Ka(a,b,c,d,e){var f=Math.sqrt(d*d+e*e),h=Math.abs(e)>Math.abs(d)?Math.sign(e):Math.sign(-d);if(0!=h){var k=a.da*(1+h*f/100),m=a.s.width/2-b,v=a.s.height/2-c;d=Math.min(m,f/100*m);e=Math.min(v,f/100*v);Ia(a,k,d,e,!1)}}
function Ia(a,b,c,d,e){b=Y(b,a.za,a.ia,.25);if(b!=a.c)return T(a,b),c=V(a,a.g+c*b,!1),d=W(a,a.f+d*b,!1),X(a,b,c,d,e)}function Ja(a,b,c,d,e,f,h){d=0==f&&0==h?Promise.resolve():Ba(a.l,d,e,f,h,function(d,e){Ka(a,b,c,d,e);return!0}).thenAlways();var k=a.c>a.da;return d.then(function(){return La(a)}).then(function(){k&&Ga(a)})}
function X(a,b,c,d,e){var f=b-a.c,h=c-a.w,k=d-a.u,h=Math.sqrt(h*h+k*k),m=0;if(e)var v=250,m=Math.min(v,Math.max(v*h*.01,v*Math.abs(f)));if(16<m&&e){var Na=H(a.c,b),Oa=H(a.w,c),Pa=H(a.u,d);e=qa(a.l,function(b){a.c=Na(b);a.w=Oa(b);a.u=Pa(b);U(a)},m).thenAlways(function(){a.c=b;a.w=c;a.u=d;U(a)})}else a.c=b,a.w=c,a.u=d,U(a),e=e?Promise.resolve():void 0;return e}
function La(a){var b=Y(a.c,a.za,a.ia,0);b!=a.c&&T(a,b);var c=V(a,a.w/a.c*b,!1),d=W(a,a.u/a.c*b,!1);return X(a,b,c,d,!0).then(function(){a.da=a.c;a.g=a.w;a.f=a.u})}function Z(a){AMP.BaseElement.call(this,a);this.ua=-1;this.$=this.Y=!1;this.J=this.G=this.D=this.ma=this.B=this.Ha=null;this.qa=this.Ua.bind(this)}l(Z,AMP.BaseElement);g=Z.prototype;g.isLayoutSupported=function(a){return"nodisplay"==a};
g.buildCallback=function(){var a=this;this.D=this.element.ownerDocument.createElement("div");this.D.classList.add("-amp-image-lightbox-container");this.element.appendChild(this.D);this.G=new Ea(this,this.win,this.loadPromise.bind(this));this.D.appendChild(this.G.getElement());this.J=this.element.ownerDocument.createElement("div");this.J.setAttribute("id",this.element.getAttribute("id")+"-caption");this.J.classList.add("amp-image-lightbox-caption");this.J.classList.add("-amp-image-lightbox-caption");
this.D.appendChild(this.J);var b=this.element.ownerDocument.createElement("button");b.textContent="Close the lightbox";b.classList.add("-amp-screen-reader");b.tabIndex=-1;b.addEventListener("click",function(){a.close()});this.element.appendChild(b);var c=ya(this.element);this.element.addEventListener("click",function(b){a.$||a.G.getImage().contains(b.target)||a.close()});c.onGesture(M,function(){a.$||a.close()});c.onGesture(P,function(){})};
g.activate=function(a){var b=this;if(!this.Y){var c=a.source;p().assert(c&&Da[c.tagName.toLowerCase()],"Unsupported element: %s",c.tagName);this.Y=!0;Ma(this);Qa(this,c);this.win.document.documentElement.addEventListener("keydown",this.qa);this.getViewport().enterLightboxMode();Ra(this);this.ma=this.getViewport().onChanged(function(){b.Y&&b.G.measure()});ca(this.getAmpDoc()).push(this.close.bind(this)).then(function(a){b.ua=a})}};g.Ua=function(a){27==a.keyCode&&this.close()};
g.close=function(){this.Y&&(this.$=this.Y=!1,Sa(this),this.ma&&(this.ma(),this.ma=null),this.getViewport().leaveLightboxMode(),-1!=this.ua&&ca(this.getAmpDoc()).pop(this.ua),this.win.document.documentElement.removeEventListener("keydown",this.qa),this.qa=null)};g.toggleViewMode=function(a){void 0!==a?this.D.classList.toggle("-amp-image-lightbox-view-mode",a):this.D.classList.toggle("-amp-image-lightbox-view-mode")};
function Qa(a,b){a.Ha=b;a.B=r(b,"img");a.G.init(a.Ha,a.B);var c=null;if(!c){var d=ba(b);d&&(c=r(d,"figcaption"))}if(!c)var e=b.getAttribute("aria-describedby"),c=a.element.ownerDocument.getElementById(e);if(c){var f=c;b=a.J;for(var h=b.ownerDocument.createDocumentFragment(),f=f.firstChild;f;f=f.nextSibling)h.appendChild(f.cloneNode(!0));b.appendChild(h);a.G.getImage().setAttribute("aria-describedby",a.J.getAttribute("id"))}a.J.classList.toggle("-amp-empty",!c)}
function Ma(a){a.G.reset();for(var b=a.J;b.firstChild;)b.removeChild(b.firstChild);a.Ha=null;a.B=null;a.toggleViewMode(!1)}
function Ra(a){a.$=!0;y(a.element,{opacity:0,display:""});a.G.measure();var b=new E(a.element);b.add(0,G(a.element,{opacity:H(0,1)}),.6,R);var c=null;if(a.B&&u(a.B)&&a.B.src){c=a.element.ownerDocument.createElement("div");c.classList.add("-amp-image-lightbox-trans");a.element.ownerDocument.body.appendChild(c);var d=A(a.B.getBoundingClientRect()),e=a.G.getImageBox(),f=a.B.cloneNode(!0);f.className="";y(f,{position:"absolute",top:d.top+"px",left:d.left+"px",width:d.width+"px",height:d.height+"px",transformOrigin:"top left",
willChange:"transform"});c.appendChild(f);a.B.classList.add("-amp-ghost");var h=e.top-d.top,k=0!=d.width?e.width/d.width:1,m=Math.max(.2,Math.min(.8,Math.abs(h)/250*.8));b.add(0,G(f,{transform:ta([ua(H(0,e.left-d.left),H(0,h)),va(H(1,k))])}),m,R);y(a.D,{opacity:0});b.add(.8,G(a.D,{opacity:H(0,1)}),.1,R);b.add(.9,G(c,{opacity:H(1,.01)}),.1,S)}b.start(500).thenAlways(function(){a.$=!1;y(a.element,{opacity:""});y(a.D,{opacity:""});c&&a.element.ownerDocument.body.removeChild(c)})}
function Sa(a){var b=a.G.getImage(),c=a.G.getImageBoxWithOffset(),d=new E(a.element),e=500;d.add(0,G(a.element,{opacity:H(1,0)}),.9,S);var f=null;if(u(b)&&b.src&&a.B){f=a.element.ownerDocument.createElement("div");f.classList.add("-amp-image-lightbox-trans");a.element.ownerDocument.body.appendChild(f);var h=A(a.B.getBoundingClientRect()),k=b.cloneNode(!0);y(k,{position:"absolute",top:c.top+"px",left:c.left+"px",width:c.width+"px",height:c.height+"px",transform:"",transformOrigin:"top left",willChange:"transform"});
f.appendChild(k);d.add(0,G(a.D,{opacity:H(1,0)}),.1,S);var b=h.top-c.top,m=0!=c.width?h.width/c.width:1,v=G(k,{transform:ta([ua(H(0,h.left-c.left),H(0,b)),va(H(1,m))])}),c=Math.max(.2,Math.min(.8,Math.abs(b)/250*.8));d.add(Math.min(.8-c,.2),function(b,c){v(b);c&&a.B.classList.remove("-amp-ghost")},c,S);d.add(.8,G(f,{opacity:H(1,.01)}),.2,S);e=Math.max(Math.min(Math.abs(b)/250*e,e),300)}d.start(e).thenAlways(function(){a.B&&a.B.classList.remove("-amp-ghost");a.collapse();y(a.element,{opacity:""});
y(a.D,{opacity:""});f&&a.element.ownerDocument.body.removeChild(f);Ma(a)})}AMP.registerElement("amp-image-lightbox",Z,"amp-image-lightbox{position:fixed!important;z-index:1000!important;top:0!important;left:0!important;bottom:0!important;right:0!important;margin:0!important;padding:0!important;overflow:hidden!important;-webkit-transform:translateZ(0)!important;transform:translateZ(0)!important;-ms-touch-action:none!important;touch-action:none!important;background:rgba(0,0,0,.95);color:#f2f2f2}.-amp-image-lightbox-container{position:absolute;z-index:0;top:0;left:0;right:0;bottom:0;overflow:hidden;-webkit-transform:translateZ(0);transform:translateZ(0)}.-amp-image-lightbox-trans{pointer-events:none!important;position:fixed;z-index:1001;top:0;left:0;bottom:0;right:0}.-amp-image-lightbox-caption{position:absolute!important;z-index:2!important;bottom:0!important;left:0!important;right:0!important}.-amp-image-lightbox-caption.-amp-empty,.-amp-image-lightbox-view-mode .-amp-image-lightbox-caption{visibility:hidden}.amp-image-lightbox-caption{background:rgba(0,0,0,.5);max-height:25%;padding:8px}.-amp-image-lightbox-viewer{position:absolute;z-index:1;top:0;left:0;right:0;bottom:0;overflow:hidden;-webkit-transform:translateZ(0);transform:translateZ(0)}.-amp-image-lightbox-viewer-image{position:absolute;z-index:1;display:block;-webkit-transform-origin:50% 50%;transform-origin:50% 50%}\n/*# sourceURL=/extensions/amp-image-lightbox/0.1/amp-image-lightbox.css*/");
})});
//# sourceMappingURL=amp-image-lightbox-0.1.js.map

