(self.AMP = self.AMP || []).push({n:"amp-user-notification", f:(function(AMP) {var g;function h(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var f=Object.getOwnPropertyDescriptor(b,d);f&&Object.defineProperty(a,d,f)}else a[d]=b[d]};Date.now();function l(a){for(var b=null,c="",d=0;d<arguments.length;d++){var f=arguments[d];f instanceof Error&&!b?b=f:(c&&(c+=" "),c+=f)}b?c&&(b.message=c+": "+b.message):b=Error(c);return b}function n(a){var b=l.apply(null,arguments);setTimeout(function(){throw b;})}self.log=self.log||{user:null,dev:null};var p=self.log;function q(){if(p.user)return p.user;throw Error("failed to call initLogConstructor");};function r(a,b,c){if(b(a))c();else{var d=a.ownerDocument.defaultView;if(d.MutationObserver){var f=new d.MutationObserver(function(){b(a)&&(f.disconnect(),c())});f.observe(a,{childList:!0})}else var e=d.setInterval(function(){b(a)&&(d.clearInterval(e),c())},5)}}function t(a,b){r(a.documentElement,function(){return!!a.body},b)}function u(a){return new Promise(function(b){t(a,b)})};function v(a){a=a.__AMP_TOP||a;var b=a.services&&a.services.xhr&&a.services.xhr.obj;return b}function x(a,b){var c=y(a);return c&&c.services&&c.services[b]&&c.services[b].obj}function z(a){if(a.nodeType){var b=(a.ownerDocument||a).defaultView;if(b=b!=(b.__AMP_TOP||b)&&b.services&&b.services["url-replace"]&&b.services["url-replace"].obj?b.services["url-replace"].obj:null)return b}return x(a,"url-replace")}function A(a){var b=B;a=a.__AMP_TOP||a;return C(a,a,"userNotificationManager",b)}
function y(a){if(a.nodeType){var b=(a.ownerDocument||a).defaultView,b=b.__AMP_TOP||b;a=C(b,b,"ampdoc").getAmpDoc(a)}return a.isSingleDoc()?a.win:a}function C(a,b,c,d){var f=D(a),e=f[c];e||(e=f[c]={obj:null,promise:null,resolve:null});e.obj||(e.obj=d?new d(b):(void 0)(b),e.resolve&&e.resolve(e.obj));return e.obj}function E(a,b){var c=F(a,b);if(c)return c;a=D(a);var d,f=new Promise(function(a){d=a});a[b]={obj:null,promise:f,resolve:d};return f}
function F(a,b){if(a=D(a)[b]){if(b=a.promise)return b;if(a.obj)return a.promise=Promise.resolve(a.obj)}return null}function D(a){var b=a.services;b||(b=a.services={});return b};function G(a){var b="amp-analytics";return H(a,b).then(function(a){return q().assert(a,"Service %s was requested to be provided through %s, but %s is not loaded in the current page. To fix this problem load the JavaScript file for %s in this page.","cid",b,b,b)})}
function H(a,b){var c=F(a,"cid");return c?c:Promise.resolve().then(function(){return a.ampExtendedElements&&a.ampExtendedElements[b]?E(a,"cid"):u(a.document).then(function(){return a.ampExtendedElements&&a.ampExtendedElements[b]?E(a,"cid"):null})})};var I,J;
function K(a){if("string"==typeof a){I||(I=self.document.createElement("a"),J=self.UrlCache||(self.UrlCache=Object.create(null)));var b=J[a];if(b)a=b;else{I.href=a;I.protocol||(I.href=I.href);b={href:I.href,protocol:I.protocol,host:I.host,hostname:I.hostname,port:"0"==I.port?"":I.port,pathname:I.pathname,search:I.search,hash:I.hash,origin:null};"/"!==b.pathname[0]&&(b.pathname="/"+b.pathname);if("http:"==b.protocol&&80==b.port||"https:"==b.protocol&&443==b.port)b.port="",b.host=b.hostname;b.origin=
I.origin&&"null"!=I.origin?I.origin:"data:"!=b.protocol&&b.host?b.protocol+"//"+b.host:b.href;a=J[a]=b}}(b="https:"==a.protocol||"localhost"==a.hostname)||(a=a.hostname,b=a.length-10,b=0<=b&&a.indexOf(".localhost",b)==b);return b}function L(a,b){var c;c=void 0===c?"source":c;q().assert(null!=a,"%s %s must be available",b,c);var d=a;q().assert(K(d)||/^(\/\/)/.test(d),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,d)};var M,N="Webkit webkit Moz moz ms O o".split(" ");function O(a){return"loading"!=a.readyState&&"uninitialized"!=a.readyState}function P(a,b){var c=O,d=c(a);if(d)b(a);else{var f=function(){c(a)&&(d||(d=!0,b(a)),a.removeEventListener("readystatechange",f))};a.addEventListener("readystatechange",f)}}function Q(a){return new Promise(function(b){P(a,b)})};function R(a){AMP.BaseElement.call(this,a);this.h=this.i=this.A=null}h(R,AMP.BaseElement);g=R.prototype;g.isAlwaysFixed=function(){return!0};
g.buildCallback=function(){var a=this,b=this.getAmpDoc();this.A=z(b);this.h=E(y(b),"storage");this.i||(this.i=A(this.win));this.g=this.j=null;this.l=new Promise(function(b){a.g=b});this.b=q().assert(this.element.id,"amp-user-notification should have an id.");this.w="amp-user-notification:"+this.b;(this.c=this.element.getAttribute("data-show-if-href"))&&L(this.c,this.element);(this.a=this.element.getAttribute("data-dismiss-href"))&&L(this.a,this.element);var c=this.element.getAttribute("role");c||
this.element.setAttribute("role","alert");var d=this.element.getAttribute("data-persist-dismissal");this.u="false"!=d&&"no"!=d;this.i.registerUserNotification(this.b,this);this.registerAction("dismiss",this.dismiss.bind(this))};
function S(a,b){var c=a.c;return a.A.expandAsync(c).then(function(c){var d;d={elementId:a.b,ampUserId:b};var e=[],k;for(k in d){var m=d[k];if(null!=m)if(Array.isArray(m))for(var w=0;w<m.length;w++){var U=m[w];e.push(encodeURIComponent(k)+"="+encodeURIComponent(U))}else e.push(encodeURIComponent(k)+"="+encodeURIComponent(m))}d=e.join("&");e=c;d?(e=e.split("#",2),k=e[0].split("?",2),d=k[0]+(k[1]?"?"+k[1]+"&"+d:"?"+d),d+=e[1]?"#"+e[1]:""):d=e;return d})}
g.B=function(a){var b=this;this.j=a;return S(this,a).then(function(a){var c={credentials:"include"};return v(b.win).fetchJson(a,c)})};g.C=function(a){q().assert("boolean"==typeof a.showNotification,'`showNotification` should be a boolean. Got "%s" which is of type %s.',a.showNotification,typeof a.showNotification);a.showNotification||this.g();return Promise.resolve(a.showNotification)};
function T(a){return G(a.win).then(function(b){return b.get({scope:"amp-user-notification",createCookieIfNotPresent:!0},Promise.resolve(),a.l)})}g.shouldShow=function(){var a=this;return this.isDismissed().then(function(b){return b?!1:a.c?T(a).then(a.B.bind(a)).then(a.C.bind(a)):!0})};
g.show=function(){var a=this.element,b=a.style;M||(M=Object.create(null));var c=M.display;if(!c){c="display";if(void 0===b.display){var d="D"+"display".slice(1);a:{for(var f=0;f<N.length;f++){var e=N[f]+d;if(void 0!==b[e]){d=e;break a}}d=""}void 0!==b[d]&&(c=d)}M.display=c}(b=c)&&(a.style[b]="");this.element.classList.add("amp-active");this.getViewport().addToFixedLayer(this.element);return this.l};
g.isDismissed=function(){var a=this;return this.u?this.h.then(function(b){return b.get(a.w)}).then(function(a){return!!a},function(a){var b;if(p.dev)b=p.dev;else throw Error("failed to call initLogConstructor");b.error("amp-user-notification","Failed to read storage",a);return!1}):Promise.resolve(!1)};g.activate=function(){this.dismiss()};
g.dismiss=function(){var a=this;this.element.classList.remove("amp-active");this.element.classList.add("amp-hidden");this.g();this.getViewport().removeFromFixedLayer(this.element);this.u&&this.h.then(function(b){b.set(a.w,!0)});this.a&&v(this.win).fetchJson(this.a,{method:"POST",credentials:"include",body:{elementId:this.b,ampUserId:this.j}})};
function B(a){this.win=a;this.v=Object.create(null);this.f=Object.create(null);this.D=x(this.win.document,"viewer");this.m=Q(this.win.document);this.s=this.o=Promise.all([this.D.whenFirstVisible(),this.m])}B.prototype.get=function(a){var b=this;this.o.then(function(){null==b.win.document.getElementById(a)&&q().warn("amp-user-notification","Did not find amp-user-notification element "+a+".")});return V(this,a).promise};B.prototype.getNotification=function(a){var b=this;return this.m.then(function(){return b.v[a]})};
B.prototype.registerUserNotification=function(a,b){this.v[a]=b;var c=V(this,a);return this.s=this.s.then(function(){return b.shouldShow().then(function(a){if(a)return b.show()})}).then(c.resolve.bind(this,b)).catch(n.bind(null,"Notification service failed amp-user-notification",a))};function V(a,b){if(a.f[b])return a.f[b];var c,d=new Promise(function(a){c=a});return a.f[b]={promise:d,resolve:c}}(function(a){return A(a)})(AMP.win);AMP.registerElement("amp-user-notification",R,"amp-user-notification{position:fixed!important;bottom:0;left:0;overflow:hidden!important;visibility:hidden;background:hsla(0,0%,100%,.7);z-index:1000;width:100%}amp-user-notification.amp-active{visibility:visible}amp-user-notification.amp-hidden{visibility:hidden}\n/*# sourceURL=/extensions/amp-user-notification/0.1/amp-user-notification.css*/");
})});
//# sourceMappingURL=amp-user-notification-0.1.js.map

