(self.AMP = self.AMP || []).push({n:"amp-mustache", f:(function(AMP) {function aa(b,a){function e(){}e.prototype=a.prototype;b.prototype=new e;b.prototype.constructor=b;for(var c in a)if(Object.defineProperties){var f=Object.getOwnPropertyDescriptor(a,c);f&&Object.defineProperty(b,c,f)}else b[c]=a[c]};Date.now();self.log=self.log||{user:null,dev:null};var ba=self.log;function v(){if(ba.user)return ba.user;throw Error("failed to call initLogConstructor");};var ca=(self.AMP_CONFIG||{}).cdnUrl||"https://cdn.ampproject.org",da=/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org/;var z,ea,fa=/[?&]amp_js[^&]*/;
function G(b){var a;z||(z=self.document.createElement("a"),ea=self.UrlCache||(self.UrlCache=Object.create(null)));var e=ea[b];if(e)return e;z.href=b;z.protocol||(z.href=z.href);var c={href:z.href,protocol:z.protocol,host:z.host,hostname:z.hostname,port:"0"==z.port?"":z.port,pathname:z.pathname,search:z.search,hash:z.hash,origin:null};"/"!==c.pathname[0]&&(c.pathname="/"+c.pathname);if("http:"==c.protocol&&80==c.port||"https:"==c.protocol&&443==c.port)c.port="",c.host=c.hostname;c.origin=z.origin&&
"null"!=z.origin?z.origin:"data:"!=c.protocol&&c.host?c.protocol+"//"+c.host:c.href;var f=c;return a?f:ea[b]=f}function ja(b){"string"==typeof b&&(b=G(b));return da.test(b.origin)}function ka(b,a){"string"==typeof a&&(a=G(a));return"function"==typeof URL?(new URL(b,a.href)).toString():ta(b,a)}
function ta(b,a){"string"==typeof a&&(a=G(a));b=b.replace(/\\/g,"/");var e=G(b);if(0==b.toLowerCase().indexOf(e.protocol))return e.href;if(0==b.indexOf("//"))return a.protocol+b;if(0==b.indexOf("/"))return a.origin+b;var c=a.pathname.split("/");return a.origin+(1<c.length?c.slice(0,c.length-1).join("/"):"")+"/"+b};function L(b){v().assert(0<b.length,"Srcset must have at least one source");this.f=b;var a=!1,e=!1;for(b=0;b<this.f.length;b++){var c=this.f[b];v().assert((c.width||c.dpr)&&(!c.width||!c.dpr),"Either dpr or width must be specified");a=a||!!c.width;e=e||!!c.dpr}v().assert(!a||!e,"Srcset cannot have both width and dpr sources");a?this.f.sort(ua):this.f.sort(va);this.C=a;this.B=e}
L.prototype.select=function(b,a){var e=-1;if(this.C)for(var e=-1,c=1E6,f=1E6,l=0;l<this.f.length;l++){var h=this.f[l],h=h.width?h.width/a:c/2,c=Math.min(c,h),h=Math.abs((h-b)/b-.2);h<f&&(f=h,e=l)}else if(this.B){b=-1;e=1E6;for(c=0;c<this.f.length;c++)f=Math.abs((this.f[c].dpr||1)-a),f<e&&(e=f,b=c);e=b}return-1!=e?this.f[e]:this.getLast()};L.prototype.getLast=function(){return this.f[this.f.length-1]};L.prototype.getSources=function(){return this.f};
L.prototype.stringify=function(){for(var b=[],a=0;a<this.f.length;a++){var e=this.f[a];e.width?b.push(e.url+" "+e.width+"w"):e.dpr?b.push(e.url+" "+e.dpr+"x"):b.push(""+e.url)}return b.join(", ")};function ua(b,a){v().assert(b.width!=a.width,"Duplicate width: %s",b.width);return a.width-b.width}function va(b,a){v().assert(b.dpr!=a.dpr,"Duplicate dpr: %s",b.dpr);return a.dpr-b.dpr};var wa=function(){function b(b){var g=(""+b).match(t);return g?new d(w(g[1]),w(g[2]),w(g[3]),w(g[4]),w(g[5]),w(g[6]),w(g[7])):null}function a(g,b,a,h,l,u,r){g=new d(c(g,q),c(b,q),e(a),0<h?h.toString():null,c(l,C),null,e(r));u&&("string"===typeof u?g.setRawQuery(u.replace(/[^?&=0-9A-Za-z_\-~.%]/g,f)):g.setAllParameters(u));return g}function e(g){return"string"==typeof g?encodeURIComponent(g):null}function c(g,b){return"string"==typeof g?encodeURI(g).replace(b,f):null}function f(b){var g=b.charCodeAt(0);
return"%"+"0123456789ABCDEF".charAt(g>>4&15)+"0123456789ABCDEF".charAt(g&15)}function l(b){return b.replace(/(^|\/)\.(?:\/|$)/g,"$1").replace(/\/{2,}/g,"/")}function h(b){if(null===b)return null;b=l(b);for(var g=I,a;(a=b.replace(g,"$1"))!=b;b=a);return b}function u(b,a){var g=b.clone(),d=a.hasScheme();d?g.setRawScheme(a.getRawScheme()):d=a.hasCredentials();d?g.setRawCredentials(a.getRawCredentials()):d=a.hasDomain();d?g.setRawDomain(a.getRawDomain()):d=a.hasPort();var e=a.getRawPath(),c=h(e);if(d)g.setPort(a.getPort()),
c=c&&c.replace(r,"");else if(d=!!e){if(47!==c.charCodeAt(0))var f=h(g.getRawPath()||"").replace(r,""),H=f.lastIndexOf("/")+1,c=h((H?f.substring(0,H):"")+h(e)).replace(r,"")}else c=c&&c.replace(r,""),c!==e&&g.setRawPath(c);d?g.setRawPath(c):d=a.hasQuery();d?g.setRawQuery(a.getRawQuery()):d=a.hasFragment();d&&g.setRawFragment(a.getRawFragment());return g}function d(b,a,d,e,c,h,f){this.o=b;this.j=a;this.l=d;this.v=e;this.h=c;this.g=h;this.m=f;this.c=null}function w(b){return"string"==typeof b&&0<b.length?
b:null}var M=/(\/|^)(?:[^./][^/]*|\.{2,}(?:[^./][^/]*)|\.{3,}[^/]*)\/\.\.(?:\/|$)/,I=new RegExp(M),r=/^(?:\.\.\/)*(?:\.\.$)?/;d.prototype.toString=function(){var b=[];null!==this.o&&b.push(this.o,":");null!==this.l&&(b.push("//"),null!==this.j&&b.push(this.j,"@"),b.push(this.l),null!==this.v&&b.push(":",this.v.toString()));null!==this.h&&b.push(this.h);null!==this.g&&b.push("?",this.g);null!==this.m&&b.push("#",this.m);return b.join("")};d.prototype.clone=function(){return new d(this.o,this.j,this.l,
this.v,this.h,this.g,this.m)};d.prototype.getScheme=function(){return this.o&&decodeURIComponent(this.o).toLowerCase()};d.prototype.getRawScheme=function(){return this.o};d.prototype.setScheme=function(b){this.o=c(b,q);return this};d.prototype.setRawScheme=function(b){this.o=b?b:null;return this};d.prototype.hasScheme=function(){return null!==this.o};d.prototype.getCredentials=function(){return this.j&&decodeURIComponent(this.j)};d.prototype.getRawCredentials=function(){return this.j};d.prototype.setCredentials=
function(b){this.j=c(b,q);return this};d.prototype.setRawCredentials=function(b){this.j=b?b:null;return this};d.prototype.hasCredentials=function(){return null!==this.j};d.prototype.getDomain=function(){return this.l&&decodeURIComponent(this.l)};d.prototype.getRawDomain=function(){return this.l};d.prototype.setDomain=function(b){return this.setRawDomain(b&&encodeURIComponent(b))};d.prototype.setRawDomain=function(b){this.l=b?b:null;return this.setRawPath(this.h)};d.prototype.hasDomain=function(){return null!==
this.l};d.prototype.getPort=function(){return this.v&&decodeURIComponent(this.v)};d.prototype.setPort=function(b){if(b){b=Number(b);if(b!==(b&65535))throw Error("Bad port number "+b);this.v=""+b}else this.v=null;return this};d.prototype.hasPort=function(){return null!==this.v};d.prototype.getPath=function(){return this.h&&decodeURIComponent(this.h)};d.prototype.getRawPath=function(){return this.h};d.prototype.setPath=function(b){return this.setRawPath(c(b,C))};d.prototype.setRawPath=function(b){b?
(b=String(b),this.h=!this.l||/^\//.test(b)?b:"/"+b):this.h=null;return this};d.prototype.hasPath=function(){return null!==this.h};d.prototype.getQuery=function(){return this.g&&decodeURIComponent(this.g).replace(/\+/g," ")};d.prototype.getRawQuery=function(){return this.g};d.prototype.setQuery=function(b){this.c=null;this.g=e(b);return this};d.prototype.setRawQuery=function(b){this.c=null;this.g=b?b:null;return this};d.prototype.hasQuery=function(){return null!==this.g};d.prototype.setAllParameters=
function(b){if("object"===typeof b&&!(b instanceof Array)&&(b instanceof Object||"[object Array]"!==Object.prototype.toString.call(b))){var a=[],d=-1,g;for(g in b){var e=b[g];"string"===typeof e&&(a[++d]=g,a[++d]=e)}b=a}this.c=null;for(var c=[],h="",f=0;f<b.length;)g=b[f++],e=b[f++],c.push(h,encodeURIComponent(g.toString())),h="&",e&&c.push("=",encodeURIComponent(e.toString()));this.g=c.join("");return this};d.prototype.w=function(){if(!this.c){var b=this.g;if(b){for(var a=b.split(/[&\?]/),b=[],d=
-1,e=0;e<a.length;++e){var c=a[e].match(/^([^=]*)(?:=(.*))?$/);b[++d]=decodeURIComponent(c[1]).replace(/\+/g," ");b[++d]=decodeURIComponent(c[2]||"").replace(/\+/g," ")}this.c=b}else this.c=[]}};d.prototype.setParameterValues=function(b,a){"string"===typeof a&&(a=[a]);this.w();for(var d=0,e=this.c,c=[],g=0;g<e.length;g+=2)b===e[g]?d<a.length&&c.push(b,a[d++]):c.push(e[g],e[g+1]);for(;d<a.length;)c.push(b,a[d++]);this.setAllParameters(c);return this};d.prototype.removeParameter=function(b){return this.setParameterValues(b,
[])};d.prototype.getAllParameters=function(){this.w();return this.c.slice(0,this.c.length)};d.prototype.getParameterValues=function(b){this.w();for(var a=[],d=0;d<this.c.length;d+=2)b===this.c[d]&&a.push(this.c[d+1]);return a};d.prototype.getParameterMap=function(){this.w();for(var b={},a=0;a<this.c.length;a+=2){var d=this.c[a++],e=this.c[a++];d in b?b[d].push(e):b[d]=[e]}return b};d.prototype.getParameterValue=function(b){this.w();for(var a=0;a<this.c.length;a+=2)if(b===this.c[a])return this.c[a+
1];return null};d.prototype.getFragment=function(){return this.m&&decodeURIComponent(this.m)};d.prototype.getRawFragment=function(){return this.m};d.prototype.setFragment=function(b){this.m=b?encodeURIComponent(b):null;return this};d.prototype.setRawFragment=function(b){this.m=b?b:null;return this};d.prototype.hasFragment=function(){return null!==this.m};var t=/^(?:([^:/?#]+):)?(?:\/\/(?:([^/?#]*)@)?([^/?#:@]*)(?::([0-9]+))?)?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,q=/[#\/\?@]/g,C=/[\#\?]/g;d.parse=b;
d.create=a;d.resolve=u;d.collapse_dots=h;d.utils={mimeTypeOf:function(a){var d=b(a);return/\.html$/.test(d.getPath())?"text/html":"application/javascript"},resolve:function(a,d){return a?u(b(a),b(d)).toString():""+d}};return d}(),R={atype:{NONE:0,URI:1,URI_FRAGMENT:11,SCRIPT:2,STYLE:3,HTML:12,ID:4,IDREF:5,IDREFS:6,GLOBAL_NAME:7,LOCAL_NAME:8,CLASSES:9,FRAME_TARGET:10,MEDIA_QUERY:13}};R.atype=R.atype;
R.ATTRIBS={"*::class":9,"*::dir":0,"*::draggable":0,"*::hidden":0,"*::id":4,"*::inert":0,"*::itemprop":0,"*::itemref":6,"*::itemscope":0,"*::lang":0,"*::onblur":2,"*::onchange":2,"*::onclick":2,"*::ondblclick":2,"*::onerror":2,"*::onfocus":2,"*::onkeydown":2,"*::onkeypress":2,"*::onkeyup":2,"*::onload":2,"*::onmousedown":2,"*::onmousemove":2,"*::onmouseout":2,"*::onmouseover":2,"*::onmouseup":2,"*::onreset":2,"*::onscroll":2,"*::onselect":2,"*::onsubmit":2,"*::ontouchcancel":2,"*::ontouchend":2,"*::ontouchenter":2,
"*::ontouchleave":2,"*::ontouchmove":2,"*::ontouchstart":2,"*::onunload":2,"*::spellcheck":0,"*::style":3,"*::tabindex":0,"*::title":0,"*::translate":0,"a::accesskey":0,"a::coords":0,"a::href":1,"a::hreflang":0,"a::name":7,"a::onblur":2,"a::onfocus":2,"a::shape":0,"a::target":10,"a::type":0,"area::accesskey":0,"area::alt":0,"area::coords":0,"area::href":1,"area::nohref":0,"area::onblur":2,"area::onfocus":2,"area::shape":0,"area::target":10,"audio::controls":0,"audio::loop":0,"audio::mediagroup":5,
"audio::muted":0,"audio::preload":0,"audio::src":1,"bdo::dir":0,"blockquote::cite":1,"br::clear":0,"button::accesskey":0,"button::disabled":0,"button::name":8,"button::onblur":2,"button::onfocus":2,"button::type":0,"button::value":0,"canvas::height":0,"canvas::width":0,"caption::align":0,"col::align":0,"col::char":0,"col::charoff":0,"col::span":0,"col::valign":0,"col::width":0,"colgroup::align":0,"colgroup::char":0,"colgroup::charoff":0,"colgroup::span":0,"colgroup::valign":0,"colgroup::width":0,
"command::checked":0,"command::command":5,"command::disabled":0,"command::icon":1,"command::label":0,"command::radiogroup":0,"command::type":0,"data::value":0,"del::cite":1,"del::datetime":0,"details::open":0,"dir::compact":0,"div::align":0,"dl::compact":0,"fieldset::disabled":0,"font::color":0,"font::face":0,"font::size":0,"form::accept":0,"form::action":1,"form::autocomplete":0,"form::enctype":0,"form::method":0,"form::name":7,"form::novalidate":0,"form::onreset":2,"form::onsubmit":2,"form::target":10,
"h1::align":0,"h2::align":0,"h3::align":0,"h4::align":0,"h5::align":0,"h6::align":0,"hr::align":0,"hr::noshade":0,"hr::size":0,"hr::width":0,"iframe::align":0,"iframe::frameborder":0,"iframe::height":0,"iframe::marginheight":0,"iframe::marginwidth":0,"iframe::width":0,"img::align":0,"img::alt":0,"img::border":0,"img::height":0,"img::hspace":0,"img::ismap":0,"img::name":7,"img::src":1,"img::usemap":11,"img::vspace":0,"img::width":0,"input::accept":0,"input::accesskey":0,"input::align":0,"input::alt":0,
"input::autocomplete":0,"input::checked":0,"input::disabled":0,"input::inputmode":0,"input::ismap":0,"input::list":5,"input::max":0,"input::maxlength":0,"input::min":0,"input::multiple":0,"input::name":8,"input::onblur":2,"input::onchange":2,"input::onfocus":2,"input::onselect":2,"input::pattern":0,"input::placeholder":0,"input::readonly":0,"input::required":0,"input::size":0,"input::src":1,"input::step":0,"input::type":0,"input::usemap":11,"input::value":0,"ins::cite":1,"ins::datetime":0,"label::accesskey":0,
"label::for":5,"label::onblur":2,"label::onfocus":2,"legend::accesskey":0,"legend::align":0,"li::type":0,"li::value":0,"map::name":7,"menu::compact":0,"menu::label":0,"menu::type":0,"meter::high":0,"meter::low":0,"meter::max":0,"meter::min":0,"meter::optimum":0,"meter::value":0,"ol::compact":0,"ol::reversed":0,"ol::start":0,"ol::type":0,"optgroup::disabled":0,"optgroup::label":0,"option::disabled":0,"option::label":0,"option::selected":0,"option::value":0,"output::for":6,"output::name":8,"p::align":0,
"pre::width":0,"progress::max":0,"progress::min":0,"progress::value":0,"q::cite":1,"select::autocomplete":0,"select::disabled":0,"select::multiple":0,"select::name":8,"select::onblur":2,"select::onchange":2,"select::onfocus":2,"select::required":0,"select::size":0,"source::type":0,"table::align":0,"table::bgcolor":0,"table::border":0,"table::cellpadding":0,"table::cellspacing":0,"table::frame":0,"table::rules":0,"table::summary":0,"table::width":0,"tbody::align":0,"tbody::char":0,"tbody::charoff":0,
"tbody::valign":0,"td::abbr":0,"td::align":0,"td::axis":0,"td::bgcolor":0,"td::char":0,"td::charoff":0,"td::colspan":0,"td::headers":6,"td::height":0,"td::nowrap":0,"td::rowspan":0,"td::scope":0,"td::valign":0,"td::width":0,"textarea::accesskey":0,"textarea::autocomplete":0,"textarea::cols":0,"textarea::disabled":0,"textarea::inputmode":0,"textarea::name":8,"textarea::onblur":2,"textarea::onchange":2,"textarea::onfocus":2,"textarea::onselect":2,"textarea::placeholder":0,"textarea::readonly":0,"textarea::required":0,
"textarea::rows":0,"textarea::wrap":0,"tfoot::align":0,"tfoot::char":0,"tfoot::charoff":0,"tfoot::valign":0,"th::abbr":0,"th::align":0,"th::axis":0,"th::bgcolor":0,"th::char":0,"th::charoff":0,"th::colspan":0,"th::headers":6,"th::height":0,"th::nowrap":0,"th::rowspan":0,"th::scope":0,"th::valign":0,"th::width":0,"thead::align":0,"thead::char":0,"thead::charoff":0,"thead::valign":0,"tr::align":0,"tr::bgcolor":0,"tr::char":0,"tr::charoff":0,"tr::valign":0,"track::default":0,"track::kind":0,"track::label":0,
"track::srclang":0,"ul::compact":0,"ul::type":0,"video::controls":0,"video::height":0,"video::loop":0,"video::mediagroup":5,"video::muted":0,"video::poster":1,"video::preload":0,"video::src":1,"video::width":0};R.ATTRIBS=R.ATTRIBS;R.eflags={OPTIONAL_ENDTAG:1,EMPTY:2,CDATA:4,RCDATA:8,UNSAFE:16,FOLDABLE:32,SCRIPT:64,STYLE:128,VIRTUALIZED:256};R.eflags=R.eflags;
R.ELEMENTS={a:0,abbr:0,acronym:0,address:0,applet:272,area:2,article:0,aside:0,audio:0,b:0,base:274,basefont:274,bdi:0,bdo:0,big:0,blockquote:0,body:305,br:2,button:0,canvas:0,caption:0,center:0,cite:0,code:0,col:2,colgroup:1,command:2,data:0,datalist:0,dd:1,del:0,details:0,dfn:0,dialog:272,dir:0,div:0,dl:0,dt:1,em:0,fieldset:0,figcaption:0,figure:0,font:0,footer:0,form:0,frame:274,frameset:272,h1:0,h2:0,h3:0,h4:0,h5:0,h6:0,head:305,header:0,hgroup:0,hr:2,html:305,i:0,iframe:4,img:2,input:2,ins:0,
isindex:274,kbd:0,keygen:274,label:0,legend:0,li:1,link:274,map:0,mark:0,menu:0,meta:274,meter:0,nav:0,nobr:0,noembed:276,noframes:276,noscript:276,object:272,ol:0,optgroup:0,option:1,output:0,p:1,param:274,pre:0,progress:0,q:0,s:0,samp:0,script:84,section:0,select:0,small:0,source:2,span:0,strike:0,strong:0,style:148,sub:0,summary:0,sup:0,table:0,tbody:1,td:1,textarea:8,tfoot:1,th:1,thead:1,time:0,title:280,tr:1,track:2,tt:0,u:0,ul:0,"var":0,video:0,wbr:2};R.ELEMENTS=R.ELEMENTS;
R.ELEMENT_DOM_INTERFACES={a:"HTMLAnchorElement",abbr:"HTMLElement",acronym:"HTMLElement",address:"HTMLElement",applet:"HTMLAppletElement",area:"HTMLAreaElement",article:"HTMLElement",aside:"HTMLElement",audio:"HTMLAudioElement",b:"HTMLElement",base:"HTMLBaseElement",basefont:"HTMLBaseFontElement",bdi:"HTMLElement",bdo:"HTMLElement",big:"HTMLElement",blockquote:"HTMLQuoteElement",body:"HTMLBodyElement",br:"HTMLBRElement",button:"HTMLButtonElement",canvas:"HTMLCanvasElement",caption:"HTMLTableCaptionElement",
center:"HTMLElement",cite:"HTMLElement",code:"HTMLElement",col:"HTMLTableColElement",colgroup:"HTMLTableColElement",command:"HTMLCommandElement",data:"HTMLElement",datalist:"HTMLDataListElement",dd:"HTMLElement",del:"HTMLModElement",details:"HTMLDetailsElement",dfn:"HTMLElement",dialog:"HTMLDialogElement",dir:"HTMLDirectoryElement",div:"HTMLDivElement",dl:"HTMLDListElement",dt:"HTMLElement",em:"HTMLElement",fieldset:"HTMLFieldSetElement",figcaption:"HTMLElement",figure:"HTMLElement",font:"HTMLFontElement",
footer:"HTMLElement",form:"HTMLFormElement",frame:"HTMLFrameElement",frameset:"HTMLFrameSetElement",h1:"HTMLHeadingElement",h2:"HTMLHeadingElement",h3:"HTMLHeadingElement",h4:"HTMLHeadingElement",h5:"HTMLHeadingElement",h6:"HTMLHeadingElement",head:"HTMLHeadElement",header:"HTMLElement",hgroup:"HTMLElement",hr:"HTMLHRElement",html:"HTMLHtmlElement",i:"HTMLElement",iframe:"HTMLIFrameElement",img:"HTMLImageElement",input:"HTMLInputElement",ins:"HTMLModElement",isindex:"HTMLUnknownElement",kbd:"HTMLElement",
keygen:"HTMLKeygenElement",label:"HTMLLabelElement",legend:"HTMLLegendElement",li:"HTMLLIElement",link:"HTMLLinkElement",map:"HTMLMapElement",mark:"HTMLElement",menu:"HTMLMenuElement",meta:"HTMLMetaElement",meter:"HTMLMeterElement",nav:"HTMLElement",nobr:"HTMLElement",noembed:"HTMLElement",noframes:"HTMLElement",noscript:"HTMLElement",object:"HTMLObjectElement",ol:"HTMLOListElement",optgroup:"HTMLOptGroupElement",option:"HTMLOptionElement",output:"HTMLOutputElement",p:"HTMLParagraphElement",param:"HTMLParamElement",
pre:"HTMLPreElement",progress:"HTMLProgressElement",q:"HTMLQuoteElement",s:"HTMLElement",samp:"HTMLElement",script:"HTMLScriptElement",section:"HTMLElement",select:"HTMLSelectElement",small:"HTMLElement",source:"HTMLSourceElement",span:"HTMLSpanElement",strike:"HTMLElement",strong:"HTMLElement",style:"HTMLStyleElement",sub:"HTMLElement",summary:"HTMLElement",sup:"HTMLElement",table:"HTMLTableElement",tbody:"HTMLTableSectionElement",td:"HTMLTableDataCellElement",textarea:"HTMLTextAreaElement",tfoot:"HTMLTableSectionElement",
th:"HTMLTableHeaderCellElement",thead:"HTMLTableSectionElement",time:"HTMLTimeElement",title:"HTMLTitleElement",tr:"HTMLTableRowElement",track:"HTMLTrackElement",tt:"HTMLElement",u:"HTMLElement",ul:"HTMLUListElement","var":"HTMLElement",video:"HTMLVideoElement",wbr:"HTMLElement"};R.ELEMENT_DOM_INTERFACES=R.ELEMENT_DOM_INTERFACES;R.ueffects={NOT_LOADED:0,SAME_DOCUMENT:1,NEW_DOCUMENT:2};R.ueffects=R.ueffects;
R.URIEFFECTS={"a::href":2,"area::href":2,"audio::src":1,"blockquote::cite":0,"command::icon":1,"del::cite":0,"form::action":2,"img::src":1,"input::src":1,"ins::cite":0,"q::cite":0,"video::poster":1,"video::src":1};R.URIEFFECTS=R.URIEFFECTS;R.ltypes={UNSANDBOXED:2,SANDBOXED:1,DATA:0};R.ltypes=R.ltypes;
R.LOADERTYPES={"a::href":2,"area::href":2,"audio::src":2,"blockquote::cite":2,"command::icon":1,"del::cite":2,"form::action":2,"img::src":1,"input::src":1,"ins::cite":2,"q::cite":2,"video::poster":1,"video::src":2};R.LOADERTYPES=R.LOADERTYPES;
var xa=function(b){function a(b){if(W.hasOwnProperty(b))return W[b];var a=b.match(ma);return a?String.fromCharCode(parseInt(a[1],10)):(a=b.match(na))?String.fromCharCode(parseInt(a[1],16)):J&&oa.test(b)?(J.innerHTML="&"+b+";",a=J.textContent,W[b]=a):"&"+b+";"}function e(b,d){return a(d)}function c(b){return b.replace(O,"")}function f(b){return b.replace(N,e)}function l(b){return(""+b).replace(k,"&amp;").replace(E,"&lt;").replace(F,"&gt;").replace(P,"&#34;")}function h(b){return b.replace(n,"&amp;$1").replace(E,
"&lt;").replace(F,"&gt;")}function u(b){var a={cdata:b.cdata||b.cdata,comment:b.comment||b.comment,endDoc:b.endDoc||b.endDoc,endTag:b.endTag||b.endTag,pcdata:b.pcdata||b.pcdata,rcdata:b.rcdata||b.rcdata,startDoc:b.startDoc||b.startDoc,startTag:b.startTag||b.startTag};return function(b,d){var A=a,p=M(b);w(A,p,0,{noMoreGT:!1,noMoreEndComments:!1},d)}}function d(b,a,d,e,m){return function(){w(b,a,d,e,m)}}function w(a,p,e,c,m){try{a.startDoc&&0==e&&a.startDoc(m);for(var A,x,h,f=e,g=p.length;f<g;){var pa=
p[f++],k=p[f];switch(pa){case "&":T.test(k)?(a.pcdata&&a.pcdata("&"+k,m,B,d(a,p,f,c,m)),f++):a.pcdata&&a.pcdata("&amp;",m,B,d(a,p,f,c,m));break;case "</":(A=/^([-\w:]+)[^\'\"]*/.exec(k))?A[0].length===k.length&&">"===p[f+1]?(f+=2,h=A[1].toLowerCase(),a.endTag&&a.endTag(h,m,B,d(a,p,f,c,m))):f=I(p,f,a,m,B,c):a.pcdata&&a.pcdata("&lt;/",m,B,d(a,p,f,c,m));break;case "<":if(A=/^([-\w:]+)\s*\/?/.exec(k))if(A[0].length===k.length&&">"===p[f+1]){f+=2;h=A[1].toLowerCase();a.startTag&&a.startTag(h,[],m,B,d(a,
p,f,c,m));var n=b.ELEMENTS[h];n&qa&&(f=t(p,{name:h,next:f,eflags:n},a,m,B,c))}else f=r(p,f,a,m,B,c);else a.pcdata&&a.pcdata("&lt;",m,B,d(a,p,f,c,m));break;case "\x3c!--":if(!c.noMoreEndComments){for(x=f+1;x<g&&(">"!==p[x]||!/--$/.test(p[x-1]));x++);if(x<g){if(a.comment){var l=p.slice(f,x).join("");a.comment(l.substr(0,l.length-2),m,B,d(a,p,x+1,c,m))}f=x+1}else c.noMoreEndComments=!0}c.noMoreEndComments&&a.pcdata&&a.pcdata("&lt;!--",m,B,d(a,p,f,c,m));break;case "<!":if(/^\w/.test(k)){if(!c.noMoreGT){for(x=
f+1;x<g&&">"!==p[x];x++);x<g?f=x+1:c.noMoreGT=!0}c.noMoreGT&&a.pcdata&&a.pcdata("&lt;!",m,B,d(a,p,f,c,m))}else a.pcdata&&a.pcdata("&lt;!",m,B,d(a,p,f,c,m));break;case "<?":if(!c.noMoreGT){for(x=f+1;x<g&&">"!==p[x];x++);x<g?f=x+1:c.noMoreGT=!0}c.noMoreGT&&a.pcdata&&a.pcdata("&lt;?",m,B,d(a,p,f,c,m));break;case ">":a.pcdata&&a.pcdata("&gt;",m,B,d(a,p,f,c,m));break;case "":break;default:a.pcdata&&a.pcdata(pa,m,B,d(a,p,f,c,m))}}a.endDoc&&a.endDoc(m)}catch(ra){if(ra!==B)throw ra;}}function M(b){var a=
/(<\/|<\!--|<[!?]|[&<>])/g;b+="";if(ha)return b.split(a);for(var d=[],c=0,m;null!==(m=a.exec(b));)d.push(b.substring(c,m.index)),d.push(m[0]),c=m.index+m[0].length;d.push(b.substring(c));return d}function I(b,a,c,e,m,f){var p=q(b,a);if(!p)return b.length;c.endTag&&c.endTag(p.name,e,m,d(c,b,a,f,e));return p.next}function r(b,a,c,e,m,f){a=q(b,a);if(!a)return b.length;c.startTag&&c.startTag(a.name,a.attrs,e,m,d(c,b,a.next,f,e));return a.eflags&qa?t(b,a,c,e,m,f):a.next}function t(a,c,e,f,m,g){var p=a.length;
ia.hasOwnProperty(c.name)||(ia[c.name]=new RegExp("^"+c.name+"(?:[\\s\\/]|$)","i"));for(var x=ia[c.name],A=c.next,k=c.next+1;k<p&&("</"!==a[k-1]||!x.test(a[k]));k++);k<p&&--k;var n=a.slice(A,k).join("");if(c.eflags&b.eflags.CDATA)e.cdata&&e.cdata(n,f,m,d(e,a,k,g,f));else if(c.eflags&b.eflags.RCDATA)e.rcdata&&e.rcdata(h(n),f,m,d(e,a,k,g,f));else throw Error("bug");return k}function q(a,c){var d=/^([-\w:]+)/.exec(a[c]),e={};e.name=d[1].toLowerCase();e.eflags=b.ELEMENTS[e.name];var f=a[c].substr(d[0].length);
c+=1;for(var g=a.length;c<g&&">"!==a[c];c++)f+=a[c];if(!(g<=c)){for(var p=[];""!==f;)if(d=K.exec(f))if(d[4]&&!d[5]||d[6]&&!d[7]){for(var h=d[4]||d[6],k=!1,A=[f,a[c++]];c<g;c++){if(k){if(">"===a[c])break}else 0<=a[c].indexOf(h)&&(k=!0);A.push(a[c])}if(g<=c)break;f=A.join("")}else{var n=d[1].toLowerCase(),l=d[2]?C(d[3]):"";p.push(n,l);f=f.substr(d[0].length)}else f=f.replace(/^[\s\S][^a-z\s]*/,"");e.attrs=p;e.next=c+1;return e}}function C(b){var a=b.charCodeAt(0);if(34===a||39===a)b=b.substr(1,b.length-
2);return f(c(b))}function g(a){function c(b,a){e||a.push(b)}var d,e;return u({startDoc:function(){d=[];e=!1},startTag:function(c,f,g){if(!e&&b.ELEMENTS.hasOwnProperty(c)){var m=b.ELEMENTS[c];if(!(m&b.eflags.FOLDABLE)){var h=a(c,f);if(h){if("object"!==typeof h)throw Error("tagPolicy did not return object (old API?)");if("attribs"in h)f=h.attribs;else throw Error("tagPolicy gave no attribs");var p,k;"tagName"in h?(k=h.tagName,p=b.ELEMENTS[k]):(k=c,p=m);if(m&b.eflags.OPTIONAL_ENDTAG){var n=d[d.length-
1];!n||n.orig!==c||n.rep===k&&c===k||g.push("</",n.rep,">")}m&b.eflags.EMPTY||d.push({orig:c,rep:k});g.push("<",k);for(var A=0,x=f.length;A<x;A+=2){var u=f[A],F=f[A+1];null!==F&&void 0!==F&&g.push(" ",u,'="',l(F),'"')}g.push(">");m&b.eflags.EMPTY&&!(p&b.eflags.EMPTY)&&g.push("</",k,">")}else e=!(m&b.eflags.EMPTY)}}},endTag:function(a,c){if(e)e=!1;else if(b.ELEMENTS.hasOwnProperty(a)){var f=b.ELEMENTS[a];if(!(f&(b.eflags.EMPTY|b.eflags.FOLDABLE))){if(f&b.eflags.OPTIONAL_ENDTAG)for(f=d.length;0<=--f;){var g=
d[f].orig;if(g===a)break;if(!(b.ELEMENTS[g]&b.eflags.OPTIONAL_ENDTAG))return}else for(f=d.length;0<=--f&&d[f].orig!==a;);if(!(0>f)){for(var m=d.length;--m>f;){var h=d[m].rep;b.ELEMENTS[h]&b.eflags.OPTIONAL_ENDTAG||c.push("</",h,">")}f<d.length&&(a=d[f].rep);d.length=f;c.push("</",a,">")}}}},pcdata:c,rcdata:c,cdata:c,endDoc:function(b){for(;d.length;d.length--)b.push("</",d[d.length-1].rep,">")}})}function H(b,a,c,d,f){if(!f)return null;try{var e=wa.parse(""+b);if(e&&(!e.hasScheme()||Ea.test(e.getScheme()))){var g=
f(e,a,c,d);return g?g.toString():null}}catch(Ra){}return null}function D(b,a,c,d,f){c||b(a+" removed",{change:"removed",tagName:a});if(d!==f){var e="changed";d&&!f?e="removed":!d&&f&&(e="added");b(a+"."+c+" "+e,{change:e,tagName:a,attribName:c,oldValue:d,newValue:f})}}function S(b,a,d){var c;c=a+"::"+d;if(b.hasOwnProperty(c))return b[c];c="*::"+d;if(b.hasOwnProperty(c))return b[c]}function la(a,c){return S(b.ATTRIBS,a,c)}function ga(a,c){return S(b.LOADERTYPES,a,c)}function U(a,c){return S(b.URIEFFECTS,
a,c)}function V(a,c,d,f,e){for(var g=0;g<c.length;g+=2){var h=c[g],k=c[g+1],m=k,n=null,p;if((p=a+"::"+h,b.ATTRIBS.hasOwnProperty(p))||(p="*::"+h,b.ATTRIBS.hasOwnProperty(p)))n=b.ATTRIBS[p];if(null!==n)switch(n){case b.atype.NONE:break;case b.atype.SCRIPT:k=null;e&&D(e,a,h,m,k);break;case b.atype.STYLE:if("undefined"===typeof X){k=null;e&&D(e,a,h,m,k);break}var l=[];X(k,{declaration:function(a,c){var e=a.toLowerCase();Y(e,c,d?function(a){return H(a,b.ueffects.SAME_DOCUMENT,b.ltypes.SANDBOXED,{TYPE:"CSS",
CSS_PROP:e},d)}:null);c.length&&l.push(e+": "+c.join(" "))}});k=0<l.length?l.join(" ; "):null;e&&D(e,a,h,m,k);break;case b.atype.ID:case b.atype.IDREF:case b.atype.IDREFS:case b.atype.GLOBAL_NAME:case b.atype.LOCAL_NAME:case b.atype.CLASSES:k=f?f(k):k;e&&D(e,a,h,m,k);break;case b.atype.URI:k=H(k,U(a,h),ga(a,h),{TYPE:"MARKUP",XML_ATTR:h,XML_TAG:a},d);e&&D(e,a,h,m,k);break;case b.atype.URI_FRAGMENT:k&&"#"===k.charAt(0)?(k=k.substring(1),k=f?f(k):k,null!==k&&void 0!==k&&(k="#"+k)):k=null;e&&D(e,a,h,
m,k);break;default:k=null,e&&D(e,a,h,m,k)}else k=null,e&&D(e,a,h,m,k);c[g+1]=k}return c}function Z(a,c,d){return function(e,f){if(b.ELEMENTS[e]&b.eflags.UNSAFE)d&&D(d,e,void 0,void 0,void 0);else return{attribs:V(e,f,a,c,d)}}}function Q(b,a){var c=[];g(a)(b,c);return c.join("")}function Fa(b,a,c,d){a=Z(a,c,d);return Q(b,a)}var X,Y,sa;"undefined"!==typeof window&&(X=window.parseCssDeclarations,Y=window.sanitizeCssProperty,sa=window.cssSchema);var W={lt:"<",LT:"<",gt:">",GT:">",amp:"&",AMP:"&",quot:'"',
apos:"'",nbsp:"\u00a0"},ma=/^#(\d+)$/,na=/^#x([0-9A-Fa-f]+)$/,oa=/^[A-Za-z][A-za-z0-9]+$/,J="undefined"!==typeof window&&window.document?window.document.createElement("textarea"):null,O=/\0/g,N=/&(#[0-9]+|#[xX][0-9A-Fa-f]+|\w+);/g,T=/^(#[0-9]+|#[xX][0-9A-Fa-f]+|\w+);/,k=/&/g,n=/&([^a-z#]|#(?:[^0-9x]|x(?:[^0-9a-f]|$)|$)|$)/gi,E=/[<]/g,F=/>/g,P=/\"/g,K=/^\s*([-.:\w]+)(?:\s*(=)\s*((")[^"]*("|$)|(')[^']*('|$)|(?=[a-z][-\w]*\s*=)|[^"'\s]*))?/i,ha=3==="a,b".split(/(,)/).length,qa=b.eflags.CDATA|b.eflags.RCDATA,
B={},ia={},Ea=/^(?:https?|mailto)$/i,y={};y.escapeAttrib=y.escapeAttrib=l;y.makeHtmlSanitizer=y.makeHtmlSanitizer=g;y.makeSaxParser=y.makeSaxParser=u;y.makeTagPolicy=y.makeTagPolicy=Z;y.normalizeRCData=y.normalizeRCData=h;y.sanitize=y.sanitize=Fa;y.sanitizeAttribs=y.sanitizeAttribs=V;y.sanitizeWithPolicy=y.sanitizeWithPolicy=Q;y.unescapeEntities=y.unescapeEntities=f;return y}(R);var ya={applet:!0,audio:!0,base:!0,embed:!0,form:!0,frame:!0,frameset:!0,iframe:!0,img:!0,link:!0,meta:!0,object:!0,script:!0,style:!0,svg:!0,template:!0,video:!0},za={br:!0,col:!0,hr:!0,img:!0,input:!0,source:!0,track:!0,wbr:!0,area:!0,base:!0,command:!0,embed:!0,keygen:!0,link:!0,meta:!0,param:!0},Aa="b br code del em i ins mark q s small strong sub sup time u".split(" "),Ba=["fallback","href","on","placeholder"],Ca=/^data-/i,Da=["_top","_blank"],Ga=["javascript:","vbscript:","data:","<script",
"\x3c/script"],Ha={input:{type:/(?:image|file|password|button)/i}},Ia="form formaction formmethod formtarget formnovalidate formenctype".split(" "),Ja={input:Ia,textarea:Ia,select:Ia};
function Ka(b){function a(b){0==f&&c.push(b)}var e=xa.makeTagPolicy(),c=[],f=0,l=xa.makeSaxParser({startTag:function(b,c){if(0<f)za[b]||f++;else{if(ya[b])f++;else if(0!=b.indexOf("amp-")){var d=c.slice(0),h=e(b,c);if(h){c=h.attribs;for(var l=0;l<c.length;l+=2)-1!=Ba.indexOf(c[l])?c[l+1]=d[l+1]:0==c[l].search(Ca)&&(c[l+1]=d[l+1])}else f++;if("a"==b){for(var l=-1,u=!1,r=0;r<d.length;r+=2)"target"==d[r]?l=r+1:"href"==d[r]&&(u=null!=c[r+1]);var t=-1!=l?d[l]:null;null!=t?(t=t.toLowerCase(),-1!=Da.indexOf(t)?
c[l]=t:c[l]="_top"):u&&(c.push("target"),c.push("_top"))}}if(0<f)za[b]&&f--;else{a("<");a(b);for(l=0;l<c.length;l+=2){var q=c[l],C=c[l+1];La(b,q,C)&&(a(" "),a(q),a('="'),C&&a(xa.escapeAttrib(Ma(b,q,C))),a('"'))}a(">")}}},endTag:function(b){0<f?f--:(a("</"),a(b),a(">"))},pcdata:a,rcdata:a,cdata:a});l(b);return c.join("")}
function La(b,a,e){if(0==a.indexOf("on")&&"on"!=a||"style"==a)return!1;if(e)for(var c=e.toLowerCase().replace(/[\s,\u0000]+/g,""),f=0;f<Ga.length;f++)if(-1!=c.indexOf(Ga[f]))return!1;var l=Ja[b];if(l&&-1!=l.indexOf(a))return!1;var h=Ha[b];if(h){var u=h[a];if(u&&-1!=e.search(u))return!1}return!0}function Ma(b,a,e){return"src"==a||"href"==a||"srcset"==a?Na(b,a,e):e}
function Na(b,a,e){var c=self.location;var f=G(e).search,l=Object.create(null);if(f){if(0==f.indexOf("?")||0==f.indexOf("#"))f=f.substr(1);for(var f=f.split("&"),h=0;h<f.length;h++){var u=f[h],d=u.indexOf("="),w;-1!=d?(w=decodeURIComponent(u.substring(0,d)).trim(),u=decodeURIComponent(u.substring(d+1)).trim()):(w=decodeURIComponent(u).trim(),u="");w&&(l[w]=u)}}v().assert(!("__amp_source_origin"in l),"Source origin is not allowed in %s",e);var M=ja(c);l=c;"string"==typeof l&&(l=G(l));ja(l)?(f=l.pathname.split("/"),
h=f[1],v().assert("c"==h||"v"==h,"Unknown path prefix in url %s",l.href),h=f[2],w="s"==h?"https://"+decodeURIComponent(f[3]):"http://"+decodeURIComponent(h),v().assert(0<w.indexOf("."),"Expected a . in origin %s",w),f.splice(1,"s"==h?3:2),f=w+f.join("/"),h=(h=l.search)&&"?"!=h?(h=h.replace(fa,"").replace(/^[?&]/,""))?"?"+h:"":"",l=f+h+(l.hash||"")):l=l.href;l=G(l);if("href"==a&&0!=e.indexOf("#"))return ka(e,l);if("src"==a)return"amp-img"==b?Oa(e,l,M):ka(e,l);if("srcset"==a){var I;try{var r=e.match(/\s*(?:[\S]*)(?:\s+(?:-?(?:\d+(?:\.(?:\d+)?)?|\.\d+)[a-zA-Z]))?(?:\s*,)?/g);
v().assert(0<r.length,"srcset has to have at least one source: %s",void 0);b=[];for(a=0;a<r.length;a++){var t=r[a].trim();","==t.substr(-1)&&(t=t.substr(0,t.length-1).trim());var q=t.split(/\s+/,2);if(0!=q.length&&(1!=q.length||q[0])&&(2!=q.length||q[0]||q[1])){var C=q[0];if(1==q.length||2==q.length&&!q[1])b.push({url:C,width:void 0,dpr:1});else{var g=q[1].toLowerCase(),H=g.substring(g.length-1);"w"==H?b.push({url:C,width:parseFloat(g),dpr:void 0}):"x"==H&&b.push({url:C,width:void 0,dpr:parseFloat(g)})}}}I=
new L(b)}catch(D){return v().error("sanitizer","Failed to parse srcset: ",D),e}e=I.getSources();for(r=0;r<e.length;r++)e[r].url=Oa(e[r].url,l,M);return I.stringify()}return e}function Oa(b,a,e){b=G(ka(b,a));return"data:"==b.protocol||ja(b)||!e?b.href:ca+"/i/"+("https:"==b.protocol?"s/":"")+encodeURIComponent(b.host)+b.pathname+(b.search||"")+(b.hash||"")};var Pa={};
(function defineMustache(a,e){e(Pa)})(this,function mustacheFactory(a){function e(a){return"function"===typeof a}function c(a){return g(a)?"array":typeof a}function f(a){return a.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,"\\$&")}function l(a,c){return null!=a&&"object"===typeof a&&Object.prototype.hasOwnProperty.call(a,c)}function h(a,c){return H.call(a,c)}function u(a){return!h(D,a)}function d(a){return String(a).replace(/[&<>"'`=\/]/g,function Y(a){return S[a]})}function w(c,d){function e(){if(w&&!J)for(;t.length;)delete q[t.pop()];
else t=[];J=w=!1}function h(a){"string"===typeof a&&(a=a.split(ga,2));if(!g(a)||2!==a.length)throw Error("Invalid tags: "+a);O=new RegExp(f(a[0])+"\\s*");N=new RegExp("\\s*"+f(a[1]));T=new RegExp("\\s*"+f("}"+a[1]))}if(!c)return[];var l=[],q=[],t=[],w=!1,J=!1,O,N,T;h(d||a.tags);for(var k=new r(c),n,E,F,P,K;!k.eos();){c=k.pos;if(E=k.scanUntil(O)){n=0;for(var ha=E.length;n<ha;++n)F=E.charAt(n),u(F)?t.push(q.length):J=!0,q.push(["text",F,c,c+1]),c+=1,"\n"===F&&e()}if(!k.scan(O))break;w=!0;n=k.scan(Z)||
"name";k.scan(la);"="===n?(E=k.scanUntil(U),k.scan(U),k.scanUntil(N)):"{"===n?(E=k.scanUntil(T),k.scan(V),k.scanUntil(N),n="&"):E=k.scanUntil(N);if(!k.scan(N))throw Error("Unclosed tag at "+k.pos);P=[n,E,c,k.pos];q.push(P);if("#"===n||"^"===n)l.push(P);else if("/"===n){K=l.pop();if(!K)throw Error('Unopened section "'+E+'" at '+c);if(K[1]!==E)throw Error('Unclosed section "'+K[1]+'" at '+c);}else if("name"===n||"{"===n||"&"===n)J=!0}if(K=l.pop())throw Error('Unclosed section "'+K[1]+'" at '+k.pos);
return I(M(q))}function M(a){for(var c=[],d,e,f=0,g=a.length;f<g;++f)if(d=a[f])"text"===d[0]&&e&&"text"===e[0]?(e[1]+=d[1],e[3]=d[3]):(c.push(d),e=d);return c}function I(a){for(var c=[],d=c,e=[],f,g,h=0,l=a.length;h<l;++h)switch(f=a[h],f[0]){case "#":case "^":d.push(f);e.push(f);d=f[4]=[];break;case "/":g=e.pop();g[5]=f[2];d=0<e.length?e[e.length-1][4]:c;break;default:d.push(f)}return c}function r(a){this.tail=this.string=a;this.pos=0}function t(a,c){this.view=a;this.cache={".":this.view};this.parent=
c}function q(){this.cache={}}var C=Object.prototype.toString,g=Array.isArray||function X(a){return"[object Array]"===C.call(a)},H=RegExp.prototype.test,D=/\S/,S={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;","/":"&#x2F;","`":"&#x60;","=":"&#x3D;"},la=/\s*/,ga=/\s+/,U=/\s*=/,V=/\s*\}/,Z=/#|\^|\/|>|\{|&|=|!/;r.prototype.eos=function Y(){return""===this.tail};r.prototype.scan=function sa(a){var c=this.tail.match(a);if(!c||0!==c.index)return"";a=c[0];this.tail=this.tail.substring(a.length);
this.pos+=a.length;return a};r.prototype.scanUntil=function W(a){a=this.tail.search(a);var c;switch(a){case -1:c=this.tail;this.tail="";break;case 0:c="";break;default:c=this.tail.substring(0,a),this.tail=this.tail.substring(a)}this.pos+=c.length;return c};t.prototype.push=function ma(a){return new t(a,this)};t.prototype.lookup=function na(a){var c=this.cache,d;if(c.hasOwnProperty(a))d=c[a];else{for(var f=this,g,k,h=!1;f;){if(0<a.indexOf("."))for(d=f.view,g=a.split("."),k=0;null!=d&&k<g.length;){if(!l(d,
g[k])){d=null;break}k===g.length-1&&(h=!0);d=d[g[k++]]}else l(f.view,a)?(d=f.view[a],h=!0):d=null;if(h)break;f=f.parent}c[a]=d}e(d)&&(d=d.call(this.view));return d};q.prototype.clearCache=function oa(){this.cache={}};q.prototype.parse=function(a,c){var d=this.cache,e=d[a];null==e&&(e=d[a]=w(a,c));return e};q.prototype.render=function J(a,c,d){var e=this.parse(a);c=c instanceof t?c:new t(c);return this.renderTokens(e,c,d,a)};q.prototype.renderTokens=function O(a,c,d,e){for(var f="",g,k,h,l=0,n=a.length;l<
n;++l)h=void 0,g=a[l],k=g[0],"#"===k?h=this.renderSection(g,c,d,e):"^"===k?h=this.renderInverted(g,c,d,e):">"===k?h=this.renderPartial(g,c,d,e):"&"===k?h=this.unescapedValue(g,c):"name"===k?h=this.escapedValue(g,c):"text"===k&&(h=this.rawValue(g)),void 0!==h&&(f+=h);return f};q.prototype.renderSection=function N(a,c,d,f){function h(a){return k.render(a,c,d)}var k=this,l="",n=c.lookup(a[1]);if(n){if(g(n))for(var q=0,r=n.length;q<r;++q)l+=this.renderTokens(a[4],c.push(n[q]),d,f);else if("object"===
typeof n||"string"===typeof n||"number"===typeof n)l+=this.renderTokens(a[4],c.push(n),d,f);else if(e(n)){if("string"!==typeof f)throw Error("Cannot use higher-order sections without the original template");n=n.call(c.view,f.slice(a[3],a[5]),h);null!=n&&(l+=n)}else l+=this.renderTokens(a[4],c,d,f);return l}};q.prototype.renderInverted=function T(a,c,d,e){var f=c.lookup(a[1]);if(!f||g(f)&&0===f.length)return this.renderTokens(a[4],c,d,e)};q.prototype.renderPartial=function k(a,c,d){if(d&&(a=e(d)?d(a[1]):
d[a[1]],null!=a))return this.renderTokens(this.parse(a),c,d,a)};q.prototype.unescapedValue=function n(c,d){c=d.lookup(c[1]);if(null!=c)return a.sanitizeUnescaped?a.sanitizeUnescaped(c):c};q.prototype.escapedValue=function E(c,d){c=d.lookup(c[1]);if(null!=c)return a.escape(c)};q.prototype.rawValue=function F(a){return a[1]};a.name="mustache.js";a.version="2.2.0";a.tags=["{{","}}"];var Q=new q;a.clearCache=function(){return Q.clearCache()};a.parse=function(a,c){return Q.parse(a,c)};a.render=function(a,
d,e){if("string"!==typeof a)throw new TypeError('Invalid template! Template should be a "string" but "'+c(a)+'" was given as the first argument for mustache#render(template, view, partials)');return Q.render(a,d,e)};a.to_html=function P(c,d,f,g){var h=a.render(c,d,f);if(e(g))g(h);else return h};a.escape=d;a.sanitizeUnescaped=null;a.setUnescapedSanitizier=function K(c){a.sanitizeUnescaped=c};a.Scanner=r;a.Context=t;a.Writer=q});Pa.setUnescapedSanitizier(function(b){return xa.sanitizeWithPolicy(b,function(a){return-1==Aa.indexOf(a)?null:{tagName:a,attribs:[]}})});function Qa(b){AMP.BaseTemplate.apply(this,arguments)}aa(Qa,AMP.BaseTemplate);Qa.prototype.compileCallback=function(){this.A=this.element.innerHTML;Pa.parse(this.A)};Qa.prototype.render=function(b){b=Pa.render(this.A,b);var a=Ka(b);b=this.win.document.createElement("div");b.innerHTML=a;return this.unwrap(b)};AMP.registerTemplate("amp-mustache",Qa);
})});
//# sourceMappingURL=amp-mustache-0.1.js.map

