(self.AMP = self.AMP || []).push({n:"amp-accordion", f:(function(AMP) {function h(a,b){function d(){}d.prototype=b.prototype;a.prototype=new d;a.prototype.constructor=a;for(var e in b)if(Object.defineProperties){var f=Object.getOwnPropertyDescriptor(b,e);f&&Object.defineProperty(a,e,f)}else a[e]=b[e]};function k(){var a,b=Object.create(null);a&&Object.assign(b,a);return b};Date.now();self.log=self.log||{user:null,dev:null};var n=self.log;function p(){if(n.user)return n.user;throw Error("failed to call initLogConstructor");};var q;
function r(a){var b="amp-accordion-session-state-optout",d=q||(q=Object.create(null)),e;if(b in d)e=d[b];else{e=b;var f=b,c;if(a._experimentCookie)c=a._experimentCookie;else{c:{d:{try{c=a.document.cookie;break d}catch(x){}c=void 0}if(c){c=c.split(";");for(var g=0;g<c.length;g++){var l=c[g].trim(),m=l.indexOf("=");if(-1!=m&&"AMP_EXP"==decodeURIComponent(l.substring(0,m).trim())){c=decodeURIComponent(l.substring(m+1).trim());break c}}}c=null}c=a._experimentCookie=c?c.split(/\s*,\s*/g):[]}a=-1!=c.indexOf(f)?
!0:a.AMP_CONFIG&&a.AMP_CONFIG.hasOwnProperty(f)?Math.random()<a.AMP_CONFIG[f]:!1;e=d[e]=a}return e};function t(a){AMP.BaseElement.call(this,a);this.a=this.b=this.f=null;this.c=!1}h(t,AMP.BaseElement);t.prototype.isLayoutSupported=function(a){return"container"==a};
t.prototype.buildCallback=function(){var a=this;this.f=this.getRealChildren();r(this.win)&&(this.c=this.element.hasAttribute("disable-session-states"));this.element.setAttribute("role","tablist");this.b=u(this);this.a=v(this);this.f.forEach(function(b,d){p().assert("section"==b.tagName.toLowerCase(),"Sections should be enclosed in a <section> tag, See https://github.com/ampproject/amphtml/blob/master/extensions/amp-accordion/amp-accordion.md. Found in: %s",a.element);var e=b.children;p().assert(2==
e.length,"Each section must have exactly two children. See https://github.com/ampproject/amphtml/blob/master/extensions/amp-accordion/amp-accordion.md. Found in: %s",a.element);var f=e[0],c=e[1];f.classList.add("-amp-accordion-header");f.setAttribute("role","tab");c.classList.add("-amp-accordion-content");c.setAttribute("role","tabpanel");var g=c.getAttribute("id");g||(g=a.element.id+"_AMP_content_"+d,c.setAttribute("id",g));a.a[g]?b.setAttribute("expanded",""):0==a.a[g]&&b.removeAttribute("expanded");
f.setAttribute("aria-controls",g);f.setAttribute("aria-expanded",b.hasAttribute("expanded").toString());f.addEventListener("click",a.g.bind(a))})};function u(a){var b=a.element.id;a=a.win.location.href;var d=a.indexOf("#");a=-1==d?a:a.substring(0,d);return"amp-"+b+"-"+a}function v(a){if(a.c)return k();try{var b=a.win.sessionStorage.getItem(a.b);return b?JSON.parse(b):k()}catch(d){return k()}}function w(a){if(!a.c){var b=JSON.stringify(a.a);try{a.win.sessionStorage.setItem(a.b,b)}catch(d){}}}
t.prototype.g=function(a){a.preventDefault();var b=a.currentTarget.parentNode,d=b.children,e=d[0],d=d[1],f=d.getAttribute("id"),c=b.hasAttribute("expanded");this.mutateElement(function(){b.hasAttribute("expanded")?(b.removeAttribute("expanded"),e.setAttribute("aria-expanded","false")):(b.setAttribute("expanded",""),e.setAttribute("aria-expanded","true"))},d);this.a[f]=!c;w(this)};AMP.registerElement("amp-accordion",t,"amp-accordion{display:block!important}amp-accordion>section{float:none!important}amp-accordion>section>:nth-child(n){display:none!important;float:none!important}amp-accordion>section>.-amp-accordion-content,amp-accordion>section>.-amp-accordion-header{display:block!important;overflow:hidden!important;position:relative!important}.-amp-accordion-content,.-amp-accordion-header,amp-accordion,amp-accordion>section{margin:0}.-amp-accordion-header{cursor:pointer;background-color:#efefef;padding-right:20px;border:1px solid #dfdfdf}amp-accordion>section>.-amp-accordion-content{display:none!important}amp-accordion>section[expanded]>.-amp-accordion-content{display:block!important}\n/*# sourceURL=/extensions/amp-accordion/0.1/amp-accordion.css*/");
})});
//# sourceMappingURL=amp-accordion-0.1.js.map

