(self.AMP = self.AMP || []).push({n:"amp-instagram", f:(function(AMP) {var c;function m(a,b){function g(){}g.prototype=b.prototype;a.prototype=new g;a.prototype.constructor=a;for(var e in b)if(Object.defineProperties){var l=Object.getOwnPropertyDescriptor(b,e);l&&Object.defineProperty(a,e,l)}else a[e]=b[e]};Date.now();self.log=self.log||{user:null,dev:null};var n=self.log;var q,r="Webkit webkit Moz moz ms O o".split(" ");function t(a,b){for(var g in b){var e=a,l=b[g],f;f=e.style;var h=g;q||(q=Object.create(null));var k=q[h];if(!k){k=h;if(void 0===f[h]){var d;d=h;d=d.charAt(0).toUpperCase()+d.slice(1);a:{for(var p=0;p<r.length;p++){var u=r[p]+d;if(void 0!==f[u]){d=u;break a}}d=""}void 0!==f[d]&&(k=d)}q[h]=k}(f=k)&&(e.style[f]=l)}};function v(a){AMP.BaseElement.call(this,a);this.c=this.a=null;this.b=""}m(v,AMP.BaseElement);c=v.prototype;c.preconnectCallback=function(a){this.preconnect.url("https://www.instagram.com",a);this.preconnect.url("https://instagram.fsnc1-1.fna.fbcdn.net",a)};c.renderOutsideViewport=function(){return!1};
c.buildCallback=function(){var a;if(n.user)a=n.user;else throw Error("failed to call initLogConstructor");this.b=a.assert(this.element.getAttribute("data-shortcode")||this.element.getAttribute("shortcode"),"The data-shortcode attribute is required for <amp-instagram> %s",this.element)};
c.createPlaceholderCallback=function(){var a=this.win.document.createElement("div");a.setAttribute("placeholder","");var b=this.win.document.createElement("amp-img");b.setAttribute("noprerender","");b.setAttribute("src","https://www.instagram.com/p/"+encodeURIComponent(this.b)+"/media/?size=l");b.setAttribute("layout","fill");b.setAttribute("referrerpolicy","origin");this.propagateAttributes(["alt"],b);t(b,{top:"48px",bottom:"48px",left:"8px",right:"8px"});a.appendChild(b);return a};
c.isLayoutSupported=function(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a};
c.layoutCallback=function(){var a=this,b=this.element.ownerDocument.createElement("iframe");this.a=b;b.setAttribute("frameborder","0");b.setAttribute("allowtransparency","true");b.setAttribute("title","Instagram: "+this.element.getAttribute("alt"));b.src="https://www.instagram.com/p/"+encodeURIComponent(this.b)+"/embed/?v=4";this.applyFillContent(b);this.element.appendChild(b);t(b,{opacity:0});return this.c=this.loadPromise(b).then(function(){a.getVsync().mutate(function(){t(b,{opacity:1})})})};
c.unlayoutOnPause=function(){return!0};c.unlayoutCallback=function(){if(this.a){var a=this.a;a.parentElement&&a.parentElement.removeChild(a);this.c=this.a=null}return!0};AMP.registerElement("amp-instagram",v);
})});
//# sourceMappingURL=amp-instagram-0.1.js.map

