(self.AMP = self.AMP || []).push({n:"amp-iframe", f:(function(AMP) {var k;function m(a,b){function d(){}d.prototype=b.prototype;a.prototype=new d;a.prototype.constructor=a;for(var c in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,c);e&&Object.defineProperty(a,c,e)}else a[c]=b[c]};Date.now();self.log=self.log||{user:null,dev:null};var t=self.log;function w(){if(t.user)return t.user;throw Error("failed to call initLogConstructor");}function x(){if(t.dev)return t.dev;throw Error("failed to call initLogConstructor");};function y(a){a=a.__AMP_TOP||a;var b=a.services&&a.services.timer&&a.services.timer.obj;return b};function z(a,b){var d=a.length-b.length;return 0<=d&&a.indexOf(b,d)==d};var B=(self.AMP_CONFIG||{}).thirdPartyFrameHost||"ampproject.net";var C,D;
function E(a){var b;C||(C=self.document.createElement("a"),D=self.UrlCache||(self.UrlCache=Object.create(null)));var d=D[a];if(d)return d;C.href=a;C.protocol||(C.href=C.href);var c={href:C.href,protocol:C.protocol,host:C.host,hostname:C.hostname,port:"0"==C.port?"":C.port,pathname:C.pathname,search:C.search,hash:C.hash,origin:null};"/"!==c.pathname[0]&&(c.pathname="/"+c.pathname);if("http:"==c.protocol&&80==c.port||"https:"==c.protocol&&443==c.port)c.port="",c.host=c.hostname;c.origin=C.origin&&"null"!=
C.origin?C.origin:"data:"!=c.protocol&&c.host?c.protocol+"//"+c.host:c.href;var e=c;return b?e:D[a]=e};var F,G="Webkit webkit Moz moz ms O o".split(" ");function H(a,b){var d,c=a.style;F||(F=Object.create(null));var e=F.zIndex;if(!e){e="zIndex";if(void 0===c.zIndex){var f="Z"+"zIndex".slice(1);a:{for(var g=0;g<G.length;g++){var n=G[g]+f;if(void 0!==c[n]){f=n;break a}}f=""}void 0!==c[f]&&(e=f)}F.zIndex=e}(c=e)&&(a.style[c]=d?b+d:b)};var I={"AMP-FX-FLYING-CARPET":!0,"AMP-LIGHTBOX":!0,"AMP-STICKY-AD":!0};function J(a,b){for(var d=[],c=0;c<a.length;c++){var e=a[c];b(e,c,a)||(d.push(e),a.splice(c,1),c--)}};function K(a,b,d){var c=a.listeningFors;!c&&d&&(c=a.listeningFors=Object.create(null));a=c||null;if(!a)return a;var e=a[b];!e&&d&&(e=a[b]=[]);return e||null}function L(a,b,d){var c=E(b.src).origin,e=d?b.getAttribute("data-amp-3p-sentinel"):"amp";a=K(a,e,!0);for(var f,e=0;e<a.length;e++){var g=a[e];if(g.frame===b){f=g;break}}f||(f={frame:b,origin:c,events:Object.create(null)},a.push(f));return f.events}
function M(a){for(var b={sentinel:"unlisten"},d=a.length-1;0<=d;d--){var c=a[d];if(!c.frame.contentWindow){a.splice(d,1);var e=c.events,f;for(f in e)e[f].splice(0,Infinity).forEach(function(a){a(b)})}}}
function N(a){if(!a.listeningFors){var b=function(b){if(b.data){var c=b.data;if("string"===typeof c&&"{"===c.charAt(0))try{c=JSON.parse(c)}catch(A){x().warn("IFRAME-HELPER","Postmessage could not be parsed. Is it in a valid JSON format?",A)}if(c.sentinel){var d;var f=c.sentinel,g=b.origin,n=b.source,h=K(a,f);if(h){for(var l=0;l<h.length;l++){var u=h[l],q=u.frame.contentWindow;if(q)if("amp"===f){if(u.origin===g&&q==n){d=u;break}}else{var p;if(!(p=n==q))b:{for(p=n;p&&p!=p.parent;p=p.parent)if(p==q){p=
!0;break b}p=!1}if(p){d=u;break}}else setTimeout(M,0,h)}d=d?d.events:null}else d=h;var v=d;if(v){var r=v[c.type];if(r)for(r=r.slice(),d=0;d<r.length;d++)(0,r[d])(c,b.source,b.origin)}}}};a.addEventListener("message",b)}}function O(a,b,d,c,e){function f(b,c,f){if(e||c==a.contentWindow)"unlisten"==b.sentinel?h():d(b,c,f)}var g=a.ownerDocument.defaultView;N(g);c=L(g,a,c);var n=c[b]||(c[b]=[]),h;n.push(f);return h=function(){if(f){var a=n.indexOf(f);-1<a&&n.splice(a,1);d=n=f=null}}}
function P(a,b,d,c,e){if(a.contentWindow){c.type=d;c.sentinel=e?a.getAttribute("data-amp-3p-sentinel"):"amp";var f=c;e&&(f="amp-"+JSON.stringify(c));for(a=0;a<b.length;a++)d=b[a],d.win.postMessage(f,d.origin)}}function Q(a,b,d,c){var e=this;this.a=a;this.o=d;this.f=[];this.K=O(this.a,b,function(a,b,d){e.f.some(function(a){return a.win==b})||e.f.push({win:b,origin:d});c(a,b,d)},this.o,this.o)}Q.prototype.send=function(a,b){J(this.f,function(a){return!!a.win.parent});P(this.a,this.f,a,b,this.o)};
Q.prototype.destroy=function(){this.K();this.f.length=0};function R(a,b,d,c){return{left:a,top:b,width:d,height:c,bottom:b+c,right:a+d}}function aa(a){for(var b=-Infinity,d=Infinity,c=-Infinity,e=Infinity,f=0;f<arguments.length;f++){var g=arguments[f];if(g&&(b=Math.max(b,g.left),d=Math.min(d,g.left+g.width),c=Math.max(c,g.top),e=Math.min(e,g.top+g.height),d<b||e<c))return null}return Infinity==d?null:R(b,c,d-b,e-c)}function S(a,b,d){return 0==b&&0==d||0==a.width&&0==a.height?a:R(a.left+b,a.top+d,a.width,a.height)};var ba=[0,.05,.1,.15,.2,.25,.3,.35,.4,.45,.5,.55,.6,.65,.7,.75,.8,.85,.9,.95,1],ca=Date.now();function T(a,b,d){var c=this;this.j=a;this.h=null;this.v=this.C=!1;this.i=null;this.F=a.getViewport();this.D=new Q(b,"send-intersections",d||!1,function(){da(c)});this.h=new U(function(a){for(var b=0;b<a.length;b++)delete a[b].target;c.D.send("intersection",{changes:a})},{threshold:ba});this.fire=function(){c.C&&c.v&&c.h.tick(c.F.getRect())}}
function da(a){a.C=!0;a.h.observe(a.j.element);a.j.getVsync().measure(function(){a.v=a.j.isInViewport();a.fire()});var b=a.F.onScroll(a.fire),d=a.F.onChanged(a.fire);a.i=function(){b();d()}}T.prototype.onViewportCallback=function(a){this.v=a};T.prototype.destroy=function(){this.C=!1;this.h=null;this.i&&(this.i(),this.i=null);this.D.destroy();this.D=null};function U(a,b){this.I=a;var d=b&&b.threshold||[0];this.J=d.sort();this.c=[]}
U.prototype.observe=function(a){a.isBuilt&&a.isBuilt();for(var b=0;b<this.c.length;b++)if(this.c[b].element===a){x().warn("INTERSECTION-OBSERVER","should observe same element once");return}this.c.push({element:a,currentThresholdSlot:0})};U.prototype.unobserve=function(a){for(var b=0;b<this.c.length;b++)if(this.c[b].element===a){this.c.splice(b,1);return}x().warn("INTERSECTION-OBSERVER","unobserve non-observed element")};
U.prototype.tick=function(a,b){b&&(a=S(a,-b.left,-b.top),b=S(b,-b.left,-b.top));for(var d=[],c=0;c<this.c.length;c++){var e;var f=this.c[c],g=a,n=b;e=f.element;var h,l;h=e.getLayoutBox();l=(l=e.getOwner())&&l.getLayoutBox();var u=aa(h,l,g,n)||R(0,0,0,0);l=u.width*u.height/(h.width*h.height);var q;q=this.J;var p=0,v=q.length;if(0==l)q=0;else{for(var r=(p+v)/2|0;p<r;)l<q[r]?v=r:p=r,r=(p+v)/2|0;q=v}if(q==f.currentThresholdSlot)e=null;else{f.currentThresholdSlot=q;f=n?null:g;g=u;n=l;if(l=f)g=S(g,-f.left,
-f.top),h=S(h,-f.left,-f.top),l=S(l,-f.left,-f.top);h={time:"undefined"!==typeof performance&&performance.now?performance.now():Date.now()-ca,rootBounds:l&&V(l),boundingClientRect:V(h),intersectionRect:V(g),intersectionRatio:n};h.target=e;e=h}var A=e;A&&d.push(A)}d.length&&this.I(d)};function V(a){return{left:a.left,top:a.top,width:a.width,height:a.height,bottom:a.bottom,right:a.right,x:a.left,y:a.top}};var ea=0,W=0;function X(a){AMP.BaseElement.apply(this,arguments)}m(X,AMP.BaseElement);k=X.prototype;k.isLayoutSupported=function(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a};
k.assertSource=function(a,b,d){var c=E(a);w().assert("https:"==c.protocol||"data:"==c.protocol||0==c.origin.indexOf("http://iframe.localhost:"),"Invalid <amp-iframe> src. Must start with https://. Found %s",this.element);var e=E(b);w().assert(!(" "+d+" ").match(/\s+allow-same-origin\s+/i)||c.origin!=e.origin&&"data:"!=c.protocol,"Origin of <amp-iframe> must not be equal to container %sif allow-same-origin is set. See https://github.com/ampproject/amphtml/blob/master/spec/amp-iframe-origin-policy.md for details.",
this.element);w().assert(!(z(c.hostname,"."+B)||z(c.hostname,".ampproject.org")),"amp-iframe does not allow embedding of frames from ampproject.*: %s",a);return a};
k.assertPosition=function(){var a=this.element.getLayoutBox(),b=Math.min(600,.75*this.getViewport().getSize().height);w().assert(a.top>=b,"<amp-iframe> elements must be positioned outside the first 75% of the viewport or 600px from the top (whichever is smaller): %s  Current position %s. Min: %sPositioning rules don't apply for iframes that use `placeholder`.See https://github.com/ampproject/amphtml/blob/master/extensions/amp-iframe/amp-iframe.md#iframe-with-placeholder for details.",this.element,
a.top,b)};
k.firstAttachedCallback=function(){this.B=this.element.getAttribute("sandbox");var a;if(a=this.element.getAttribute("src")){var b=E(a);"data:"==b.protocol||b.hash&&"#"!=b.hash||(b=a.indexOf("#"),a=(-1==b?a:a.substring(0,b))+"#amp=1")}else a=void 0;if(!a)if(a=this.element.getAttribute("srcdoc"),b=this.B,a){w().assert(!(" "+b+" ").match(/\s+allow-same-origin\s+/i),"allow-same-origin is not allowed with the srcdoc attribute %s.",this.element);if("undefined"!==typeof TextEncoder)a=(new TextEncoder("utf-8")).encode(a);else{a=
unescape(encodeURIComponent(a));for(var b=new Uint8Array(a.length),d=0;d<a.length;d++){var c=a.charCodeAt(d);b[d]=c}a=b}a="data:text/html;charset=utf-8;base64,"+btoa(String.fromCharCode.apply(String,a))}else a=void 0;var e=a;this.iframeSrc=this.assertSource(e,window.location.href,this.B);a=this.element;"no"!=a.getAttribute("scrolling")&&(b=a.ownerDocument.createElement("i-amp-scroll-container"),a.appendChild(b),a=b);this.l=a};
k.preconnectCallback=function(a){this.iframeSrc&&this.preconnect.url(this.iframeSrc,a)};k.buildCallback=function(){this.A=this.getPlaceholder();this.u=!!this.A;this.H=this.g=this.s=!1;this.a=this.m=this.L=null;(this.w=this.element.hasAttribute("resizable"))&&this.element.setAttribute("scrolling","no");this.b=null;this.element.hasAttribute("frameborder")||this.element.setAttribute("frameborder","0")};
k.onLayoutMeasure=function(){Y(this);var a;a:{var b=this.element.getLayoutBox();a=b.height;for(var b=b.width,d=0;d<Z.length;d++){var c=Z[d][0],e=Z[d][1];if(!(e>a||c>b)&&20>=a-e&&20>=b-c){a=!0;break a}}a=!1}this.s=a;a=this.element.getLayoutBox();this.g=10<a.width&&10<a.height?!1:!0;if(a=this.s){a=this.win;b=!1;d=0;c=this.element;do I[c.tagName]?(d++,b=!1):"fixed"==a.getComputedStyle(c).position&&(b=!0),c=c.parentElement;while(c&&"BODY"!=c.tagName);a=!(!b&&1>=d)}this.H=a;this.b&&this.b.fire()};
function Y(a){if(a.a){var b=a.getViewport().getLayoutRect(a.a),d=a.getLayoutBox();a.m=S(b,-d.left,-d.top)}}k.getIntersectionElementLayoutBox=function(){if(!this.a)return AMP.BaseElement.prototype.getIntersectionElementLayoutBox.call(this);var a=this.getLayoutBox();this.m||Y(this);return S(this.m,a.left,a.top)};
k.layoutCallback=function(){var a=this;w().assert(!this.H,"amp-iframe is not used for displaying fixed ad. Please use amp-sticky-ad and amp-ad instead.");this.u||this.assertPosition();this.w&&w().assert(this.getOverflowElement(),"Overflow element must be defined for resizable frames: %s",this.element);if(!this.iframeSrc)return Promise.resolve();if(this.g&&(W++,1<W))return console.error("Only 1 analytics/tracking iframe allowed per page. Please use amp-analytics instead or file a GitHub issue for your use case: https://github.com/ampproject/amphtml/issues/new"),
Promise.resolve();var b=this.element.ownerDocument.createElement("iframe");this.a=b;this.applyFillContent(b);b.name="amp_iframe"+ea++;this.u&&H(b,-1);this.propagateAttributes(["frameborder","allowfullscreen","allowtransparency","scrolling","referrerpolicy"],b);fa(b,this.B);b.src=this.iframeSrc;this.g||(this.b=new T(this,b));b.onload=function(){b.readyState="complete";a.G();a.g&&(a.iframeSrc=null,y(a.win).promise(5E3).then(function(){b.parentElement&&b.parentElement.removeChild(b);a.element.setAttribute("amp-removed",
"");a.a=null}))};O(b,"embed-size",function(b){ga(a,b.height,b.width)});this.u&&O(b,"embed-ready",this.G.bind(this));this.l.appendChild(b);return this.loadPromise(b).then(function(){a.l!=a.element&&y(a.win).delay(function(){a.deferMutate(function(){a.l.classList.add("amp-active")})},1E3)})};k.unlayoutOnPause=function(){return!0};
k.unlayoutCallback=function(){if(this.a){var a=this.a;a.parentElement&&a.parentElement.removeChild(a);this.A&&this.togglePlaceholder(!0);this.a=null;this.b&&(this.b.destroy(),this.b=null)}return!0};k.viewportCallback=function(a){if(this.b)this.b.onViewportCallback(a)};k.getPriority=function(){return this.s?2:this.g?1:AMP.BaseElement.prototype.getPriority.call(this)};k.G=function(){var a=this;this.A&&this.getVsync().mutate(function(){a.a&&(H(a.a,0),a.togglePlaceholder(!1))})};
k.firstLayoutCompleted=function(){};
function ga(a,b,d){if(a.w)if(100>b)w().error("amp-iframe","Ignoring embed-size request because the resize height is less than 100px. If you are using amp-iframe to display ads, consider using amp-ad instead.",a.element);else{var c,e;b=parseInt(b,10);isNaN(b)||(c=Math.max(b+(a.element.offsetHeight-a.a.offsetHeight),b));d=parseInt(d,10);isNaN(d)||(e=Math.max(d+(a.element.offsetWidth-a.a.offsetWidth),d));void 0!==c||void 0!==e?a.attemptChangeSize(c,e).then(function(){void 0!==c&&a.element.setAttribute("height",
c);void 0!==e&&a.element.setAttribute("width",e)},function(){}):w().error("amp-iframe","Ignoring embed-size request becauseno width or height value is provided",a.element)}else w().error("amp-iframe","Ignoring embed-size request because this iframe is not resizable",a.element)}function fa(a,b){var d=b||"";a.setAttribute("sandbox",d)}var Z=[[300,250],[320,50],[300,50],[320,100]];AMP.registerElement("amp-iframe",X);
})});
//# sourceMappingURL=amp-iframe-0.1.js.map

