(self.AMP = self.AMP || []).push({n:"amp-form", f:(function(AMP) {var k;function m(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]};function n(a){if(!a)return[];for(var b=Array(a.length),c=0;c<a.length;c++)b[c]=a[c];return b};Date.now();function aa(a){for(var b=null,c="",d=0;d<arguments.length;d++){var e=arguments[d];e instanceof Error&&!b?b=e:(c&&(c+=" "),c+=e)}b?c&&(b.message=c+": "+b.message):b=Error(c);return b}function ba(a){var b=aa.apply(null,arguments);setTimeout(function(){throw b;})}self.log=self.log||{user:null,dev:null};var p=self.log;function q(){if(p.user)return p.user;throw Error("failed to call initLogConstructor");};function ca(a,b,c){if(b(a))c();else{var d=a.ownerDocument.defaultView;if(d.MutationObserver){var e=new d.MutationObserver(function(){b(a)&&(e.disconnect(),c())});e.observe(a,{childList:!0})}else var f=d.setInterval(function(){b(a)&&(d.clearInterval(f),c())},5)}}function da(a,b){ca(a.documentElement,function(){return!!a.body},b)}function ea(a){return new Promise(function(b){da(a,b)})}function fa(a,b){for(var c=a.firstElementChild;c;c=c.nextElementSibling)if(b(c))return c;return null}var r;
function ga(a){if(null==r)try{a.ownerDocument.querySelector(":scope"),r=!0}catch(b){r=!1}return r?a.querySelector(":scope > [i-amp-rendered]"):fa(a,function(a){return a.hasAttribute("i-amp-rendered")})}function ha(a,b){for(var c=[],d=a.parentElement;d;d=d.parentElement)b(d)&&c.push(d);return c}function t(a){var b="fieldset",b=b.toUpperCase();return ha(a,function(a){return a.tagName==b})};function u(a,b){a=a.__AMP_TOP||a;var c=a.services&&a.services[b]&&a.services[b].obj;return c}function v(a,b){var c=a,c=c.nodeType?w((c.ownerDocument||c).defaultView,"ampdoc").getAmpDoc(c):c,d=c.isSingleDoc()?c.win:c;return d&&d.services&&d.services[b]&&d.services[b].obj}function w(a,b,c){var d=a=a.__AMP_TOP||a,e=c?c:void 0;a=x(a);var f=a[b];f||(f=a[b]={obj:null,promise:null,resolve:null});f.obj||(f.obj=e(d),f.resolve&&f.resolve(f.obj));return f.obj}
function y(a){var b=z(a);if(b)return b;a=x(a);var c,d=new Promise(function(a){c=a});a["amp-analytics-instrumentation"]={obj:null,promise:d,resolve:c};return d}function z(a){if(a=x(a)["amp-analytics-instrumentation"]){var b=a.promise;if(b)return b;if(a.obj)return a.promise=Promise.resolve(a.obj)}return null}function x(a){var b=a.services;b||(b=a.services={});return b};function ia(a){var b=z(a);return b?b:Promise.resolve().then(function(){return a.ampExtendedElements&&a.ampExtendedElements["amp-analytics"]?y(a):ea(a.document).then(function(){return a.ampExtendedElements&&a.ampExtendedElements["amp-analytics"]?y(a):null})})};var ja=/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org/;var A,B;
function C(a){var b;A||(A=self.document.createElement("a"),B=self.UrlCache||(self.UrlCache=Object.create(null)));var c=B[a];if(c)return c;A.href=a;A.protocol||(A.href=A.href);var d={href:A.href,protocol:A.protocol,host:A.host,hostname:A.hostname,port:"0"==A.port?"":A.port,pathname:A.pathname,search:A.search,hash:A.hash,origin:null};"/"!==d.pathname[0]&&(d.pathname="/"+d.pathname);if("http:"==d.protocol&&80==d.port||"https:"==d.protocol&&443==d.port)d.port="",d.host=d.hostname;d.origin=A.origin&&"null"!=
A.origin?A.origin:"data:"!=d.protocol&&d.host?d.protocol+"//"+d.host:d.href;var e=d;return b?e:B[a]=e}function ka(a,b){var c=[],d;for(d in b){var e=b[d];if(null!=e)if(Array.isArray(e))for(var f=0;f<e.length;f++){var g=e[f];c.push(encodeURIComponent(d)+"="+encodeURIComponent(g))}else c.push(encodeURIComponent(d)+"="+encodeURIComponent(e))}if(b=c.join("&"))a=a.split("#",2),c=a[0].split("?",2),b=c[0]+(c[1]?"?"+c[1]+"&"+b:"?"+b),a=b+=a[1]?"#"+a[1]:"";return a}
function la(a){"string"==typeof a&&(a=C(a));var b;(b="https:"==a.protocol||"localhost"==a.hostname)||(a=a.hostname,b=a.length-10,b=0<=b&&a.indexOf(".localhost",b)==b);return b}function ma(a){"string"==typeof a&&(a=C(a));return ja.test(a.origin)};var D;
function F(a,b){var c=D||(D=Object.create(null));if(b in c)a=c[b];else{var d=b,e;if(a._experimentCookie)e=a._experimentCookie;else{c:{d:{try{e=a.document.cookie;break d}catch(l){}e=void 0}if(e){e=e.split(";");for(var f=0;f<e.length;f++){var g=e[f].trim(),h=g.indexOf("=");if(-1!=h&&"AMP_EXP"==decodeURIComponent(g.substring(0,h).trim())){e=decodeURIComponent(g.substring(h+1).trim());break c}}}e=null}e=a._experimentCookie=e?e.split(/\s*,\s*/g):[]}a=-1!=e.indexOf(d)?!0:a.AMP_CONFIG&&a.AMP_CONFIG.hasOwnProperty(d)?Math.random()<
a.AMP_CONFIG[d]:!1;a=c[b]=a}return a};var G,H="Webkit webkit Moz moz ms O o".split(" ");function I(a,b){for(var c in b){var d=a,e=b[c],f;f=d.style;var g=c;G||(G=Object.create(null));var h=G[g];if(!h){h=g;if(void 0===f[g]){var l;l=g;l=l.charAt(0).toUpperCase()+l.slice(1);a:{for(var E=0;E<H.length;E++){var U=H[E]+l;if(void 0!==f[U]){l=U;break a}}l=""}void 0!==f[l]&&(h=l)}G[g]=h}(f=h)&&(d.style[f]=e)}};function na(a,b){var c,d,e="form.amp-form-submit-error [submit-error],form.amp-form-submit-success [submit-success]{display:block}.-amp-validation-bubble{-webkit-transform:translate(-50%,-100%);transform:translate(-50%,-100%);background-color:#fff;box-shadow:0 5px 15px 0 rgba(0,0,0,.5);max-width:200px;position:absolute;display:none;box-sizing:border-box;padding:10px;border-radius:5px}.-amp-validation-bubble:after{content:' ';position:absolute;bottom:-8px;left:30px;width:0;height:0;border-left:8px solid transparent;border-right:8px solid transparent;border-top:8px solid #fff}[visible-when-invalid]{display:none;color:red}[visible-when-invalid].visible{display:initial}\n/*# sourceURL=/extensions/amp-form/0.1/amp-form.css*/",
f=oa(a,a.head,e,c||!1,d||null);if(J(a,f))b();else var g=setInterval(function(){J(a,f)&&(clearInterval(g),b())},4)}function oa(a,b,c,d,e){a=a.createElement("style");a.textContent=c;var f=null;d?(a.setAttribute("amp-runtime",""),b.runtimeStyleElement=a):"amp-custom"==e?(a.setAttribute("amp-custom",""),f=b.lastChild):(a.setAttribute("amp-extension",e||""),f=b.runtimeStyleElement);c=b;var g=f;g?g.nextSibling?c.insertBefore(a,g.nextSibling):c.appendChild(a):c.insertBefore(a,c.firstChild);return a}
function J(a,b){var c=a.styleSheets;for(a=0;a<c.length;a++){var d=c[a];if(d.ownerNode==b)return!0}return!1};function pa(a){return"loading"!=a.readyState&&"uninitialized"!=a.readyState}function qa(a,b){ra(a,b)}function ra(a,b){var c=pa,d=c(a);if(d)b(a);else{var e=function(){c(a)&&(d||(d=!0,b(a)),a.removeEventListener("readystatechange",e))};a.addEventListener("readystatechange",e)}};function K(a,b){var c=void 0;ia(a).then(function(a){a&&a.triggerEvent(b,c)})};function L(a,b){this.w=b;this.J=v(a.document,"viewport");this.o=u(a,"vsync");this.v=null;this.u="";this.m=!1;this.f=a.document.createElement("div");this.f.classList.add("-amp-validation-bubble");this.f.__BUBBLE_OBJ=this;a.document.body.appendChild(this.f)}L.prototype.isActiveOn=function(a){return this.m&&a==this.v};L.prototype.hide=function(){this.m&&(this.m=!1,this.v=null,this.u="",this.o.run({measure:void 0,mutate:sa},{bubbleElement:this.f}))};
L.prototype.show=function(a,b){if(!this.isActiveOn(a)||b!=this.u){this.m=!0;this.v=a;this.u=b;var c={message:b,targetElement:a,bubbleElement:this.f,viewport:this.J,id:this.w};this.o.run({measure:ta,mutate:ua},c)}};function sa(a){a.bubbleElement.removeAttribute("aria-alert");a.bubbleElement.removeAttribute("role");for(var b=a.bubbleElement;b.firstChild;)b.removeChild(b.firstChild);I(a.bubbleElement,{display:"none"})}function ta(a){a.targetRect=a.viewport.getLayoutRect(a.targetElement)}
function ua(a){for(var b=a.bubbleElement;b.firstChild;)b.removeChild(b.firstChild);var c=a.bubbleElement.ownerDocument.createElement("div");c.id="bubble-message-"+a.id;c.textContent=a.message;a.bubbleElement.setAttribute("aria-labeledby",c.id);a.bubbleElement.setAttribute("role","alert");a.bubbleElement.setAttribute("aria-live","assertive");a.bubbleElement.appendChild(c);I(a.bubbleElement,{display:"block",top:a.targetRect.top-10+"px",left:a.targetRect.left+a.targetRect.width/2+"px"})};var M,va=0;function N(a){this.form=a;this.doc=a.ownerDocument}N.prototype.report=function(){};N.prototype.onBlur=function(){};N.prototype.onInput=function(){};function O(a){N.apply(this,arguments)}m(O,N);O.prototype.report=function(){this.form.reportValidity()};function P(a){N.call(this,a);a=this.doc.defaultView;var b="amp-validation-bubble-"+va++;this.j=new L(a,b)}m(P,N);
P.prototype.report=function(){for(var a=this.form.querySelectorAll("input,select,textarea"),b=0;b<a.length;b++)if(!a[b].checkValidity()){a[b].focus();this.j.show(a[b],a[b].validationMessage);break}};P.prototype.onBlur=function(){this.j.hide()};P.prototype.onInput=function(a){var b=a.target;this.j.isActiveOn(b)&&(b.checkValidity()?(b.removeAttribute("aria-invalid"),this.j.hide()):(b.setAttribute("aria-invalid","true"),this.j.show(b,b.validationMessage)))};
function Q(a){N.call(this,a);this.A={};this.l={}}m(Q,N);k=Q.prototype;k.reportInput=function(a){var b;a:{for(b in a.validity)if(a.validity[b])break a;b=null}var c=b;c&&this.showValidationFor(a,c)};k.hideAllValidations=function(){for(var a in this.l){var b=this.doc.getElementById(a);this.hideValidationFor(b)}};k.getValidationFor=function(a,b){if(!a.id)return null;a="[visible-when-invalid="+b+"]"+("[validation-for="+a.id+"]");void 0===this.A[a]&&(this.A[a]=this.doc.querySelector(a));return this.A[a]};
k.showValidationFor=function(a,b){var c=this.getValidationFor(a,b);c&&(c.textContent.trim()||(c.textContent=a.validationMessage),a.setAttribute("aria-invalid","true"),c.classList.add("visible"),this.l[a.id]=c)};k.hideValidationFor=function(a){var b=this.getVisibleValidationFor(a);b&&(a.removeAttribute("aria-invalid"),b.classList.remove("visible"),delete this.l[a.id])};k.getVisibleValidationFor=function(a){return a.id?this.l[a.id]:null};
k.shouldValidateOnInteraction=function(){throw Error("Not Implemented");};k.onInteraction=function(a){a=a.target;var b=this.shouldValidateOnInteraction(a);this.hideValidationFor(a);b&&!a.checkValidity()&&this.reportInput(a)};k.onBlur=function(a){this.onInteraction(a)};k.onInput=function(a){this.onInteraction(a)};function R(a){Q.apply(this,arguments)}m(R,Q);
R.prototype.report=function(){this.hideAllValidations();for(var a=this.form.querySelectorAll("input,select,textarea"),b=0;b<a.length;b++)if(!a[b].checkValidity()){this.reportInput(a[b]);a[b].focus();break}};R.prototype.shouldValidateOnInteraction=function(a){return!!this.getVisibleValidationFor(a)};function S(a){Q.apply(this,arguments)}m(S,Q);
S.prototype.report=function(){this.hideAllValidations();for(var a=null,b=this.form.querySelectorAll("input,select,textarea"),c=0;c<b.length;c++)b[c].checkValidity()||(a=a||b[c],this.reportInput(b[c]));a&&a.focus()};S.prototype.shouldValidateOnInteraction=function(a){return!!this.getVisibleValidationFor(a)};function T(a){Q.apply(this,arguments)}m(T,Q);T.prototype.shouldValidateOnInteraction=function(){return!0};
function wa(a){if(F(a.ownerDocument.defaultView,"amp-form-custom-validations")){var b=a.getAttribute("custom-validation-reporting");switch(b){case "as-you-go":return new T(a);case "show-all-on-submit":return new S(a);case "show-first-on-submit":return new R(a)}}void 0===M&&(M=!!a.ownerDocument.createElement("form").reportValidity);return M?new O(a):new P(a)};function V(a,b){this.w=b;this.b=a.ownerDocument.defaultView;this.I=u(this.b,"timer");a:{b=this.b.document;if(b.nodeType){var c=(b.ownerDocument||b).defaultView;if(c=c!=(c.__AMP_TOP||c)&&c.services&&c.services["url-replace"]&&c.services["url-replace"].obj?c.services["url-replace"].obj:null){b=c;break a}}b=v(b,"url-replace")}this.D=b;this.a=a;this.o=u(this.b,"vsync");this.H=u(this.b,"templates");this.K=u(this.b,"xhr");this.s=v(this.b.document.documentElement,"action");this.g=(this.a.getAttribute("method")||
"GET").toUpperCase();this.L=this.a.getAttribute("target");if(this.c=this.a.getAttribute("action-xhr"))a=this.c,b=this.a,c="action-xhr",c=void 0===c?"source":c,q().assert(null!=a,"%s %s must be available",b,c),q().assert(la(a)||/^(\/\/)/.test(a),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,a),q().assert(!ma(this.c),"form action-xhr should not be on AMP CDN: %s",this.a);this.C=!this.a.hasAttribute("novalidate");this.a.setAttribute("novalidate",
"");this.C||this.a.setAttribute("amp-novalidate","");this.a.classList.add("-amp-form");var d=this.a.querySelectorAll('[type="submit"]');this.G=n(d);this.h=null;a=this.a.elements;for(b=0;b<a.length;b++)q().assert(!a[b].name||"__amp_source_origin"!=a[b].name,"Illegal input name, %s found: %s","__amp_source_origin",a[b]);this.B=wa(this.a);this.s.installActionHandler(this.a,this.F.bind(this));xa(this)}V.prototype.F=function(a){"submit"==a.method&&W(this)};
function xa(a){a.a.addEventListener("submit",function(b){return W(a,b)},!0);a.a.addEventListener("blur",function(b){X(b.target,!0);a.B.onBlur(b)},!0);a.a.addEventListener("input",function(b){X(b.target,!0);a.B.onInput(b)})}
function W(a,b){if("submitting"==a.h)b&&(b.stopImmediatePropagation(),b.preventDefault());else{var c=ya(a.a);if(a.C&&!c)b&&(b.stopImmediatePropagation(),b.preventDefault()),a.o.run({measure:void 0,mutate:za},{validator:a.B});else{var d=F(a.b,"amp-form-var-sub"),e=d?a.a.querySelectorAll('[type="hidden"][default-value]'):[];if(a.c){b&&b.preventDefault();Aa(a);Y(a,"submitting");var f="GET"==a.g||"HEAD"==a.g,g=[];for(b={i:0};b.i<e.length;b={i:b.i},b.i++){var h=e[b.i].getAttribute("default-value");g.push(a.D.expandStringAsync(h).then(function(a){return function(b){e[a.i].value=
b}}(b)))}Ba(a,g).then(function(){var b,c;f?b=ka(a.c,Ca(a)):(b=a.c,c=new FormData(a.a));return a.K.fetchJson(b,{body:c,method:a.g,credentials:"include",requireAmpResponseSourceOrigin:!0}).then(function(b){a.s.trigger(a.a,"submit-success",null);K(a.b,"amp-form-submit-success");Y(a,"submit-success");Z(a,b||{})}).catch(function(b){a.s.trigger(a.a,"submit-error",null);K(a.b,"amp-form-submit-error");Y(a,"submit-error");Z(a,b.responseJson||{});ba("Form submission failed:",b)})})}else if("POST"==a.g)b&&b.preventDefault(),
q().assert(!1,"Only XHR based (via action-xhr attribute) submissions are support for POST requests. %s",a.a);else if("GET"==a.g)for(b=0;b<e.length;b++){var l=e[b].getAttribute("default-value");e[b].value=a.D.expandStringSync(l)}}}}function Ba(a,b){var c=100;return Promise.race([Promise.all(b),a.I.promise(c)])}
function Ca(a){var b={};a=a.a.elements;for(var c=/^(?:input|select|textarea)$/i,d=/^(?:button|image|file|reset)$/i,e=/^(?:checkbox|radio)$/i,f=0;f<a.length;f++){var g=a[f],h;if(h=g.name){a:if(g.disabled)h=!0;else{h=t(g);for(var l=0;l<h.length;l++)if(h[l].disabled){h=!0;break a}h=!1}h=!h}!h||!c.test(g.tagName)||d.test(g.type)||e.test(g.type)&&!g.checked||(void 0===b[g.name]&&(b[g.name]=[]),b[g.name].push(g.value))}return b}
function Y(a,b){var c=a.h;a.a.classList.remove("amp-form-"+c);a.a.classList.add("amp-form-"+b);a.h=b;a.G.forEach(function(a){"submitting"==b?a.setAttribute("disabled",""):a.removeAttribute("disabled")})}
function Z(a,b){var c=a.a.querySelector("["+a.h+"]");if(c){var d="rendered-message-"+a.w;c.setAttribute("role","alert");c.setAttribute("aria-labeledby",d);c.setAttribute("aria-live","assertive");a.H.findAndRenderTemplate(c,b).then(function(a){a.id=d;a.setAttribute("i-amp-rendered","");c.appendChild(a)})}}function Aa(a){if(a=a.a.querySelector("["+a.h+"]")){var b=ga(a);b&&(a=b,a.parentElement&&a.parentElement.removeChild(a))}}function za(a){a.validator.report()}
function ya(a){for(var b=a.querySelectorAll("input,select,textarea,fieldset"),c=0;c<b.length;c++)X(b[c]);return X(a)}
function X(a,b){b=void 0===b?!1:b;var c=!1,d=a.classList.contains("user-valid")?"valid":a.classList.contains("user-invalid")?"invalid":"none",e=a.checkValidity();"valid"!=d&&e?(a.classList.add("user-valid"),a.classList.remove("user-invalid"),c="invalid"==d):"invalid"==d||e||(a.classList.add("user-invalid"),a.classList.remove("user-valid"),c=!0);if(a.validity)for(var f in a.validity)a.classList.toggle(f,a.validity[f]);if(b&&c){f=t(a);for(var g=0;g<f.length;g++)X(f[g]);a.form&&X(a.form)}return e}
function Da(a){qa(a.document,function(a){n(a.forms).forEach(function(a,b){new V(a,"amp-form-"+b)})})}(function(a){return w(a,"amp-form",function(){na(a.document,function(){Da(a)});return{}})})(AMP.win);
})});
//# sourceMappingURL=amp-form-0.1.js.map

