(self.AMP = self.AMP || []).push({n:"amp-font", f:(function(AMP) {function l(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var f=Object.getOwnPropertyDescriptor(b,d);f&&Object.defineProperty(a,d,f)}else a[d]=b[d]};Date.now();self.log=self.log||{user:null,dev:null};var m=self.log;function n(){if(m.user)return m.user;throw Error("failed to call initLogConstructor");};function p(a,b){a=a.__AMP_TOP||a;var c=a.services&&a.services[b]&&a.services[b].obj;return c};var r,t="Webkit webkit Moz moz ms O o".split(" ");function u(a,b){for(var c in b){var d=a,f=b[c],g;g=d.style;var h=c;r||(r=Object.create(null));var k=r[h];if(!k){k=h;if(void 0===g[h]){var e;e=h;e=e.charAt(0).toUpperCase()+e.slice(1);a:{for(var q=0;q<t.length;q++){var w=t[q]+e;if(void 0!==g[w]){e=w;break a}}e=""}void 0!==g[e]&&(k=e)}r[h]=k}(g=k)&&(d.style[g]=f)}};var v=["sans-serif","serif"];function x(a){this.s=a;this.a=a.document;this.f=this.g=this.c=null;this.l=this.m=!1;this.b=null}x.prototype.load=function(a,b){var c=this;this.b=a;return p(this.s,"timer").timeoutPromise(b,y(this)).then(function(){c.m=!0;c.h()},function(a){c.l=!0;c.h();throw a;})};
function y(a){return new Promise(function(b,c){var d=a.b.style+" "+a.b.variant+" "+a.b.weight+" "+a.b.size+" '"+a.b.family+"'";"fonts"in a.a?a.a.fonts.check(d)?b():a.a.fonts.load(d).then(function(){return a.a.fonts.load(d)}).then(function(){a.a.fonts.check(d)?b():c(Error("Font could not be loaded, probably due to incorrect @font-face."))}).catch(c):z(a).then(b,c)})}
function z(a){return new Promise(function(b,c){var d=p(a.s,"vsync");A(a);var f=d.createTask({measure:function(){a.m?b():a.l?c(Error("Font loading timed out.")):B(a)?b():f()}});f()})}
function A(a){var b=a.c=a.a.createElement("div");u(b,{fontSize:"40px",fontVariant:a.b.variant,fontWeight:a.b.weight,fontStyle:a.b.style,left:"-999px",lineHeight:"normal",margin:0,padding:0,position:"absolute",top:"-999px",visibility:"hidden"});a.g=[];v.forEach(function(c){var d=a.a.createElement("div");a.g.push(d);d.textContent="MAxmTYklsjo190QW";u(d,{fontFamily:c,margin:0,padding:0,whiteSpace:"nowrap"});b.appendChild(d)});var c=a.f=a.a.createElement("div");u(c,{fontFamily:a.b.family+","+v.join(),
margin:0,padding:0,whiteSpace:"nowrap"});c.textContent="MAxmTYklsjo190QW";b.appendChild(c);a.a.body.appendChild(b)}function B(a){return a.g.some(function(b){var c=2<Math.abs(b.offsetWidth-a.f.offsetWidth),d=2<Math.abs(b.offsetHeight-a.f.offsetHeight);return c||d})}x.prototype.h=function(){if(this.c){var a=this.c;a.parentElement&&a.parentElement.removeChild(a)}this.f=this.g=this.c=null};function C(a){AMP.BaseElement.apply(this,arguments)}l(C,AMP.BaseElement);C.prototype.prerenderAllowed=function(){return!0};
C.prototype.buildCallback=function(){this.j=n().assert(this.element.getAttribute("font-family"),"The font-family attribute is required for <amp-font> %s",this.element);this.w=this.element.getAttribute("font-weight")||"400";this.u=this.element.getAttribute("font-style")||"normal";this.v=this.element.getAttribute("font-variant")||"normal";this.a=this.win.document;this.i=this.a.documentElement;this.o=new x(this.win);D(this)};
function D(a){a.o.load({style:a.u,variant:a.v,weight:a.w,size:"medium",family:a.j},E(a)).then(function(){var b=a.element.getAttribute("on-load-add-class"),c=a.element.getAttribute("on-load-remove-class");F(a,b,c)}).catch(function(){var b=a.element.getAttribute("on-error-add-class"),c=a.element.getAttribute("on-error-remove-class");F(a,b,c);n().warn("amp-font","Font download timed out for "+a.j)})}
function F(a,b,c){b&&a.i.classList.add(b);c&&(a.i.classList.remove(c),a.a.body.classList.remove(c));a.h()}C.prototype.h=function(){this.o=null};function E(a){var b=parseInt(a.element.getAttribute("timeout"),10),c=b,b="number"!==typeof c||!isFinite(c)||0>b?3E3:b;return b=Math.max(b-p(a.win,"timer").timeSinceStart(),100)}AMP.registerElement("amp-font",C);
})});
//# sourceMappingURL=amp-font-0.1.js.map

