(self.AMP = self.AMP || []).push({n:"amp-facebook", f:(function(AMP) {function h(a,d){function b(){}b.prototype=d.prototype;a.prototype=new b;a.prototype.constructor=a;for(var c in d)if(Object.defineProperties){var f=Object.getOwnPropertyDescriptor(d,c);f&&Object.defineProperty(a,c,f)}else a[c]=d[c]}var u="";
function v(){var a=void 0,d=a||self,b;if(d.AMP_MODE)b=d.AMP_MODE;else{b=d;if(b.context&&b.context.mode)b=b.context.mode;else{var c=w(b.location.originalHash||b.location.hash),f=w(b.location.search);u||(u=b.AMP_CONFIG&&b.AMP_CONFIG.v?b.AMP_CONFIG.v:"011481320064935");b={localDev:!1,development:!("1"!=c.development&&!b.AMP_DEV_MODE),filter:c.filter,minified:!0,lite:void 0!=f.amp_lite,test:!1,log:c.log,version:"1481320064935",rtvVersion:u}}b=d.AMP_MODE=b}return b}
function w(a){var d=Object.create(null);if(!a)return d;if(0==a.indexOf("?")||0==a.indexOf("#"))a=a.substr(1);for(var b=a.split("&"),c=0;c<b.length;c++){var f=b[c],e=f.indexOf("="),g,l;-1!=e?(g=decodeURIComponent(f.substring(0,e)).trim(),l=decodeURIComponent(f.substring(e+1)).trim()):(g=decodeURIComponent(f).trim(),l="");g&&(d[g]=l)}return d};Date.now();self.log=self.log||{user:null,dev:null};var x=self.log;function A(){if(x.user)return x.user;throw Error("failed to call initLogConstructor");};function B(a,d){var b=a;if(b.nodeType){var c=(b.ownerDocument||b).defaultView,f=c=c.__AMP_TOP||c,e=c.services;e||(e=c.services={});c=e;(e=c.ampdoc)||(e=c.ampdoc={obj:null,promise:null,resolve:null});e.obj||(e.obj=(void 0)(f),e.resolve&&e.resolve(e.obj));b=e.obj.getAmpDoc(b)}var g=b.isSingleDoc()?b.win:b;return g&&g.services&&g.services[d]&&g.services[d].obj};function G(a){return a.replace(/-([a-z])/g,function(a,b){return b.toUpperCase()})};var H=self.AMP_CONFIG||{},I=H.thirdPartyUrl||"https://3p.ampproject.net",K=H.thirdPartyFrameHost||"ampproject.net";var L,M;
function N(a){var d;L||(L=self.document.createElement("a"),M=self.UrlCache||(self.UrlCache=Object.create(null)));var b=M[a];if(b)return b;L.href=a;L.protocol||(L.href=L.href);var c={href:L.href,protocol:L.protocol,host:L.host,hostname:L.hostname,port:"0"==L.port?"":L.port,pathname:L.pathname,search:L.search,hash:L.hash,origin:null};"/"!==c.pathname[0]&&(c.pathname="/"+c.pathname);if("http:"==c.protocol&&80==c.port||"https:"==c.protocol&&443==c.port)c.port="",c.host=c.hostname;c.origin=L.origin&&"null"!=
L.origin?L.origin:"data:"!=c.protocol&&c.host?c.protocol+"//"+c.host:c.href;var f=c;return d?f:M[a]=f}function O(a){"string"==typeof a&&(a=N(a));var d;(d="https:"==a.protocol||"localhost"==a.hostname)||(a=a.hostname,d=a.length-10,d=0<=d&&a.indexOf(".localhost",d)==d);return d};function P(a){for(var d=a.nodeName,b=0,c=0,f=a.previousElementSibling;f&&25>c&&100>b;)f.nodeName==d&&c++,b++,f=f.previousElementSibling;return 25>c&&100>b?"."+c:""};var R,S="Webkit webkit Moz moz ms O o".split(" ");function T(a){var d,b=a.style;R||(R=Object.create(null));var c=R.border;if(!c){c="border";if(void 0===b.border){var f="B"+"border".slice(1);a:{for(var e=0;e<S.length;e++){var g=S[e]+f;if(void 0!==b[g]){f=g;break a}}f=""}void 0!==b[f]&&(c=f)}R.border=c}(b=c)&&(a.style[b]=d?"none"+d:"none")};function U(a){a=parseFloat(a);return"number"===typeof a&&isFinite(a)?a:void 0};var V={};
function aa(a,d){var b=Date.now(),c=d.getAttribute("width"),f=d.getAttribute("height");A().assert("facebook","Attribute type required for <amp-ad>: %s",d);for(var e={},g=0;g<d.attributes.length;g++){var l=d.attributes[g];0==l.name.indexOf("data-")&&(e[G(l.name.substr(5))]=l.value)}if(g=d.getAttribute("json")){var n;a:{try{n=JSON.parse(g);break a}catch(ha){}n=void 0}if(void 0===n)throw A().createError("Error parsing JSON in json attribute in element %s",d);for(var p in n)e[p]=n[p]}e.width=U(c);e.height=
U(f);e.type="facebook";var q=B(d,"documentInfo").get(),r=B(d,"viewer"),m=a.location.href;"about:srcdoc"==m&&(m=a.parent.location.href);c=r.getUnconfirmedReferrerUrl();f=q.canonicalUrl;p=q.sourceUrl;n=q.pageViewId;for(var g={href:m},l=d.tagName,C={localDev:!1,development:v().development,filter:v().filter,minified:!0,lite:v().lite,test:!1,log:v().log,version:v().version,rtvVersion:v().rtvVersion},t=!(!a.AMP_CONFIG||!a.AMP_CONFIG.canary),J=!r.isVisible(),D=a,E=0,k=D;k&&k!=k.parent;k=k.parent)E++;for(var D=
String(E)+"-"+W(D),E=d.getIntersectionChangeEntry(),k=d,F=[],y=0;k&&1==k.nodeType&&25>y;){var z="";k.id&&(z="/"+k.id);var ba=k.nodeName.toLowerCase();F.push(""+ba+z+P(k));y++;k=k.parentElement}k=F.join();F=k.length;y=5381;for(z=0;z<F;z++)y=33*y^k.charCodeAt(z);e._context={referrer:c,canonicalUrl:f,sourceUrl:p,pageViewId:n,location:g,tagName:l,mode:C,canary:t,hidden:J,amp3pSentinel:D,initialIntersection:E,domFingerprint:String(y>>>0),startTime:b};Object.assign(e._context,void 0);var Q=d.getAttribute("src");
Q&&(e.src=Q);return e}function ca(a,d){var b=aa(a,d),c=a.document.createElement("iframe");V[b.type]||(V[b.type]=0);a=X(a);var f=N(a).hostname;a=a+"#"+JSON.stringify(b);var e=f+"_"+b.type+"_"+V[b.type]++;c.src=a;c.name=e;c.ampLocation=N(a);c.width=b.width;c.height=b.height;c.setAttribute("scrolling","no");T(c);c.onload=function(){this.readyState="complete"};c.setAttribute("data-amp-3p-sentinel",b._context.amp3pSentinel);return c}
function X(a){var d,b=a.bootstrapBaseUrl;if(b)a=b;else{var c;c=d;var f=a.document.querySelector('meta[name="amp-3p-iframe-src"]');if(f){var e=f.getAttribute("content"),g;g=void 0===g?"source":g;A().assert(null!=e,"%s %s must be available",f,g);A().assert(O(e)||/^(\/\/)/.test(e),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',f,g,e);A().assert(-1==e.indexOf("?"),"3p iframe url must not include query string %s in element %s.",
e,f);g=N(e);A().assert("localhost"==g.hostname&&!c||g.origin!=N(a.location.href).origin,"3p iframe url must not be on the same origin as the current document %s (%s) in element %s. See https://github.com/ampproject/amphtml/blob/master/spec/amp-iframe-origin-policy.md for details.",e,g.origin,f);c=e+"?1481320064935"}else c=null;c||(c="https://d-"+W(a)+("."+K+"/1481320064935/")+"frame.html");a=a.bootstrapBaseUrl=c}return a}
function W(a){var d;if(a.crypto&&a.crypto.getRandomValues){var b=new Uint32Array(2);a.crypto.getRandomValues(b);d=String(b[0])+b[1]}else d=String(a.Math.random()).substr(2)+"0";return d};function Y(a,d,b){var c=a.listeningFors;!c&&b&&(c=a.listeningFors=Object.create(null));a=c||null;if(!a)return a;var f=a[d];!f&&b&&(f=a[d]=[]);return f||null}function da(a,d){var b=!0,c=N(d.src).origin,f=b?d.getAttribute("data-amp-3p-sentinel"):"amp";a=Y(a,f,!0);for(var e,f=0;f<a.length;f++){var g=a[f];if(g.frame===d){e=g;break}}e||(e={frame:d,origin:c,events:Object.create(null)},a.push(e));return e.events}
function ea(a){for(var d={sentinel:"unlisten"},b=a.length-1;0<=b;b--){var c=a[b];if(!c.frame.contentWindow){a.splice(b,1);var f=c.events,e;for(e in f)f[e].splice(0,Infinity).forEach(function(a){a(d)})}}}
function fa(a){if(!a.listeningFors){var d=function(b){if(b.data){var c=b.data;if("string"===typeof c&&"{"===c.charAt(0))try{c=JSON.parse(c)}catch(J){var d;if(x.dev)d=x.dev;else throw Error("failed to call initLogConstructor");d.warn("IFRAME-HELPER","Postmessage could not be parsed. Is it in a valid JSON format?",J)}if(c.sentinel){var e;d=c.sentinel;var g=b.origin,l=b.source,n=Y(a,d);if(n){for(var p=0;p<n.length;p++){var q=n[p],r=q.frame.contentWindow;if(r)if("amp"===d){if(q.origin===g&&r==l){e=q;
break}}else{var m;if(!(m=l==r))b:{for(m=l;m&&m!=m.parent;m=m.parent)if(m==r){m=!0;break b}m=!1}if(m){e=q;break}}else setTimeout(ea,0,n)}e=e?e.events:null}else e=n;var C=e;if(C){var t=C[c.type];if(t)for(t=t.slice(),e=0;e<t.length;e++)(0,t[e])(c,b.source,b.origin)}}}};a.addEventListener("message",d)}}
function ga(a,d){function b(b,e,f){if(c||e==a.contentWindow)"unlisten"==b.sentinel?l():d(b,e,f)}var c,f="embed-size",e=a.ownerDocument.defaultView;fa(e);var e=da(e,a),g=e[f]||(e[f]=[]),l;g.push(b);l=function(){if(b){var a=g.indexOf(b);-1<a&&g.splice(a,1);d=g=b=null}}};function Z(a){AMP.BaseElement.call(this,a);this.a=null}h(Z,AMP.BaseElement);Z.prototype.preconnectCallback=function(a){this.preconnect.url("https://facebook.com",a);this.preconnect.preload("https://connect.facebook.net/en_US/sdk.js","script");var d=this.preconnect,b=X(this.win);d.preload(b,"document");d.preload(I+"/1481320064935/f.js","script")};Z.prototype.isLayoutSupported=function(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a};
Z.prototype.layoutCallback=function(){var a=this,d=ca(this.win,this.element);this.applyFillContent(d);ga(d,function(b){a.changeHeight(b.height)});this.element.appendChild(d);this.a=d;return this.loadPromise(d)};Z.prototype.unlayoutOnPause=function(){return!0};Z.prototype.unlayoutCallback=function(){if(this.a){var a=this.a;a.parentElement&&a.parentElement.removeChild(a);this.a=null}return!0};AMP.registerElement("amp-facebook",Z);
})});
//# sourceMappingURL=amp-facebook-0.1.js.map

