(self.AMP = self.AMP || []).push({n:"amp-sidebar", f:(function(AMP) {function g(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var e in b)if(Object.defineProperties){var f=Object.getOwnPropertyDescriptor(b,e);f&&Object.defineProperty(a,e,f)}else a[e]=b[e]};Date.now();self.log=self.log||{user:null,dev:null};function h(a,b){for(var c,e=a;e&&e!==c;e=e.parentElement)if(b(e))return e;return null}function k(a){var b="A";if(a.closest)return a.closest(b);b=b.toUpperCase();return h(a,function(a){return a.tagName==b})};function l(a,b){a=a.__AMP_TOP||a;var c=a.services&&a.services[b]&&a.services[b].obj;return c}function n(a){var b=a;if(b.nodeType){var c=(b.ownerDocument||b).defaultView,e=c=c.__AMP_TOP||c,f=c.services;f||(f=c.services={});c=f;(f=c.ampdoc)||(f=c.ampdoc={obj:null,promise:null,resolve:null});f.obj||(f.obj=(void 0)(e),f.resolve&&f.resolve(f.obj));b=f.obj.getAmpDoc(b)}var d=b.isSingleDoc()?b.win:b;return d&&d.services&&d.services.history&&d.services.history.obj};var p,q;function r(a){var b=a.indexOf("#");return-1==b?a:a.substring(0,b)};var t,u="Webkit webkit Moz moz ms O o".split(" ");function v(a,b){var c=void 0;t||(t=Object.create(null));var e=t[b];if(!e||c){e=b;if(void 0===a[b]){var f=b.charAt(0).toUpperCase()+b.slice(1);a:{for(var d=0;d<u.length;d++){var w=u[d]+f;if(void 0!==a[w]){f=w;break a}}f=""}var m=f;void 0!==a[m]&&(e=m)}c||(t[b]=e)}return e}function x(a,b,c){var e;(b=v(a.style,b))&&(a.style[b]=e?c+e:c)}
function y(a,b){if(void 0===b){var c;c=(c=v(a.style,"display"))?a.style[c]:void 0;b="none"==c}x(a,"display",b?"":"none")};function z(a){AMP.BaseElement.call(this,a);this.l=null;this.m=l(this.win,"vsync");this.f=null;this.c=this.win.document;this.s=this.c.documentElement;this.g=null;var b=l(this.win,"platform");this.u=b.isIos()&&b.isSafari();this.h=-1;this.o=!1;this.j=l(this.win,"timer");this.b=null}g(z,AMP.BaseElement);z.prototype.isLayoutSupported=function(a){return"nodisplay"==a};
z.prototype.buildCallback=function(){var a=this;this.g=this.element.getAttribute("side");this.l=this.getViewport();this.l.addToFixedLayer(this.element,!0);if("left"!=this.g&&"right"!=this.g){var b=this.c.body.getAttribute("dir")||this.s.getAttribute("dir")||"ltr";this.g="rtl"==b?"right":"left";this.element.setAttribute("side",this.g)}this.u&&A(this);B(this)?this.i():this.element.setAttribute("aria-hidden","true");this.element.hasAttribute("role")||this.element.setAttribute("role","menu");this.element.tabIndex=
-1;this.s.addEventListener("keydown",function(b){27==b.keyCode&&a.a()});var c=this.c.createElement("button");c.textContent="Close the sidebar";c.classList.add("-amp-screen-reader");c.tabIndex=-1;c.addEventListener("click",function(){a.a()});this.element.appendChild(c);this.registerAction("toggle",this.v.bind(this));this.registerAction("open",this.i.bind(this));this.registerAction("close",this.a.bind(this));this.element.addEventListener("click",function(b){if((b=k(b.target))&&b.href){var c;c=b.href;
p||(p=self.document.createElement("a"),q=self.UrlCache||(self.UrlCache=Object.create(null)));var d=q[c];if(d)c=d;else{p.href=c;p.protocol||(p.href=p.href);d={href:p.href,protocol:p.protocol,host:p.host,hostname:p.hostname,port:"0"==p.port?"":p.port,pathname:p.pathname,search:p.search,hash:p.hash,origin:null};"/"!==d.pathname[0]&&(d.pathname="/"+d.pathname);if("http:"==d.protocol&&80==d.port||"https:"==d.protocol&&443==d.port)d.port="",d.host=d.hostname;d.origin=p.origin&&"null"!=p.origin?p.origin:
"data:"!=d.protocol&&d.host?d.protocol+"//"+d.host:d.href;c=q[c]=d}var e=c,m=a.getAmpDoc().win.location.href;r(b.href)==r(m)&&e.hash&&a.a()}},!0)};function B(a){return a.element.hasAttribute("open")}z.prototype.activate=function(){this.i()};z.prototype.v=function(){B(this)?this.a():this.i()};
z.prototype.i=function(){var a=this;B(this)||(this.l.disableTouchZoom(),this.m.mutate(function(){y(a.element,!0);C(a);a.u&&D(a);a.element.scrollTop=1;a.m.mutate(function(){a.element.setAttribute("open","");a.element.setAttribute("aria-hidden","false");try{a.element.focus()}catch(b){}a.b&&a.j.cancel(a.b);a.b=a.j.delay(function(){var b=a.getRealChildren();a.scheduleLayout(b);a.scheduleResume(b)},550)})}),n(this.getAmpDoc()).push(this.a.bind(this)).then(function(b){a.h=b}))};
z.prototype.a=function(){var a=this;B(this)&&(this.l.restoreOriginalTouchZoom(),this.m.mutate(function(){a.f&&y(a.f,!1);a.element.removeAttribute("open");a.element.setAttribute("aria-hidden","true");a.b&&a.j.cancel(a.b);a.b=a.j.delay(function(){B(a)||a.m.mutate(function(){y(a.element,!1);a.schedulePause(a.getRealChildren())})},550)}),-1!=this.h&&(n(this.getAmpDoc()).pop(this.h),this.h=-1))};
function C(a){if(!a.f){var b=a.c.createElement("div");b.classList.add("-amp-sidebar-mask");b.addEventListener("click",function(){a.a()});a.element.parentNode.appendChild(b);b.addEventListener("touchmove",function(a){a.preventDefault()});a.f=b}y(a.f,!0)}
function A(a){a.element.addEventListener("scroll",function(b){B(a)&&(1>a.element.scrollTop?(a.element.scrollTop=1,b.preventDefault()):a.element.scrollHeight==a.element.scrollTop+a.element.offsetHeight&&(--a.element.scrollTop,b.preventDefault()))})}function D(a){if(!a.o){var b=a.c.createElement("div"),c={height:"10vh",width:"100%","background-color":"transparent"},e;for(e in c)x(b,e,c[e]);a.element.appendChild(b);a.o=!0}}AMP.registerElement("amp-sidebar",z,"amp-sidebar{position:fixed!important;top:0;max-height:100vh!important;height:100vh;max-width:80vw!important;background-color:#efefef;min-width:45px!important;outline:none;overflow-x:hidden!important;overflow-y:auto!important;z-index:9999!important;-webkit-overflow-scrolling:touch;will-change:transform}amp-sidebar[side=left]{left:0!important;-webkit-transform:translateX(-100%)!important;transform:translateX(-100%)!important}amp-sidebar[side=right]{right:0!important;-webkit-transform:translateX(100%)!important;transform:translateX(100%)!important}amp-sidebar[side][open]{-webkit-transform:translateX(0)!important;transform:translateX(0)!important}amp-sidebar[side]{-webkit-transition:-webkit-transform 233ms cubic-bezier(0,0,.21,1);transition:-webkit-transform 233ms cubic-bezier(0,0,.21,1);transition:transform 233ms cubic-bezier(0,0,.21,1);transition:transform 233ms cubic-bezier(0,0,.21,1),-webkit-transform 233ms cubic-bezier(0,0,.21,1)}.-amp-sidebar-mask{position:fixed!important;top:0!important;left:0!important;width:100vw!important;height:100vh!important;opacity:0.2;background-image:none!important;background-color:#000;z-index:9998!important}\n/*# sourceURL=/extensions/amp-sidebar/0.1/amp-sidebar.css*/");
})});
//# sourceMappingURL=amp-sidebar-0.1.js.map

