<?php
/***BRAND REPLACE VARIABLE ARE AVAILABLE IN config('description.extended.replace')****/
return [
    'upcoming'                    => [
        'xiaomi'   => [
            'text'    => 'The {PRODUCT} is one of the most-awaited upcoming mobile phones of <a href=\'/xiaomi-mobiles-price-list-in-india-351\'>Xiaomi</a>. Powered by {PROCESSOR}, the handset is based on {OS}. The device is equipped with a {CAMERA} rear camera and a {FRONT_CAMERA} front camera. As far the memory, the smartphone has a {INTERNAL} of internal storage, paired with {RAM} of RAM. For battery backup, the mobile phone is armed with {BATTERY} of {BATTERY_TYPE} type.  Compare and buy {PRODUCT} online, get delivered anywhere in India.',
            'excerpt' => 'The {PRODUCT} is likely to go on sale from {DATE} at the expected price rate of {PRICE} INR. The internal storage of {INTERNAL} makes the smartphone one of the best {INTERNAL} Internal Memory mobiles in India. The handset is available in different unique colors including {COLOR}.',
            'keys'    => 'replace',
        ],
        'samsung'  => [
            'text'    => 'Loaded with an immense number of innovative features, the {PRODUCT} is another upcoming flagship of South Korean multinational company, <a href=\'/samsung-mobiles-price-list-in-india-351\'>Samsung</a>. Based on {OS}, the handset is powered by {PROCESSOR}, paired with {RAM} of RAM. Featuring {SCREEN_SIZE} inches of display, the device is armed with a {CAMERA} rear camera and a {FRONT_CAMERA} front camera. For storage, the mobile phone has got a {INTERNAL} of internal storage. Over that, smartphone is fuelled with a powerful {BATTERY} of {BATTERY_TYPE} type. Compare and buy {PRODUCT} online, get delivered anywhere in India.',
            'excerpt' => 'The {PRODUCT} is likely to go on sale from {DATE} at the expected price rate of {PRICE} INR. The internal storage of {INTERNAL} makes the smartphone one of the best {INTERNAL} Internal Memory mobiles in India. The handset is available in different unique colors including {COLOR}.',
            'keys'    => 'replace',
        ],
        'huawei'   => [
            'text'    => 'Equipped with a comprehensive range of advanced features, the {PRODUCT} is another upcoming mobile phone by <a href=\'/huawei-mobiles-price-list-in-india-351\'>Huawei</a>. The handset is based on {OS}, paired with {PROCESSOR}. Flaunting {SCREEN_SIZE} inches of display, the mobile phone has a {CAMERA} rear camera and a {FRONT_CAMERA} front camera. For storage, the mobile phone comes with a {INTERNAL} of internal storage, combined with {RAM} of RAM. Beyond all, the device is supported by a powerful battery backup of {BATTERY} of {BATTERY_TYPE} type. Compare and buy {PRODUCT} online and get delivered anywhere in India.',
            'excerpt' => 'The {PRODUCT} is likely to go on sale from {DATE} at the expected price rate of {PRICE} INR. The internal storage of {INTERNAL} makes the smartphone one of the best {INTERNAL} Internal Memory mobiles in India. The handset is available in different unique colors including {COLOR}.',
            'keys'    => 'replace',
        ],
        'micromax' => [
            'text'    => 'The {PRODUCT} is soon-to-be available in the Indian mobile market. Manufactured and designed by <a href=\'/micromax-mobiles-price-list-in-india-351\'>Micromax</a>, the handset is powered by {PROCESSOR} and runs on {OS}. For photography, the smartphone got a {CAMERA} rear camera and a {FRONT_CAMERA} front camera for taking selfies. Besides, the device has a {INTERNAL} of internal storage, combined with {RAM} of RAM. Over that, the mobile phone is supported by {BATTERY} of {BATTERY_TYPE} type.  Compare and buy {PRODUCT} online at economical prices and get delivered anywhere in India.',
            'excerpt' => 'The {PRODUCT} is likely to go on sale from {DATE} at the expected price rate of {PRICE} INR. The internal storage of {INTERNAL} makes the smartphone one of the best {INTERNAL} Internal Memory mobiles in India. The handset is available in different unique colors including {COLOR}.',
            'keys'    => 'replace',
        ],
        'intex'    => [
            'text'    => 'Manufactured by <a href=\'/intex-mobiles-price-list-in-india-351\'>Intex</a>, the {PRODUCT} is another upcoming masterpiece by one of India’s largest mobile manufacturer companies. The handset is powered by {PROCESSOR} and runs on {OS}, clubbed with {RAM} of RAM. For photography, the device is equipped with a {CAMERA} rear camera and a {FRONT_CAMERA} front camera for taking selfies. On storage front, the mobile phone has a {INTERNAL} GB of internal storage. Moreover, the smartphone is supported by {BATTERY} of {BATTERY_TYPE} type. Compare and buy {PRODUCT} online at reasonable prices and get delivered anywhere in India.',
            'excerpt' => 'The {PRODUCT} is likely to go on sale from {DATE} at the expected price rate of {PRICE} INR. The internal storage of {INTERNAL} makes the smartphone one of the best {INTERNAL} Internal Memory mobiles in India. The handset is available in different unique colors including {COLOR}.',
            'keys'    => 'replace',
        ],
        'karbonn'  => [
            'text'    => 'The {PRODUCT} is another power-packed upcoming mobile phone, manufactured by one of the leading mobile manufacture company, <a href=\'/karbonn-mobiles-price-list-in-india-351\'>Karbonn</a>. Based on {OS}, the smartphone is powered by {PROCESSOR}, paired with {RAM} of RAM. For taking pictures, the handset has got a {CAMERA} rear camera and a {FRONT_CAMERA} front camera. Besides, the device has a {INTERNAL} GB of internal storage. Over that, the mobile phone is backed by {BATTERY} of {BATTERY_TYPE} type. Compare and buy {PRODUCT} online at best prices and get delivered anywhere in India.',
            'excerpt' => 'The {PRODUCT} is likely to go on sale from {DATE} at the expected price rate of {PRICE} INR. The internal storage of {INTERNAL} makes the smartphone one of the best {INTERNAL} Internal Memory mobiles in India. The handset is available in different unique colors including {COLOR}.',
            'keys'    => 'replace',
        ],
        'motorola' => [
            'text'    => 'Packed with quality features, the {PRODUCT} is one of the upcoming mobile phones of an American telecommunication company, <a href=\'/motorola-mobiles-price-list-in-india-351\'>Motorola</a>. The device is based on {OS} and is powered by {PROCESSOR}, paired with {RAM} of RAM. For photography, the mobile phone has a {CAMERA} rear camera and a {FRONT_CAMERA} front camera for selfies. Over that, the smartphone comes with a {INTERNAL} of internal storage. In addition, the mobile phone is supported by {BATTERY} of {BATTERY_TYPE} type. Compare and buy {PRODUCT} online at best prices and get delivered anywhere in India.',
            'excerpt' => 'The {PRODUCT} is likely to go on sale from {DATE} at the expected price rate of {PRICE} INR. The internal storage of {INTERNAL} makes the smartphone one of the best {INTERNAL} Internal Memory mobiles in India. The handset is available in different unique colors including {COLOR}.',
            'keys'    => 'replace',
        ],
        'lg'       => [
            'text'    => '{PRODUCT} is the blend of innovation and technology, manufactured by world-renewed South Korean multinational Company, <a href=\'/lg-mobiles-price-list-in-india-351\'>LG</a>. Powered by {PROCESSOR}, the device is based on {OS}. For photography, the mobile handset has a {CAMERA} rear camera and a {FRONT_CAMERA} front camera for selfies. Besides, the mobile phone comes with a {INTERNAL} of internal storage, paired with {RAM} of RAM. In addition, the smartphone is backed by {BATTERY} of {BATTERY_TYPE} type. Compare and buy {PRODUCT} online at best prices and get delivered anywhere in India.',
            'excerpt' => 'The {PRODUCT} is likely to go on sale from {DATE} at the expected price rate of {PRICE} INR. The internal storage of {INTERNAL} makes the smartphone one of the best {INTERNAL} Internal Memory mobiles in India. The handset is available in different unique colors including {COLOR}.',
            'keys'    => 'replace',
        ],
        'nokia'    => [
            'text'    => 'An eminent telecommunication company, <a href=\'/nokia-mobiles-price-list-in-india-351\'>Nokia</a> is yet again coming up with highly-featured smartphone called {PRODUCT}. The mobile phone is based on {OS} and is powered by {PROCESSOR}, paired with {RAM} of RAM. For pictures, the device is equipped with a {CAMERA} rear camera and a {FRONT_CAMERA} front camera. Besides, the handset has a {INTERNAL} of internal storage. Above all, the mobile device is fuelled with {BATTERY} of {BATTERY_TYPE} type. Compare and buy {PRODUCT} online at best prices and get delivered anywhere in India.',
            'excerpt' => 'The {PRODUCT} is likely to go on sale from {DATE} at the expected price rate of {PRICE} INR. The internal storage of {INTERNAL} makes the smartphone one of the best {INTERNAL} Internal Memory mobiles in India. The handset is available in different unique colors including {COLOR}.',
            'keys'    => 'replace',
        ],
        'lenovo'   => [
            'text'    => 'A Chinese multinational company, <a href=\'/lenovo-mobiles-price-list-in-india-351\'>Lenovo</a> is bringing a new smartphone, {PRODUCT} which is loaded with quality features with elegant design. Based on {OS}, the mobile device is powered by {PROCESSOR}.  For pictures, users can make use of a {CAMERA} rear camera and a {FRONT_CAMERA} front camera for taking selfies. Further, the mobile phone has a {INTERNAL} of internal storage, packed with a {RAM} of RAM. Besides, the handset is supported by {BATTERY} of {BATTERY_TYPE} type. Compare and buy {PRODUCT} online at best prices and get delivered anywhere in India.',
            'excerpt' => 'The {PRODUCT} is likely to go on sale from {DATE} at the expected price rate of {PRICE} INR. The internal storage of {INTERNAL} makes the smartphone one of the best {INTERNAL} Internal Memory mobiles in India. The handset is available in different unique colors including {COLOR}.',
            'keys'    => 'replace',
        ],
        'asus'     => [
            'text'    => '{PRODUCT} is upcoming mobile phone, manufactured and developed by Taiwanese multinational company, <a href=\'/asus-mobiles-price-list-in-india-351\'>Asus</a>. Based on {OS}, the smartphone is powered by {PROCESSOR}. On photography front, the device is equipped with a {CAMERA} rear camera and a {FRONT_CAMERA} front camera for selfies. Over that, the device comes with a {INTERNAL} of internal storage, paired with {RAM} of RAM. Besides, the mobile device is backed by {BATTERY} of {BATTERY_TYPE} type. Compare and buy {PRODUCT} online at best prices and get delivered anywhere in India.',
            'excerpt' => 'The {PRODUCT} is likely to go on sale from {DATE} at the expected price rate of {PRICE} INR. The internal storage of {INTERNAL} makes the smartphone one of the best {INTERNAL} Internal Memory mobiles in India. The handset is available in different unique colors including {COLOR}.',
            'keys'    => 'replace',
        ],
        'htc'      => [
            'text'    => 'A Taiwanese multinational company, <a href=\'/htc-mobiles-price-list-in-india-351\'>HTC</a> is coming up with another innovative smartphone {PRODUCT}. The handset is based on {OS} and powered by {PROCESSOR}. For photography, users can make use of a {CAMERA} rear camera and get the best shots clicked. And for selfie lovers, the device has got a {FRONT_CAMERA} front camera. Besides, the mobile device comes with a {INTERNAL} of internal storage, paired with {RAM} of RAM. Furthermore, the mobile phone is backed by {BATTERY} of {BATTERY_TYPE} type. Compare and buy {PRODUCT} online at best prices and get delivered anywhere in India.',
            'excerpt' => 'The {PRODUCT} is likely to go on sale from {DATE} at the expected price rate of {PRICE} INR. The internal storage of {INTERNAL} makes the smartphone one of the best {INTERNAL} Internal Memory mobiles in India. The handset is available in different unique colors including {COLOR}.',
            'keys'    => 'replace',
        ],
        'vivo'     => [
            'text'    => 'In the list of remarkable smartphones, <a href=\'/vivo-mobiles-price-list-in-india-351\'>Vivo</a> will soon add another upcoming mobile phone {PRODUCT} with the latest features. The phone will consist of the screen size of {SCREEN_SIZE} inches, combined with the {RAM} RAM for efficient functioning. To capture beautiful moments, the handset will offer the primary camera of {CAMERA} and the front shooter of {FRONT_CAMERA}. The {PRODUCT} will be powered by the {PROCESSOR} and the {OS}. In addition, the device will have {BATTERY}. Furthermore, the cell phone will provide {INTERNAL} on-board storage to store the valuable data. Compare and buy {PRODUCT} online at best prices and get delivered anywhere in India.',
            'excerpt' => 'The {PRODUCT} is likely to go on sale from {DATE} at the expected price rate of {PRICE} INR. The internal storage of {INTERNAL} makes the smartphone one of the best {INTERNAL} Internal Memory mobiles in India. The handset is available in different unique colors including {COLOR}.',
            'keys'    => 'replace',
        ],

    ],
    \indiashopps\Category::MOBILE => [
        'xiaomi'   => [
            'text'    => 'The {PRODUCT} is powered by {PROCESSOR}, combined with {RAM} of RAM. The device runs on {OS}. Equipped with a {CAMERA} rear camera and a {FRONT_CAMERA} front-facing camera. The handset is backed with a {BATTERY}. Featuring a {SCREEN_SIZE}-inch display, the mobile phone has got a {INTERNAL} internal storage space. This device is one of the best <a href=\'/mobile/android-phones\'>Android mobiles</a>, manufactured by <a href=\'/xiaomi-mobiles-price-list-in-india-351\'>Xiaomi</a> at the price tag {PRICE}. Compare and buy {PRODUCT} online and get delivered anywhere in India including metro cities like Delhi, Mumbai, Pune, Bangalore etc.',
            'excerpt' => '{PRODUCT} price in India is latest updated on {DATE} and is available at the lowest price rate of {PRICE} INR from {VENDOR}. The internal storage of {INTERNAL} makes the smartphone one of the best {INTERNAL} Internal Memory mobiles in India. The handset is available in different unique colors including {COLOR}.',
            'keys'    => 'replace',
        ],
        'samsung'  => [
            'text'    => 'Like other devices of Samsung, {PRODUCT} is another masterwork that defines true value for money. Powered by {PROCESSOR}, the device runs on {OS}, paired with {RAM} of RAM. For photography, the handset has a {CAMERA} rear camera and a {FRONT_CAMERA} front-facing camera. Flaunting a {SCREEN_SIZE}-inch display, the smartphone comes with a {INTERNAL} of internal storage space. Above all, the device is supported with a powerful battery backup of {BATTERY}. This device is one of the best <a href=\'/mobile/android-phones\'>Android mobiles</a>, manufactured by <a href=\'/samsung-mobiles-price-list-in-india-351\'>Samsung</a> at the price tag of {PRICE}. Compare and buy {PRODUCT} online, get delivered anywhere in India including metro cities like Delhi, Mumbai, Pune, Bangalore etc.',
            'excerpt' => '{PRODUCT} price in India is latest updated on {DATE} and is available at the lowest price rate of {PRICE} INR from {VENDOR}. The internal storage of {INTERNAL} makes the smartphone one of the best {INTERNAL} Internal Memory mobiles in India. The handset is available in different unique colors including {COLOR}.',
            'keys'    => 'replace',
        ],
        'huawei'   => [
            'text'    => 'Armed with an ample amount of advanced features, the {PRODUCT} is beautifully designed by Chinese’s mobile manufacture giant, Huawei. Powered by {PROCESSOR}, the handset runs on {OS}, combined with {RAM} of RAM. As far the camerawork, the mobile phone has a {CAMERA} rear camera and a {FRONT_CAMERA} front-facing camera. Flaunting a {SCREEN_SIZE}-inch display, the device has a {INTERNAL} of internal storage. Over that, the smartphone is supported with a powerful battery backup of {BATTERY}. This device is one of the best <a href=\'/mobile/android-phones\'>Android mobiles</a>, manufactured by <a href=\'/huawei-mobiles-price-list-in-india-351\'>Huawei</a> at the price tag of {PRICE}. Compare and buy {PRODUCT} online, get delivered anywhere in India including metro cities like Delhi, Mumbai, Pune, Bangalore etc.',
            'excerpt' => '{PRODUCT} price in India is latest updated on {DATE} and is available at the lowest price rate of {PRICE} INR from {VENDOR}. The internal storage of {INTERNAL} makes the smartphone one of the best {INTERNAL} Internal Memory mobiles in India. The handset is available in different unique colors including {COLOR}.',
            'keys'    => 'replace',
        ],
        'micromax' => [
            'text'    => 'Powered by {PROCESSOR}, the {PRODUCT} runs on {OS}, combined with {RAM} of RAM. For photography front, the mobile phone has a {CAMERA} rear camera and a {FRONT_CAMERA} front-facing camera. Featuring a {SCREEN_SIZE} inch display, the handset comes with a {INTERNAL} of internal storage space. Moreover, the smartphone is backed with a {BATTERY} battery. This device is one of the best {OS_MOBILE}, manufactured by <a href=\'/micromax-mobiles-price-list-in-india-351\'>Micromax</a> at the price tag of {PRICE}. Compare and buy {PRODUCT} online at lowest prices, and get delivered anywhere in India including the metro cities like Delhi, Chennai, Chandigarh, Kolkata, etc.',
            'excerpt' => '{PRODUCT} price in India is latest updated on {DATE} and is available at the lowest price rate of {PRICE} INR from {VENDOR}. The internal storage of {INTERNAL} makes the smartphone one of the best {INTERNAL} Internal Memory mobiles in India. The handset is available in different unique colors including {COLOR}.',
            'keys'    => 'replace',
        ],
        'intex'    => [
            'text'    => 'If you like <a href=\'/intex-mobiles-price-list-in-india-351\'>Intex mobile phones</a> with quality features, have a look at the high-end features of {PRODUCT}. The device runs on {OS}, powered by {PROCESSOR}. On camera front, the handset got a {CAMERA} rear camera and a {FRONT_CAMERA} front-facing camera. Displaying a {SCREEN_SIZE} inch display, the smartphone comes with a {INTERNAL} internal storage space. Moreover, the mobile phone is fuelled with a {BATTERY} backup, paired with {RAM} of RAM. This is one of the best <a href=\'/mobile/android-phones\'>Android mobiles</a>, available at the price tag of {PRICE}. Compare and buy {PRODUCT} online at the best prices, and get delivered anywhere in India including the metro cities like Kolkata, Chennai, Chandigarh, Pune, etc.',
            'excerpt' => '{PRODUCT} price in India is latest updated on {DATE} and is available at the lowest price rate of {PRICE} INR from {VENDOR}. The internal storage of {INTERNAL} makes the smartphone one of the best {INTERNAL} Internal Memory mobiles in India. The handset is available in different unique colors including {COLOR}.',
            'keys'    => 'replace',
        ],
        'karbonn'  => [
            'text'    => 'Featuring a {SCREEN_SIZE} inch display, the {PRODUCT} has an amazing display along with powerful performance. Powered by {PROCESSOR}, the handset is based on {OS}, paired with {RAM} of RAM. On camera front, the mobile phone got a {CAMERA} rear camera and a {FRONT_CAMERA} front-facing camera. Besides, the smartphone comes with a {INTERNAL} of internal storage space, backed with a {BATTERY}. This device is one of the best {OS_MOBILE}, manufactured by <a href=\'/karbonn-mobiles-price-list-in-india-351\'>Karbonn</a> at the price tag of {PRICE}. Compare and buy {PRODUCT} online at the best prices, and get delivered anywhere in India including the metro cities like Kolkata, Chennai, Chandigarh, Pune, etc.',
            'excerpt' => '{PRODUCT} price in India is latest updated on {DATE} and is available at the lowest price rate of {PRICE} INR from {VENDOR}. The internal storage of {INTERNAL} makes the smartphone one of the best {INTERNAL} Internal Memory mobiles in India. The handset is available in different unique colors including {COLOR}.',
            'keys'    => 'replace',
        ],
        'motorola' => [
            'text'    => 'Featuring a {SCREEN_SIZE} inch display, the {PRODUCT} comes with quality features, high-end performance and elegant design. Powered by {PROCESSOR}, the mobile phone is based on {OS}, paired with {RAM} of RAM. For clicking pictures, the device has a {CAMERA} rear camera and a {FRONT_CAMERA} front-facing camera. Moreover, the smartphone is supported by {INTERNAL} internal storage space, backed with a {BATTERY}. This device is one of the best <a href=\'/mobile/android-phones\'>Android mobiles</a>, developed by <a href=\'/motorola-mobiles-price-list-in-india-351\'>Motorola</a> which is available at the price tag of {PRICE}. Compare and buy {PRODUCT} online at the best prices, and get delivered anywhere in India including the metro cities like Kolkata, Chennai, Chandigarh, Pune, etc.',
            'excerpt' => '{PRODUCT} price in India is latest updated on {DATE} and is available at the lowest price rate of {PRICE} INR from {VENDOR}. The internal storage of {INTERNAL} makes the smartphone one of the best {INTERNAL} Internal Memory mobiles in India. The handset is available in different unique colors including {COLOR}.',
            'keys'    => 'replace',
        ],
        'lg'       => [
            'text'    => 'Flaunting a {SCREEN_SIZE} inch display, the {PRODUCT} is a great combination of innovative technology and stylishness. The mobile phone is powered by {PROCESSOR} while it runs on {OS}, combined with {RAM} of RAM. For photography, the handset has got a {CAMERA} rear camera and a {FRONT_CAMERA} front-facing camera. Besides, the device is supported by {INTERNAL} internal storage space, backed with a {BATTERY}. This mobile device is one of the best <a href=\'/mobile/android-phones\'>Android mobiles</a>, developed by <a href=\'/lg-mobiles-price-list-in-india-351\'>LG</a> at the price tag of {PRICE}. Compare and buy {PRODUCT} online at the best prices, and get delivered anywhere in India including the metro cities like Kolkata, Chennai, Chandigarh, Pune, etc.',
            'excerpt' => '{PRODUCT} price in India is latest updated on {DATE} and is available at the lowest price rate of {PRICE} INR from {VENDOR}. The internal storage of {INTERNAL} makes the smartphone one of the best {INTERNAL} Internal Memory mobiles in India. The handset is available in different unique colors including {COLOR}.',
            'keys'    => 'replace',
        ],
        'nokia'    => [
            'text'    => '{PRODUCT} is one of the most efficient mobiles phones, developed by Finish multinational company Nokia. Featuring {SCREEN_SIZE} inch display, the handset is powered by {PROCESSOR} and runs on {OS}. For camera, the smartphone comes with a {CAMERA} rear camera and a {FRONT_CAMERA} front-facing camera. Besides, the device is equipped with a {INTERNAL} internal storage space, paired with {RAM} of RAM. Above all, the mobile device is supported by a {BATTERY}. This <a href=\'/nokia-mobiles-price-list-in-india-351\'>Nokia handset</a> is one of the best {OS_MOBILE}, available at the price tag of {PRICE}. Compare and buy {PRODUCT} online at the best prices, and get delivered anywhere in India including the metro cities like Delhi, Chennai, Chandigarh, Pune, etc.',
            'excerpt' => '{PRODUCT} price in India is latest updated on {DATE} and is available at the lowest price rate of {PRICE} INR from {VENDOR}. The internal storage of {INTERNAL} makes the smartphone one of the best {INTERNAL} Internal Memory mobiles in India. The handset is available in different unique colors including {COLOR}.',
            'keys'    => 'replace',
        ],
        'lenovo'   => [
            'text'    => 'Developed by a Chinese multinational company-Lenovo, {PRODUCT} is a smartphone that is equipped with quality features and stylish design. Featuring {SCREEN_SIZE} inch display, the mobile device is powered by {PROCESSOR} and runs on {OS}. As for photography, the handset got a high-quality {CAMERA} rear camera and a {FRONT_CAMERA} front-facing camera. Rather than this, the mobile phone is armed with a {INTERNAL} of internal storage space, paired with {RAM} of RAM. Above all, the device is supported by a {BATTERY}. This <a href=\'/lenovo-mobiles-price-list-in-india-351\'>Lenovo handset</a> is one of the best <a href=\'/mobile/android-phones\'>Android mobiles</a>, available at the price tag of {PRICE}. Compare and buy {PRODUCT} online at the best prices, and get delivered anywhere in India including the metro cities like Delhi, Chennai, Chandigarh, Pune, etc.',
            'excerpt' => '{PRODUCT} price in India is latest updated on {DATE} and is available at the lowest price rate of {PRICE} INR from {VENDOR}. The internal storage of {INTERNAL} makes the smartphone one of the best {INTERNAL} Internal Memory mobiles in India. The handset is available in different unique colors including {COLOR}.',
            'keys'    => 'replace',
        ],
        'asus'     => [
            'text'    => 'With great performance and stylish display of {SCREEN_SIZE} inch, the {PRODUCT} is a blend of advanced technology and elegance. The smartphone is powered by {PROCESSOR} whereas it runs on {OS}, paired with {RAM} of RAM. For photography, the device has got a {CAMERA} rear camera and a {FRONT_CAMERA} front-facing camera. Other than that, the mobile phone is supported by {INTERNAL} of internal storage space, backed with a {BATTERY}. This <a href=\'/asus-mobiles-price-list-in-india-351\'>handset of Asus</a> is one of the finest <a href=\'/mobile/android-phones\'>Android mobiles</a> that is available at the price tag of {PRICE}. Compare and buy {PRODUCT} online at the best prices, and get delivered anywhere in India including the metro cities like Delhi, Jaipur, Bangalore, Chennai, etc.',
            'excerpt' => '{PRODUCT} price in India is latest updated on {DATE} and is available at the lowest price rate of {PRICE} INR from {VENDOR}. The internal storage of {INTERNAL} makes the smartphone one of the best {INTERNAL} Internal Memory mobiles in India. The handset is available in different unique colors including {COLOR}.',
            'keys'    => 'replace',
        ],
        'htc'      => [
            'text'    => 'The {PRODUCT} is powered by {PROCESSOR}, combined with {RAM} of RAM. Based on {OS}, the handset is equipped with {CAMERA} rear camera and a {FRONT_CAMERA} front-facing camera. Featuring a {SCREEN_SIZE}-inch display, the smartphone has got a {INTERNAL} of internal storage space, backed by a {BATTERY}. This handset is one of the finest <a href=\'/mobile/android-phones\'>Android mobiles</a>, manufactured by a Taiwanese multinational company, <a href=\'/htc-mobiles-price-list-in-india-351\'>HTC</a> at the price tag of {PRICE}. Compare and buy {PRODUCT} online at the best prices, and get delivered anywhere in India including the metro cities like Delhi, Jaipur, Bangalore, Chennai, etc.',
            'excerpt' => '{PRODUCT} price in India is latest updated on {DATE} and is available at the lowest price rate of {PRICE} INR from {VENDOR}. The internal storage of {INTERNAL} makes the smartphone one of the best {INTERNAL} Internal Memory mobiles in India. The handset is available in different unique colors including {COLOR}.',
            'keys'    => 'replace',
        ],
        'vivo'     => [
            'text'    => 'The <a href=\'/vivo-mobiles-price-list-in-india-351\'>Vivo</a> has designed {PRODUCT}, keeping the requirements of the customer in mind. The mobile phone has the display of {SCREEN_SIZE} inches. In terms of optics, the smartphone is having the rear camera of {CAMERA} and the front camera of {FRONT_CAMERA}. Furthermore, the handset is housed with the battery of {BATTERY}. For the proper functioning of the cell phone, the device is equipped with the {OS}. The {PRODUCT} is driven by a {PROCESSOR} along with the {RAM} RAM. Moreover, the product is featured with the built-in storage of {INTERNAL}. Compare and buy {PRODUCT} online at the best prices, and get delivered anywhere in India including the metro cities like Mumbai, Chandigarh, Bangalore, Ahmedabad, etc.',
            'excerpt' => '{PRODUCT} price in India is latest updated on {DATE} and is available at the lowest price rate of {PRICE} INR from {VENDOR}. The internal storage of {INTERNAL} makes the smartphone one of the best {INTERNAL} Internal Memory mobiles in India. The handset is available in different unique colors including {COLOR}.',
            'keys'    => 'replace',
        ],
    ]
];