<?php

return [
    'smart-wearabl-price-list-in-india'                                  => 'electronics/smart-wearable-price-list-in-india.html',
    'women/kurtas-kurtis/kurtis-price-list-in-india'                     => 'women/ethnic-clothing/kurtas-kurtis-price-list-in-india.html',
    'mobile/smart-wearable-price-list-in-india'                          => 'electronics/smart-wearable-price-list-in-india.html',
    'beauty-health/beauty-health-price-list-in-india'                    => 'beauty-health',
    'home-decor/pricelist/hand-tool-price-list-in-india'                 => 'home-decor/hardware/hand-tool-price-list-in-india.html',
    'computers/kitchen-appliances/electric-kettles-price-list-in-india'  => 'appliances/kitchen-appliances/electric-kettles-price-list-in-india.html',
    'automotive/automotive-price-list-in-india'                          => 'automotive',
    'home-decor/home-decor-price-list-in-india'                          => 'home-decor',
    'tablet-accessories-price-list-in-india'                             => 'mobile/tablet-accessories-price-list-in-india.html',
    'mobile/headphones-headsets/bluetoot-headsets-price-list-in-india'   => 'mobile/headphones-headsets/bluetooth-headsets-price-list-in-india.html',
    'product/intex-tubo-turbo-s5-price-list-in-india'                    => 'intex-turbo-s5-price-in-india-896',
    'product/samsung-43j5100-43-inch-full-hd-led-tv-price-list-in-india' => 'samsung-galaxy-j5-price-in-india-5',
    'snowbird-sb-kl012-electric-kettle-price-list-in-india'              => 'appliances/kitchen-appliances/electric-kettles-price-list-in-india.html',
    'product/cruiser-4-blade-1200mm-ceiling-fan-price-list-in-india'     => 'standard-cruiser-4-blade-1200mm-ceiling-fan-price-in-india-36913',
    'product/syska-hf-740t-stereo-bluetooth-headset-price-list-in-india' => 'syska-981a-bluetooth-headset-price-in-india-124446',
    '/list-of-flowers/bouquet-of-flowers'                                => '/',
    '/log'                                                               => '/',
    '/wp-login.php'                                                      => '/',
    '/ext/HomepageButtons.png-price-list-in-india.html'                  => '/',
    '/upcoming-mobiles-in-india/%7Bpage?}'                               => 'upcoming-mobiles-in-india',
    '/12?src=pd'                                                         => '',
    '/men/shoes/flats-price-list-in-india.html'                          => 'women/shoes/flats-price-list-in-india.html',
    '/lifestyle/[]]'                                                     => 'lifestyle',
    '/sitemap/brand-comparative-sitemap-1.xml'                           => '/sitemap/sitemap-brand-comparative.xml',
    '/category-sitemap.xml'                                              => '/sitemap-category.xml',
    '/static-sitemap.xml'                                                => '/sitemap-index.xml',
];