<?php
return [
    'name'                 => [
        "0"  => "Multiple Sellers",
        "1"  => "Flipkart",
        "2"  => "Jabong",
        "3"  => "Amazon",
        "4"  => "Myntra",
        "5"  => "Homeshop18",
        "6"  => "Naaptol",
        "7"  => "Shopclues",
        "8"  => "AJIO",
        "9"  => "eZoneOnline",
        "10" => "Clovia",
        "11" => "Dominos",
        "12" => "Shein",
        "13" => "ABOF",
        "14" => "Kraftly",
        "15" => "mi",
        "16" => "snapdeal",
        "17" => "pepperfry",
        "18" => "Infibeam",
        "19" => "saholic",
        "20" => "croma",
        "21" => "thedostore",
        "22" => "voonik",
        "23" => "Firstcry",
        "24" => "lenskart",
        "25" => "fnp",
        "26" => "fashionandyou",
        "27" => "americanswan",
        "28" => "Peachmode",
        "29" => "shopperzville",
        "30" => "fabfurnish",
        "31" => "urbandazzle",
        "32" => "healthkart",
        "33" => "urbanladder",
        "34" => "koovs",
        "35" => "zivame",
        "36" => "prettysecrets",
        "37" => "onlymobiles",
        "38" => "gadgetsnow",
        "39" => "Craftsvilla",
        "40" => "Ebay",
        "41" => "LimeRoad",
        "42" => "StalkBuyLove",
        "43" => "YepMe",
        "44" => "Paytm",
        "45" => "FashionandYou",
        "46" => "poorvikamobile",
        "47" => "bagittoday",
        "48" => "theelectronicstore",
        "49" => "theitdepot",
        "50" => "syberplace",
        "51" => "shopmonk",
        "52" => "next",
        "53" => "gadgets360",
        "54" => "tatacliq",
        "55" => "wish n buy",
        "56" => "shopcj",
    ],
    'logo'                 => [
        "1"  => "//www.indiashopps.com/assets/vendor_logo/flipkart_logo.png",
        "2"  => "//www.indiashopps.com/assets/vendor_logo/jabong_logo.png",
        "3"  => "//www.indiashopps.com/assets/vendor_logo/amazon_logo.png",
        "4"  => "//www.indiashopps.com/assets/vendor_logo/myntra_logo.png",
        "5"  => "//www.indiashopps.com/assets/vendor_logo/homeshop18_logo.png",
        "6"  => "//www.indiashopps.com/assets/vendor_logo/naaptol_logo.png",
        "7"  => "//www.indiashopps.com/assets/vendor_logo/shopclues_logo.png",
        "8"  => "//www.indiashopps.com/assets/vendor_logo/ajio_logo.jpg",
        "9"  => "//www.indiashopps.com/assets/vendor_logo/Maniacstore.png",
        "10" => "/assets/vendor_logo/clovia.png",
        "11" => "//www.indiashopps.com/assets/vendor_logo/ezoneonline_logo.jpg",
        "12" => "/assets/vendor_logo/shein.png",
        "13" => "//www.indiashopps.com/assets/vendor_logo/abof_logo.jpg",
        "14" => "//www.indiashopps.com/assets/vendor_logo/kraftly_logo.jpg",
        "15" => "//www.indiashopps.com/assets/vendor_logo/mi_logo.png",
        "16" => "//www.indiashopps.com/assets/vendor_logo/snapdeal_logo.png",
        "17" => "//www.indiashopps.com/assets/vendor_logo/pepperfry_logo.png",
        "18" => "//www.indiashopps.com/assets/vendor_logo/Infibeam_logo.png",
        "19" => "//www.indiashopps.com/assets/vendor_logo/saholic_logo.png",
        "20" => "//www.indiashopps.com/assets/vendor_logo/croma_logo.png",
        "21" => "//www.indiashopps.com/assets/vendor_logo/thedostore_logo.png",
        "22" => "//www.indiashopps.com/assets/vendor_logo/voonik_logo.jpg",
        "23" => "//www.indiashopps.com/assets/vendor_logo/firstcry_logo.png",
        "24" => "//www.indiashopps.com/assets/vendor_logo/lenskart_logo.png",
        "25" => "//www.indiashopps.com/assets/vendor_logo/fnp_logo.png",
        "26" => "//www.indiashopps.com/assets/vendor_logo/fashionandyou_logo.png",
        "27" => "//www.indiashopps.com/assets/vendor_logo/americanswan_logo.png",
        "28" => "/assets/vendor_logo/peachmode.png",
        "29" => "//www.indiashopps.com/assets/vendor_logo/shopperzville_logo.png",
        "30" => "//www.indiashopps.com/assets/vendor_logo/fabfurnish_logo.png",
        "31" => "//www.indiashopps.com/assets/vendor_logo/urbandazzle_logo.png",
        "32" => "//www.indiashopps.com/assets/vendor_logo/healthkart_logo.png",
        "33" => "//www.indiashopps.com/assets/vendor_logo/urban_ladder_logo.png",
        "34" => "//www.indiashopps.com/assets/vendor_logo/koovs_logo.png",
        "35" => "//www.indiashopps.com/assets/vendor_logo/zivame_logo.png",
        "36" => "//www.indiashopps.com/assets/vendor_logo/prettysecrets_logo.png",
        "37" => "//www.indiashopps.com/assets/vendor_logo/onlymobiles_logo.jpg",
        "38" => "//www.indiashopps.com/assets/vendor_logo/gadgetsnow_logo.jpg",
        "39" => "/assets/vendor_logo/craftsvilla.png",
        "40" => "//www.indiashopps.com/assets/vendor_logo/ebayi_logo.png",
        "41" => "//www.indiashopps.com/assets/vendor_logo/limeroad_logo.png",
        "42" => "//www.indiashopps.com/assets/vendor_logo/StalkBuyLove_logo.png",
        "43" => "//www.indiashopps.com/assets/vendor_logo/yepme_logo.png",
        "44" => "//www.indiashopps.com/assets/vendor_logo/paytmmall.png",
        "45" => "//www.indiashopps.com/assets/vendor_logo/fashionandyou_logo.png",
        "46" => "//www.indiashopps.com/assets/vendor_logo/poorvikamobile_logo.jpg",
        "47" => "//www.indiashopps.com/assets/vendor_logo/bagittoday_logo.png",
        "48" => "//www.indiashopps.com/assets/vendor_logo/theelectronicstore_logo.png",
        "49" => "//www.indiashopps.com/assets/vendor_logo/theitdepot_logo.png",
        "50" => "//www.indiashopps.com/assets/vendor_logo/syberplace.png",
        "51" => "//www.indiashopps.com/assets/vendor_logo/shopmonk.png",
        "52" => "//www.indiashopps.com/assets/vendor_logo/next.png",
        "53" => "//www.indiashopps.com/assets/vendor_logo/gadgets360.png",
        "54" => "//www.indiashopps.com/assets/vendor_logo/tata_logo.png",
        "55" => "//www.indiashopps.com/assets/vendor_logo/wish-buy-logo.jpg",
        "56" => "//www.indiashopps.com/assets/vendor_logo/shopcj-logo.jpg"
    ],
    'vend_logo'            => [
        "1"  => "//www.indiashopps.com/assets/vendor_logo/flipkart_logo.png",
        "2"  => "//www.indiashopps.com/assets/vendor_logo/jabong_logo.png",
        "3"  => "//www.indiashopps.com/assets/vendor_logo/amazon_logo.png",
        "4"  => "//www.indiashopps.com/assets/vendor_logo/myntra_logo.png",
        "5"  => "//www.indiashopps.com/assets/vendor_logo/homeshop18_logo.png",
        "6"  => "//www.indiashopps.com/assets/vendor_logo/naaptol_logo.png",
        "7"  => "//www.indiashopps.com/assets/vendor_logo/shopclues_logo.png",
        "8"  => "//www.indiashopps.com/assets/vendor_logo/ajio_logo.jpg",
        "9"  => "//www.indiashopps.com/assets/vendor_logo/Maniacstore.png",
        "10" => "/assets/vendor_logo/clovia.png",
        "11" => "//www.indiashopps.com/assets/vendor_logo/ezoneonline_logo.jpg",
        "12" => "/assets/vendor_logo/shein.png",
        "13" => "//www.indiashopps.com/assets/vendor_logo/abof_logo.jpg",
        "14" => "//www.indiashopps.com/assets/vendor_logo/kraftly_logo.jpg",
        "15" => "//www.indiashopps.com/assets/vendor_logo/mi_logo.png",
        "16" => "//www.indiashopps.com/assets/vendor_logo/snapdeal_logo.png",
        "17" => "//www.indiashopps.com/assets/vendor_logo/pepperfry_logo.png",
        "18" => "//www.indiashopps.com/assets/vendor_logo/Infibeam_logo.png",
        "19" => "//www.indiashopps.com/assets/vendor_logo/saholic_logo.png",
        "20" => "//www.indiashopps.com/assets/vendor_logo/croma_logo.png",
        "21" => "//www.indiashopps.com/assets/vendor_logo/thedostore_logo.png",
        "22" => "//www.indiashopps.com/assets/vendor_logo/voonik_logo.jpg",
        "23" => "//www.indiashopps.com/assets/vendor_logo/firstcry_logo.png",
        "24" => "//www.indiashopps.com/assets/vendor_logo/lenskart_logo.png",
        "25" => "//www.indiashopps.com/assets/vendor_logo/fnp_logo.png",
        "26" => "//www.indiashopps.com/assets/vendor_logo/fashionandyou_logo.png",
        "27" => "//www.indiashopps.com/assets/vendor_logo/americanswan_logo.png",
        "28" => "/assets/vendor_logo/peachmode.png",
        "29" => "//www.indiashopps.com/assets/vendor_logo/shopperzville_logo.png",
        "30" => "//www.indiashopps.com/assets/vendor_logo/fabfurnish_logo.png",
        "31" => "//www.indiashopps.com/assets/vendor_logo/urbandazzle_logo.png",
        "32" => "//www.indiashopps.com/assets/vendor_logo/healthkart_logo.png",
        "33" => "//www.indiashopps.com/assets/vendor_logo/urban_ladder_logo.png",
        "34" => "//www.indiashopps.com/assets/vendor_logo/koovs_logo.png",
        "35" => "//www.indiashopps.com/assets/vendor_logo/zivame_logo.png",
        "36" => "//www.indiashopps.com/assets/vendor_logo/prettysecrets_logo.png",
        "37" => "//www.indiashopps.com/assets/vendor_logo/onlymobiles_logo.jpg",
        "38" => "//www.indiashopps.com/assets/vendor_logo/gadgetsnow_logo.jpg",
        "39" => "/assets/vendor_logo/craftsvilla.png",
        "40" => "//www.indiashopps.com/assets/vendor_logo/ebayi_logo.png",
        "41" => "//www.indiashopps.com/assets/vendor_logo/limeroad_logo.png",
        "42" => "//www.indiashopps.com/assets/vendor_logo/StalkBuyLove_logo.png",
        "43" => "//www.indiashopps.com/assets/vendor_logo/yepme_logo.png",
        "44" => "//www.indiashopps.com/assets/vendor_logo/paytmmall.png",
        "45" => "//www.indiashopps.com/assets/vendor_logo/fashionandyou_logo.png",
        "46" => "//www.indiashopps.com/assets/vendor_logo/poorvikamobile_logo.jpg",
        "47" => "//www.indiashopps.com/assets/vendor_logo/bagittoday_logo.png",
        "48" => "//www.indiashopps.com/assets/vendor_logo/theelectronicstore_logo.png",
        "49" => "//www.indiashopps.com/assets/vendor_logo/theitdepot_logo.png",
        "50" => "//www.indiashopps.com/assets/vendor_logo/syberplace.png",
        "51" => "//www.indiashopps.com/assets/vendor_logo/shopmonk.png",
        "52" => "//www.indiashopps.com/assets/vendor_logo/next.png",
        "53" => "//www.indiashopps.com/assets/vendor_logo/gadgets360.png",
        "54" => "//www.indiashopps.com/assets/vendor_logo/tata_logo.png",
        "55" => "//www.indiashopps.com/assets/vendor_logo/wish-buy-logo.jpg",
        "56" => "//www.indiashopps.com/assets/vendor_logo/shopcj-logo.jpg"
    ],
    'url'                  => [
        "1"  => "http://www.flipkart.com",
        "2"  => "http://www.jabong.com",
        "3"  => "http://www.amazon.in",
        "4"  => "http://www.myntra.com",
        "5"  => "http://www.homeshop18.com",
        "6"  => "http://www.naaptol.com",
        "7"  => "http://www.shopclues.com",
        "8"  => "https://www.ajio.com/",
        "9"  => "http://www.maniacstore.com",
        "10" => "https://www.clovia.com",
        "11" => "http://www.ezoneonline.in",
        "12" => "http://www.shopbychoice.com",
        "13" => "http://www.makemytrip.com",
        "14" => "http://www.kraftly.com",
        "15" => "http://www.mi.com",
        "16" => "http://www.snapdeal.com",
        "17" => "http://www.pepperfry.com",
        "18" => "http://www.infibeam.com",
        "19" => "http://www.saholic.com",
        "20" => "http://www.croma.com",
        "21" => "http://www.thedostore.com",
        "22" => "https://www.voonik.com",
        "23" => "http://www.firstcry.com",
        "24" => "http://www.lenskart.com",
        "25" => "http://www.fnp.com",
        "26" => "http://www.fashionandyou.com",
        "27" => "http://www.americanswan.com",
        "28" => "http://www.babyoye.com",
        "29" => "http://www.shopperzville.com",
        "30" => "http://www.fabfurnish.com",
        "31" => "http://www.urbandazzle.com",
        "32" => "http://www.healthkart.com",
        "33" => "http://www.urbanladder.com",
        "34" => "http://www.koovs.com",
        "35" => "http://www.zivame.com",
        "36" => "http://www.prettysecrets.com",
        "37" => "https://www.onlymobiles.com",
        "38" => "http://www.shop.gadgetsnow.com",
        "39" => "http://www.foodpanda.com",
        "40" => "http://www.ebay.in",
        "41" => "http://www.limeroad.com",
        "42" => "http://www.StalkBuyLove.com",
        "43" => "http://www.yepme.com",
        "44" => "http://paytm.com",
        "45" => "http://www.fashionandyou.com",
        "46" => "http://www.poorvikamobile.com",
        "47" => "http://www.bagittoday.com",
        "48" => "http://www.theelectronicstore.in",
        "49" => "http://www.theitdepot.com",
        "50" => "http://www.syberplace.com",
        "51" => "http://www.shopmonk.com",
        "52" => "http://www.next.co.in",
        "53" => "http://www.gadgets360.com",
        "54" => "https://www.tatacliq.com",
        "55" => "https://www.wishnbuy.com",
        "56" => "https://www.shopcj.com"
    ],
    "comparitive_category" => [
        301,
        311,
        312,
        313,
        317,
        318,
        319,
        320,
        321,
        322,
        323,
        324,
        325,
        326,
        327,
        328,
        330,
        331,
        332,
        333,
        334,
        335,
        336,
        337,
        338,
        339,
        340,
        341,
        342,
        344,
        345,
        346,
        347,
        348,
        351,
        352,
        359,
        360,
        361,
        362,
        364,
        365,
        366,
        370,
        371,
        372,
        374,
        379,
        381,
        382,
        384,
        390,
        392,
        407,
        427,
        435,
        436,
        437,
        445,
        446,
        447,
        448,
        470,
        471,
        472,
        473,
        476,
        489,
        492,
        505,
        622,
        623,
        624,
        626,
        627,
        628,
        632,
        633,
        635,
        636,
        637,
        638,
        639,
        640,
        383,
        386,
        387,
        388,
        391,
        393,
        394,
        395,
        396,
        397,
        398,
        399,
        401,
        402,
        403,
        406,
        409,
        410,
        411,
        412,
        415,
        416,
        417,
        418,
        421,
        422,
        423,
        424,
        425,
        426,
        428,
        429,
        430,
        431,
        432,
        433,
        438,
        439,
        441,
        442,
        443,
        450,
        451,
        452,
        453,
        454,
        455,
        456,
        457,
        458,
        459,
        460,
        461,
        463,
        468,
        474,
        475,
        478,
        479,
        480,
        481,
        482,
        483,
        484,
        486,
        487,
        488,
        490,
        491,
        494,
        495,
        496,
        497,
        499,
        500,
        501,
        504,
        506,
        507,
        508,
        509,
        510,
        511,
        515,
        516,
        517,
        518,
        519,
        520,
        521,
        522,
        523,
        528,
        549,
        550,
        551,
        552,
        554,
        555,
        556,
        558,
        584,
        629,
        630,
        631
    ],
    'all_brand_category'   => [351, 352, 379, 445, 446, 471, 472],
    'category_icons'       => [
        'mobile'         => 'mobile',
        'men'            => 'male',
        'women'          => 'female',
        'books'          => 'book',
        'home-decor'     => 'home',
        'appliances'     => 'plug',
        'electronics'    => 'television',
        'computers'      => 'laptop',
        'camera'         => 'camera',
        'beauty-health'  => 'medkit',
        'care'           => 'universal-access',
        'sports-fitness' => 'wheelchair-alt',
        'kids'           => 'child',
        'lifestyle'      => 'life-ring',
        'automotive'     => 'car'
    ],
    'remove_brand_link'    => [
        360,
        361,
        362,
        364,
        366,
        370,
        371,
        372,
        374,
        381,
        382,
        383,
        384,
        386,
        387,
        388,
        391,
        392,
        393,
        394,
        396,
        397,
        398,
        399,
        401,
        402,
        403,
        406,
        407,
        409,
        410,
        411,
        412,
        415,
        416,
        417,
        418,
        421,
        422,
        423,
        424,
        425,
        426,
        427,
        428,
        429,
        430,
        431,
        432,
        433,
        435,
        436,
        437,
        438,
        439,
        441,
        442,
        443,
        473,
        474,
        475,
        476,
        478,
        479,
        480,
        481,
        482,
        483,
        484,
        487,
        488,
        489,
        490,
        491,
        492,
        494,
        495,
        496,
        497,
        499,
        500,
        501,
        317,
        318,
        319,
        320,
        321,
        322,
        323,
        324,
        325,
        326,
        327,
        328,
        329,
        623,
        624,
        633,
        626,
        627,
        628,
        629,
        630,
        631,
        632,
        638,
        331,
        332,
        333,
        334,
        335,
        336,
        337,
        338,
        339,
        340,
        341,
        342,
        639,
        344,
        345,
        346,
        347,
        348,
        635,
        636,
        446,
        450,
        451,
        452,
        453,
        454,
        455,
        456,
        457,
        458,
        459,
        460,
        461,
        622,
        463,
        468,
        359,
        365,
        311,
        637,
        640,
        528,
        554,
        555,
        556,
        549,
        550,
        584,
        506,
        507,
        505,
        504,
        508,
        509,
        510,
        511,
        515,
        516,
        517,
        518,
        519,
        520,
        521,
        522,
        52
    ],
];